package unicode.tr29.internal;
//Autogenerated, do not edit
class GraphemeValues {
    public static var m = {
        var codes = unicode.tr29.internal.GraphemeCodes.codes; 
        var b = new haxe.ds.BalancedTree();
        for (c in codes) {
            var e = Type.createEnum(GraphemeValuesEnum, c.ctor);
            b.set(c.code, e);
        }
        b;
    }
    public static function get(code:Int):GraphemeValuesEnum {
        var res = m.get(code);
        return res == null ? Other : res;
    }
}
enum GraphemeValuesEnum {
    L;
    Other;
    SpacingMark;
    T;
    E_Base;
    Control;
    LVT;
    E_Base_GAZ;
    Prepend;
    LV;
    ZWJ;
    V;
    LF;
    E_Modifier;
    Regional_Indicator;
    CR;
    Extend;
    Glue_After_Zwj;
}
