package unicode.tr29.internal;
//Autogenerated, do not edit
class GraphemeValues {
        static var m = [
        1757 => Prepend,
        1807 => Prepend,
        2274 => Prepend,
        3406 => Prepend,
        69821 => Prepend,
        13 => CR,
        10 => LF,
        173 => Control,
        1564 => Control,
        6158 => Control,
        8203 => Control,
        8232 => Control,
        8233 => Control,
        8293 => Control,
        65279 => Control,
        917504 => Control,
        917505 => Control,
        1471 => Extend,
        1479 => Extend,
        1648 => Extend,
        1809 => Extend,
        2362 => Extend,
        2364 => Extend,
        2381 => Extend,
        2433 => Extend,
        2492 => Extend,
        2494 => Extend,
        2509 => Extend,
        2519 => Extend,
        2620 => Extend,
        2641 => Extend,
        2677 => Extend,
        2748 => Extend,
        2765 => Extend,
        2817 => Extend,
        2876 => Extend,
        2878 => Extend,
        2879 => Extend,
        2893 => Extend,
        2902 => Extend,
        2903 => Extend,
        2946 => Extend,
        3006 => Extend,
        3008 => Extend,
        3021 => Extend,
        3031 => Extend,
        3072 => Extend,
        3201 => Extend,
        3260 => Extend,
        3263 => Extend,
        3266 => Extend,
        3270 => Extend,
        3329 => Extend,
        3390 => Extend,
        3405 => Extend,
        3415 => Extend,
        3530 => Extend,
        3535 => Extend,
        3542 => Extend,
        3551 => Extend,
        3633 => Extend,
        3761 => Extend,
        3893 => Extend,
        3895 => Extend,
        3897 => Extend,
        4038 => Extend,
        4226 => Extend,
        4237 => Extend,
        4253 => Extend,
        6086 => Extend,
        6109 => Extend,
        6313 => Extend,
        6450 => Extend,
        6683 => Extend,
        6742 => Extend,
        6752 => Extend,
        6754 => Extend,
        6783 => Extend,
        6846 => Extend,
        6964 => Extend,
        6972 => Extend,
        6978 => Extend,
        7142 => Extend,
        7149 => Extend,
        7405 => Extend,
        7412 => Extend,
        8204 => Extend,
        8417 => Extend,
        11647 => Extend,
        42607 => Extend,
        43010 => Extend,
        43014 => Extend,
        43019 => Extend,
        43443 => Extend,
        43452 => Extend,
        43493 => Extend,
        43587 => Extend,
        43596 => Extend,
        43644 => Extend,
        43696 => Extend,
        43713 => Extend,
        43766 => Extend,
        44005 => Extend,
        44008 => Extend,
        44013 => Extend,
        64286 => Extend,
        66045 => Extend,
        66272 => Extend,
        68159 => Extend,
        69633 => Extend,
        70003 => Extend,
        70196 => Extend,
        70206 => Extend,
        70367 => Extend,
        70460 => Extend,
        70462 => Extend,
        70464 => Extend,
        70487 => Extend,
        70726 => Extend,
        70832 => Extend,
        70842 => Extend,
        70845 => Extend,
        71087 => Extend,
        71229 => Extend,
        71339 => Extend,
        71341 => Extend,
        71351 => Extend,
        72767 => Extend,
        119141 => Extend,
        121461 => Extend,
        121476 => Extend,
        2307 => SpacingMark,
        2363 => SpacingMark,
        2563 => SpacingMark,
        2691 => SpacingMark,
        2761 => SpacingMark,
        2880 => SpacingMark,
        3007 => SpacingMark,
        3262 => SpacingMark,
        3635 => SpacingMark,
        3763 => SpacingMark,
        3967 => SpacingMark,
        4145 => SpacingMark,
        4228 => SpacingMark,
        6070 => SpacingMark,
        6741 => SpacingMark,
        6743 => SpacingMark,
        6916 => SpacingMark,
        6965 => SpacingMark,
        6971 => SpacingMark,
        7042 => SpacingMark,
        7073 => SpacingMark,
        7082 => SpacingMark,
        7143 => SpacingMark,
        7150 => SpacingMark,
        7393 => SpacingMark,
        43047 => SpacingMark,
        43395 => SpacingMark,
        43597 => SpacingMark,
        43755 => SpacingMark,
        43765 => SpacingMark,
        44012 => SpacingMark,
        69632 => SpacingMark,
        69634 => SpacingMark,
        69762 => SpacingMark,
        69932 => SpacingMark,
        70018 => SpacingMark,
        70197 => SpacingMark,
        70463 => SpacingMark,
        70725 => SpacingMark,
        70841 => SpacingMark,
        70846 => SpacingMark,
        70849 => SpacingMark,
        71102 => SpacingMark,
        71230 => SpacingMark,
        71340 => SpacingMark,
        71350 => SpacingMark,
        71462 => SpacingMark,
        72751 => SpacingMark,
        72766 => SpacingMark,
        72873 => SpacingMark,
        72881 => SpacingMark,
        72884 => SpacingMark,
        119142 => SpacingMark,
        119149 => SpacingMark,
        44032 => LV,
        44060 => LV,
        44088 => LV,
        44116 => LV,
        44144 => LV,
        44172 => LV,
        44200 => LV,
        44228 => LV,
        44256 => LV,
        44284 => LV,
        44312 => LV,
        44340 => LV,
        44368 => LV,
        44396 => LV,
        44424 => LV,
        44452 => LV,
        44480 => LV,
        44508 => LV,
        44536 => LV,
        44564 => LV,
        44592 => LV,
        44620 => LV,
        44648 => LV,
        44676 => LV,
        44704 => LV,
        44732 => LV,
        44760 => LV,
        44788 => LV,
        44816 => LV,
        44844 => LV,
        44872 => LV,
        44900 => LV,
        44928 => LV,
        44956 => LV,
        44984 => LV,
        45012 => LV,
        45040 => LV,
        45068 => LV,
        45096 => LV,
        45124 => LV,
        45152 => LV,
        45180 => LV,
        45208 => LV,
        45236 => LV,
        45264 => LV,
        45292 => LV,
        45320 => LV,
        45348 => LV,
        45376 => LV,
        45404 => LV,
        45432 => LV,
        45460 => LV,
        45488 => LV,
        45516 => LV,
        45544 => LV,
        45572 => LV,
        45600 => LV,
        45628 => LV,
        45656 => LV,
        45684 => LV,
        45712 => LV,
        45740 => LV,
        45768 => LV,
        45796 => LV,
        45824 => LV,
        45852 => LV,
        45880 => LV,
        45908 => LV,
        45936 => LV,
        45964 => LV,
        45992 => LV,
        46020 => LV,
        46048 => LV,
        46076 => LV,
        46104 => LV,
        46132 => LV,
        46160 => LV,
        46188 => LV,
        46216 => LV,
        46244 => LV,
        46272 => LV,
        46300 => LV,
        46328 => LV,
        46356 => LV,
        46384 => LV,
        46412 => LV,
        46440 => LV,
        46468 => LV,
        46496 => LV,
        46524 => LV,
        46552 => LV,
        46580 => LV,
        46608 => LV,
        46636 => LV,
        46664 => LV,
        46692 => LV,
        46720 => LV,
        46748 => LV,
        46776 => LV,
        46804 => LV,
        46832 => LV,
        46860 => LV,
        46888 => LV,
        46916 => LV,
        46944 => LV,
        46972 => LV,
        47000 => LV,
        47028 => LV,
        47056 => LV,
        47084 => LV,
        47112 => LV,
        47140 => LV,
        47168 => LV,
        47196 => LV,
        47224 => LV,
        47252 => LV,
        47280 => LV,
        47308 => LV,
        47336 => LV,
        47364 => LV,
        47392 => LV,
        47420 => LV,
        47448 => LV,
        47476 => LV,
        47504 => LV,
        47532 => LV,
        47560 => LV,
        47588 => LV,
        47616 => LV,
        47644 => LV,
        47672 => LV,
        47700 => LV,
        47728 => LV,
        47756 => LV,
        47784 => LV,
        47812 => LV,
        47840 => LV,
        47868 => LV,
        47896 => LV,
        47924 => LV,
        47952 => LV,
        47980 => LV,
        48008 => LV,
        48036 => LV,
        48064 => LV,
        48092 => LV,
        48120 => LV,
        48148 => LV,
        48176 => LV,
        48204 => LV,
        48232 => LV,
        48260 => LV,
        48288 => LV,
        48316 => LV,
        48344 => LV,
        48372 => LV,
        48400 => LV,
        48428 => LV,
        48456 => LV,
        48484 => LV,
        48512 => LV,
        48540 => LV,
        48568 => LV,
        48596 => LV,
        48624 => LV,
        48652 => LV,
        48680 => LV,
        48708 => LV,
        48736 => LV,
        48764 => LV,
        48792 => LV,
        48820 => LV,
        48848 => LV,
        48876 => LV,
        48904 => LV,
        48932 => LV,
        48960 => LV,
        48988 => LV,
        49016 => LV,
        49044 => LV,
        49072 => LV,
        49100 => LV,
        49128 => LV,
        49156 => LV,
        49184 => LV,
        49212 => LV,
        49240 => LV,
        49268 => LV,
        49296 => LV,
        49324 => LV,
        49352 => LV,
        49380 => LV,
        49408 => LV,
        49436 => LV,
        49464 => LV,
        49492 => LV,
        49520 => LV,
        49548 => LV,
        49576 => LV,
        49604 => LV,
        49632 => LV,
        49660 => LV,
        49688 => LV,
        49716 => LV,
        49744 => LV,
        49772 => LV,
        49800 => LV,
        49828 => LV,
        49856 => LV,
        49884 => LV,
        49912 => LV,
        49940 => LV,
        49968 => LV,
        49996 => LV,
        50024 => LV,
        50052 => LV,
        50080 => LV,
        50108 => LV,
        50136 => LV,
        50164 => LV,
        50192 => LV,
        50220 => LV,
        50248 => LV,
        50276 => LV,
        50304 => LV,
        50332 => LV,
        50360 => LV,
        50388 => LV,
        50416 => LV,
        50444 => LV,
        50472 => LV,
        50500 => LV,
        50528 => LV,
        50556 => LV,
        50584 => LV,
        50612 => LV,
        50640 => LV,
        50668 => LV,
        50696 => LV,
        50724 => LV,
        50752 => LV,
        50780 => LV,
        50808 => LV,
        50836 => LV,
        50864 => LV,
        50892 => LV,
        50920 => LV,
        50948 => LV,
        50976 => LV,
        51004 => LV,
        51032 => LV,
        51060 => LV,
        51088 => LV,
        51116 => LV,
        51144 => LV,
        51172 => LV,
        51200 => LV,
        51228 => LV,
        51256 => LV,
        51284 => LV,
        51312 => LV,
        51340 => LV,
        51368 => LV,
        51396 => LV,
        51424 => LV,
        51452 => LV,
        51480 => LV,
        51508 => LV,
        51536 => LV,
        51564 => LV,
        51592 => LV,
        51620 => LV,
        51648 => LV,
        51676 => LV,
        51704 => LV,
        51732 => LV,
        51760 => LV,
        51788 => LV,
        51816 => LV,
        51844 => LV,
        51872 => LV,
        51900 => LV,
        51928 => LV,
        51956 => LV,
        51984 => LV,
        52012 => LV,
        52040 => LV,
        52068 => LV,
        52096 => LV,
        52124 => LV,
        52152 => LV,
        52180 => LV,
        52208 => LV,
        52236 => LV,
        52264 => LV,
        52292 => LV,
        52320 => LV,
        52348 => LV,
        52376 => LV,
        52404 => LV,
        52432 => LV,
        52460 => LV,
        52488 => LV,
        52516 => LV,
        52544 => LV,
        52572 => LV,
        52600 => LV,
        52628 => LV,
        52656 => LV,
        52684 => LV,
        52712 => LV,
        52740 => LV,
        52768 => LV,
        52796 => LV,
        52824 => LV,
        52852 => LV,
        52880 => LV,
        52908 => LV,
        52936 => LV,
        52964 => LV,
        52992 => LV,
        53020 => LV,
        53048 => LV,
        53076 => LV,
        53104 => LV,
        53132 => LV,
        53160 => LV,
        53188 => LV,
        53216 => LV,
        53244 => LV,
        53272 => LV,
        53300 => LV,
        53328 => LV,
        53356 => LV,
        53384 => LV,
        53412 => LV,
        53440 => LV,
        53468 => LV,
        53496 => LV,
        53524 => LV,
        53552 => LV,
        53580 => LV,
        53608 => LV,
        53636 => LV,
        53664 => LV,
        53692 => LV,
        53720 => LV,
        53748 => LV,
        53776 => LV,
        53804 => LV,
        53832 => LV,
        53860 => LV,
        53888 => LV,
        53916 => LV,
        53944 => LV,
        53972 => LV,
        54000 => LV,
        54028 => LV,
        54056 => LV,
        54084 => LV,
        54112 => LV,
        54140 => LV,
        54168 => LV,
        54196 => LV,
        54224 => LV,
        54252 => LV,
        54280 => LV,
        54308 => LV,
        54336 => LV,
        54364 => LV,
        54392 => LV,
        54420 => LV,
        54448 => LV,
        54476 => LV,
        54504 => LV,
        54532 => LV,
        54560 => LV,
        54588 => LV,
        54616 => LV,
        54644 => LV,
        54672 => LV,
        54700 => LV,
        54728 => LV,
        54756 => LV,
        54784 => LV,
        54812 => LV,
        54840 => LV,
        54868 => LV,
        54896 => LV,
        54924 => LV,
        54952 => LV,
        54980 => LV,
        55008 => LV,
        55036 => LV,
        55064 => LV,
        55092 => LV,
        55120 => LV,
        55148 => LV,
        55176 => LV,
        9757 => E_Base,
        9977 => E_Base,
        127877 => E_Base,
        128110 => E_Base,
        128124 => E_Base,
        128170 => E_Base,
        128373 => E_Base,
        128378 => E_Base,
        128400 => E_Base,
        128675 => E_Base,
        128704 => E_Base,
        129318 => E_Base,
        129328 => E_Base,
        8205 => ZWJ,
        10084 => Glue_After_Zwj,
        128139 => Glue_After_Zwj,
        128488 => Glue_After_Zwj,
        ];
    public static function get(code:Int):GraphemeValuesEnum {
        if (code >= 1536 && code <= 1541) return Prepend;
        if (code >= 70082 && code <= 70083) return Prepend;
        if (code >= 0 && code <= 9) return Control;
        if (code >= 11 && code <= 12) return Control;
        if (code >= 14 && code <= 31) return Control;
        if (code >= 127 && code <= 159) return Control;
        if (code >= 8206 && code <= 8207) return Control;
        if (code >= 8234 && code <= 8238) return Control;
        if (code >= 8288 && code <= 8292) return Control;
        if (code >= 8294 && code <= 8303) return Control;
        if (code >= 55296 && code <= 57343) return Control;
        if (code >= 65520 && code <= 65528) return Control;
        if (code >= 65529 && code <= 65531) return Control;
        if (code >= 113824 && code <= 113827) return Control;
        if (code >= 119155 && code <= 119162) return Control;
        if (code >= 917506 && code <= 917535) return Control;
        if (code >= 917632 && code <= 917759) return Control;
        if (code >= 918000 && code <= 921599) return Control;
        if (code >= 768 && code <= 879) return Extend;
        if (code >= 1155 && code <= 1159) return Extend;
        if (code >= 1160 && code <= 1161) return Extend;
        if (code >= 1425 && code <= 1469) return Extend;
        if (code >= 1473 && code <= 1474) return Extend;
        if (code >= 1476 && code <= 1477) return Extend;
        if (code >= 1552 && code <= 1562) return Extend;
        if (code >= 1611 && code <= 1631) return Extend;
        if (code >= 1750 && code <= 1756) return Extend;
        if (code >= 1759 && code <= 1764) return Extend;
        if (code >= 1767 && code <= 1768) return Extend;
        if (code >= 1770 && code <= 1773) return Extend;
        if (code >= 1840 && code <= 1866) return Extend;
        if (code >= 1958 && code <= 1968) return Extend;
        if (code >= 2027 && code <= 2035) return Extend;
        if (code >= 2070 && code <= 2073) return Extend;
        if (code >= 2075 && code <= 2083) return Extend;
        if (code >= 2085 && code <= 2087) return Extend;
        if (code >= 2089 && code <= 2093) return Extend;
        if (code >= 2137 && code <= 2139) return Extend;
        if (code >= 2260 && code <= 2273) return Extend;
        if (code >= 2275 && code <= 2306) return Extend;
        if (code >= 2369 && code <= 2376) return Extend;
        if (code >= 2385 && code <= 2391) return Extend;
        if (code >= 2402 && code <= 2403) return Extend;
        if (code >= 2497 && code <= 2500) return Extend;
        if (code >= 2530 && code <= 2531) return Extend;
        if (code >= 2561 && code <= 2562) return Extend;
        if (code >= 2625 && code <= 2626) return Extend;
        if (code >= 2631 && code <= 2632) return Extend;
        if (code >= 2635 && code <= 2637) return Extend;
        if (code >= 2672 && code <= 2673) return Extend;
        if (code >= 2689 && code <= 2690) return Extend;
        if (code >= 2753 && code <= 2757) return Extend;
        if (code >= 2759 && code <= 2760) return Extend;
        if (code >= 2786 && code <= 2787) return Extend;
        if (code >= 2881 && code <= 2884) return Extend;
        if (code >= 2914 && code <= 2915) return Extend;
        if (code >= 3134 && code <= 3136) return Extend;
        if (code >= 3142 && code <= 3144) return Extend;
        if (code >= 3146 && code <= 3149) return Extend;
        if (code >= 3157 && code <= 3158) return Extend;
        if (code >= 3170 && code <= 3171) return Extend;
        if (code >= 3276 && code <= 3277) return Extend;
        if (code >= 3285 && code <= 3286) return Extend;
        if (code >= 3298 && code <= 3299) return Extend;
        if (code >= 3393 && code <= 3396) return Extend;
        if (code >= 3426 && code <= 3427) return Extend;
        if (code >= 3538 && code <= 3540) return Extend;
        if (code >= 3636 && code <= 3642) return Extend;
        if (code >= 3655 && code <= 3662) return Extend;
        if (code >= 3764 && code <= 3769) return Extend;
        if (code >= 3771 && code <= 3772) return Extend;
        if (code >= 3784 && code <= 3789) return Extend;
        if (code >= 3864 && code <= 3865) return Extend;
        if (code >= 3953 && code <= 3966) return Extend;
        if (code >= 3968 && code <= 3972) return Extend;
        if (code >= 3974 && code <= 3975) return Extend;
        if (code >= 3981 && code <= 3991) return Extend;
        if (code >= 3993 && code <= 4028) return Extend;
        if (code >= 4141 && code <= 4144) return Extend;
        if (code >= 4146 && code <= 4151) return Extend;
        if (code >= 4153 && code <= 4154) return Extend;
        if (code >= 4157 && code <= 4158) return Extend;
        if (code >= 4184 && code <= 4185) return Extend;
        if (code >= 4190 && code <= 4192) return Extend;
        if (code >= 4209 && code <= 4212) return Extend;
        if (code >= 4229 && code <= 4230) return Extend;
        if (code >= 4957 && code <= 4959) return Extend;
        if (code >= 5906 && code <= 5908) return Extend;
        if (code >= 5938 && code <= 5940) return Extend;
        if (code >= 5970 && code <= 5971) return Extend;
        if (code >= 6002 && code <= 6003) return Extend;
        if (code >= 6068 && code <= 6069) return Extend;
        if (code >= 6071 && code <= 6077) return Extend;
        if (code >= 6089 && code <= 6099) return Extend;
        if (code >= 6155 && code <= 6157) return Extend;
        if (code >= 6277 && code <= 6278) return Extend;
        if (code >= 6432 && code <= 6434) return Extend;
        if (code >= 6439 && code <= 6440) return Extend;
        if (code >= 6457 && code <= 6459) return Extend;
        if (code >= 6679 && code <= 6680) return Extend;
        if (code >= 6744 && code <= 6750) return Extend;
        if (code >= 6757 && code <= 6764) return Extend;
        if (code >= 6771 && code <= 6780) return Extend;
        if (code >= 6832 && code <= 6845) return Extend;
        if (code >= 6912 && code <= 6915) return Extend;
        if (code >= 6966 && code <= 6970) return Extend;
        if (code >= 7019 && code <= 7027) return Extend;
        if (code >= 7040 && code <= 7041) return Extend;
        if (code >= 7074 && code <= 7077) return Extend;
        if (code >= 7080 && code <= 7081) return Extend;
        if (code >= 7083 && code <= 7085) return Extend;
        if (code >= 7144 && code <= 7145) return Extend;
        if (code >= 7151 && code <= 7153) return Extend;
        if (code >= 7212 && code <= 7219) return Extend;
        if (code >= 7222 && code <= 7223) return Extend;
        if (code >= 7376 && code <= 7378) return Extend;
        if (code >= 7380 && code <= 7392) return Extend;
        if (code >= 7394 && code <= 7400) return Extend;
        if (code >= 7416 && code <= 7417) return Extend;
        if (code >= 7616 && code <= 7669) return Extend;
        if (code >= 7675 && code <= 7679) return Extend;
        if (code >= 8400 && code <= 8412) return Extend;
        if (code >= 8413 && code <= 8416) return Extend;
        if (code >= 8418 && code <= 8420) return Extend;
        if (code >= 8421 && code <= 8432) return Extend;
        if (code >= 11503 && code <= 11505) return Extend;
        if (code >= 11744 && code <= 11775) return Extend;
        if (code >= 12330 && code <= 12333) return Extend;
        if (code >= 12334 && code <= 12335) return Extend;
        if (code >= 12441 && code <= 12442) return Extend;
        if (code >= 42608 && code <= 42610) return Extend;
        if (code >= 42612 && code <= 42621) return Extend;
        if (code >= 42654 && code <= 42655) return Extend;
        if (code >= 42736 && code <= 42737) return Extend;
        if (code >= 43045 && code <= 43046) return Extend;
        if (code >= 43204 && code <= 43205) return Extend;
        if (code >= 43232 && code <= 43249) return Extend;
        if (code >= 43302 && code <= 43309) return Extend;
        if (code >= 43335 && code <= 43345) return Extend;
        if (code >= 43392 && code <= 43394) return Extend;
        if (code >= 43446 && code <= 43449) return Extend;
        if (code >= 43561 && code <= 43566) return Extend;
        if (code >= 43569 && code <= 43570) return Extend;
        if (code >= 43573 && code <= 43574) return Extend;
        if (code >= 43698 && code <= 43700) return Extend;
        if (code >= 43703 && code <= 43704) return Extend;
        if (code >= 43710 && code <= 43711) return Extend;
        if (code >= 43756 && code <= 43757) return Extend;
        if (code >= 65024 && code <= 65039) return Extend;
        if (code >= 65056 && code <= 65071) return Extend;
        if (code >= 65438 && code <= 65439) return Extend;
        if (code >= 66422 && code <= 66426) return Extend;
        if (code >= 68097 && code <= 68099) return Extend;
        if (code >= 68101 && code <= 68102) return Extend;
        if (code >= 68108 && code <= 68111) return Extend;
        if (code >= 68152 && code <= 68154) return Extend;
        if (code >= 68325 && code <= 68326) return Extend;
        if (code >= 69688 && code <= 69702) return Extend;
        if (code >= 69759 && code <= 69761) return Extend;
        if (code >= 69811 && code <= 69814) return Extend;
        if (code >= 69817 && code <= 69818) return Extend;
        if (code >= 69888 && code <= 69890) return Extend;
        if (code >= 69927 && code <= 69931) return Extend;
        if (code >= 69933 && code <= 69940) return Extend;
        if (code >= 70016 && code <= 70017) return Extend;
        if (code >= 70070 && code <= 70078) return Extend;
        if (code >= 70090 && code <= 70092) return Extend;
        if (code >= 70191 && code <= 70193) return Extend;
        if (code >= 70198 && code <= 70199) return Extend;
        if (code >= 70371 && code <= 70378) return Extend;
        if (code >= 70400 && code <= 70401) return Extend;
        if (code >= 70502 && code <= 70508) return Extend;
        if (code >= 70512 && code <= 70516) return Extend;
        if (code >= 70712 && code <= 70719) return Extend;
        if (code >= 70722 && code <= 70724) return Extend;
        if (code >= 70835 && code <= 70840) return Extend;
        if (code >= 70847 && code <= 70848) return Extend;
        if (code >= 70850 && code <= 70851) return Extend;
        if (code >= 71090 && code <= 71093) return Extend;
        if (code >= 71100 && code <= 71101) return Extend;
        if (code >= 71103 && code <= 71104) return Extend;
        if (code >= 71132 && code <= 71133) return Extend;
        if (code >= 71219 && code <= 71226) return Extend;
        if (code >= 71231 && code <= 71232) return Extend;
        if (code >= 71344 && code <= 71349) return Extend;
        if (code >= 71453 && code <= 71455) return Extend;
        if (code >= 71458 && code <= 71461) return Extend;
        if (code >= 71463 && code <= 71467) return Extend;
        if (code >= 72752 && code <= 72758) return Extend;
        if (code >= 72760 && code <= 72765) return Extend;
        if (code >= 72850 && code <= 72871) return Extend;
        if (code >= 72874 && code <= 72880) return Extend;
        if (code >= 72882 && code <= 72883) return Extend;
        if (code >= 72885 && code <= 72886) return Extend;
        if (code >= 92912 && code <= 92916) return Extend;
        if (code >= 92976 && code <= 92982) return Extend;
        if (code >= 94095 && code <= 94098) return Extend;
        if (code >= 113821 && code <= 113822) return Extend;
        if (code >= 119143 && code <= 119145) return Extend;
        if (code >= 119150 && code <= 119154) return Extend;
        if (code >= 119163 && code <= 119170) return Extend;
        if (code >= 119173 && code <= 119179) return Extend;
        if (code >= 119210 && code <= 119213) return Extend;
        if (code >= 119362 && code <= 119364) return Extend;
        if (code >= 121344 && code <= 121398) return Extend;
        if (code >= 121403 && code <= 121452) return Extend;
        if (code >= 121499 && code <= 121503) return Extend;
        if (code >= 121505 && code <= 121519) return Extend;
        if (code >= 122880 && code <= 122886) return Extend;
        if (code >= 122888 && code <= 122904) return Extend;
        if (code >= 122907 && code <= 122913) return Extend;
        if (code >= 122915 && code <= 122916) return Extend;
        if (code >= 122918 && code <= 122922) return Extend;
        if (code >= 125136 && code <= 125142) return Extend;
        if (code >= 125252 && code <= 125258) return Extend;
        if (code >= 917536 && code <= 917631) return Extend;
        if (code >= 917760 && code <= 917999) return Extend;
        if (code >= 127462 && code <= 127487) return Regional_Indicator;
        if (code >= 2366 && code <= 2368) return SpacingMark;
        if (code >= 2377 && code <= 2380) return SpacingMark;
        if (code >= 2382 && code <= 2383) return SpacingMark;
        if (code >= 2434 && code <= 2435) return SpacingMark;
        if (code >= 2495 && code <= 2496) return SpacingMark;
        if (code >= 2503 && code <= 2504) return SpacingMark;
        if (code >= 2507 && code <= 2508) return SpacingMark;
        if (code >= 2622 && code <= 2624) return SpacingMark;
        if (code >= 2750 && code <= 2752) return SpacingMark;
        if (code >= 2763 && code <= 2764) return SpacingMark;
        if (code >= 2818 && code <= 2819) return SpacingMark;
        if (code >= 2887 && code <= 2888) return SpacingMark;
        if (code >= 2891 && code <= 2892) return SpacingMark;
        if (code >= 3009 && code <= 3010) return SpacingMark;
        if (code >= 3014 && code <= 3016) return SpacingMark;
        if (code >= 3018 && code <= 3020) return SpacingMark;
        if (code >= 3073 && code <= 3075) return SpacingMark;
        if (code >= 3137 && code <= 3140) return SpacingMark;
        if (code >= 3202 && code <= 3203) return SpacingMark;
        if (code >= 3264 && code <= 3265) return SpacingMark;
        if (code >= 3267 && code <= 3268) return SpacingMark;
        if (code >= 3271 && code <= 3272) return SpacingMark;
        if (code >= 3274 && code <= 3275) return SpacingMark;
        if (code >= 3330 && code <= 3331) return SpacingMark;
        if (code >= 3391 && code <= 3392) return SpacingMark;
        if (code >= 3398 && code <= 3400) return SpacingMark;
        if (code >= 3402 && code <= 3404) return SpacingMark;
        if (code >= 3458 && code <= 3459) return SpacingMark;
        if (code >= 3536 && code <= 3537) return SpacingMark;
        if (code >= 3544 && code <= 3550) return SpacingMark;
        if (code >= 3570 && code <= 3571) return SpacingMark;
        if (code >= 3902 && code <= 3903) return SpacingMark;
        if (code >= 4155 && code <= 4156) return SpacingMark;
        if (code >= 4182 && code <= 4183) return SpacingMark;
        if (code >= 6078 && code <= 6085) return SpacingMark;
        if (code >= 6087 && code <= 6088) return SpacingMark;
        if (code >= 6435 && code <= 6438) return SpacingMark;
        if (code >= 6441 && code <= 6443) return SpacingMark;
        if (code >= 6448 && code <= 6449) return SpacingMark;
        if (code >= 6451 && code <= 6456) return SpacingMark;
        if (code >= 6681 && code <= 6682) return SpacingMark;
        if (code >= 6765 && code <= 6770) return SpacingMark;
        if (code >= 6973 && code <= 6977) return SpacingMark;
        if (code >= 6979 && code <= 6980) return SpacingMark;
        if (code >= 7078 && code <= 7079) return SpacingMark;
        if (code >= 7146 && code <= 7148) return SpacingMark;
        if (code >= 7154 && code <= 7155) return SpacingMark;
        if (code >= 7204 && code <= 7211) return SpacingMark;
        if (code >= 7220 && code <= 7221) return SpacingMark;
        if (code >= 7410 && code <= 7411) return SpacingMark;
        if (code >= 43043 && code <= 43044) return SpacingMark;
        if (code >= 43136 && code <= 43137) return SpacingMark;
        if (code >= 43188 && code <= 43203) return SpacingMark;
        if (code >= 43346 && code <= 43347) return SpacingMark;
        if (code >= 43444 && code <= 43445) return SpacingMark;
        if (code >= 43450 && code <= 43451) return SpacingMark;
        if (code >= 43453 && code <= 43456) return SpacingMark;
        if (code >= 43567 && code <= 43568) return SpacingMark;
        if (code >= 43571 && code <= 43572) return SpacingMark;
        if (code >= 43758 && code <= 43759) return SpacingMark;
        if (code >= 44003 && code <= 44004) return SpacingMark;
        if (code >= 44006 && code <= 44007) return SpacingMark;
        if (code >= 44009 && code <= 44010) return SpacingMark;
        if (code >= 69808 && code <= 69810) return SpacingMark;
        if (code >= 69815 && code <= 69816) return SpacingMark;
        if (code >= 70067 && code <= 70069) return SpacingMark;
        if (code >= 70079 && code <= 70080) return SpacingMark;
        if (code >= 70188 && code <= 70190) return SpacingMark;
        if (code >= 70194 && code <= 70195) return SpacingMark;
        if (code >= 70368 && code <= 70370) return SpacingMark;
        if (code >= 70402 && code <= 70403) return SpacingMark;
        if (code >= 70465 && code <= 70468) return SpacingMark;
        if (code >= 70471 && code <= 70472) return SpacingMark;
        if (code >= 70475 && code <= 70477) return SpacingMark;
        if (code >= 70498 && code <= 70499) return SpacingMark;
        if (code >= 70709 && code <= 70711) return SpacingMark;
        if (code >= 70720 && code <= 70721) return SpacingMark;
        if (code >= 70833 && code <= 70834) return SpacingMark;
        if (code >= 70843 && code <= 70844) return SpacingMark;
        if (code >= 71088 && code <= 71089) return SpacingMark;
        if (code >= 71096 && code <= 71099) return SpacingMark;
        if (code >= 71216 && code <= 71218) return SpacingMark;
        if (code >= 71227 && code <= 71228) return SpacingMark;
        if (code >= 71342 && code <= 71343) return SpacingMark;
        if (code >= 71456 && code <= 71457) return SpacingMark;
        if (code >= 94033 && code <= 94078) return SpacingMark;
        if (code >= 4352 && code <= 4447) return L;
        if (code >= 43360 && code <= 43388) return L;
        if (code >= 4448 && code <= 4519) return V;
        if (code >= 55216 && code <= 55238) return V;
        if (code >= 4520 && code <= 4607) return T;
        if (code >= 55243 && code <= 55291) return T;
        if (code >= 44033 && code <= 44059) return LVT;
        if (code >= 44061 && code <= 44087) return LVT;
        if (code >= 44089 && code <= 44115) return LVT;
        if (code >= 44117 && code <= 44143) return LVT;
        if (code >= 44145 && code <= 44171) return LVT;
        if (code >= 44173 && code <= 44199) return LVT;
        if (code >= 44201 && code <= 44227) return LVT;
        if (code >= 44229 && code <= 44255) return LVT;
        if (code >= 44257 && code <= 44283) return LVT;
        if (code >= 44285 && code <= 44311) return LVT;
        if (code >= 44313 && code <= 44339) return LVT;
        if (code >= 44341 && code <= 44367) return LVT;
        if (code >= 44369 && code <= 44395) return LVT;
        if (code >= 44397 && code <= 44423) return LVT;
        if (code >= 44425 && code <= 44451) return LVT;
        if (code >= 44453 && code <= 44479) return LVT;
        if (code >= 44481 && code <= 44507) return LVT;
        if (code >= 44509 && code <= 44535) return LVT;
        if (code >= 44537 && code <= 44563) return LVT;
        if (code >= 44565 && code <= 44591) return LVT;
        if (code >= 44593 && code <= 44619) return LVT;
        if (code >= 44621 && code <= 44647) return LVT;
        if (code >= 44649 && code <= 44675) return LVT;
        if (code >= 44677 && code <= 44703) return LVT;
        if (code >= 44705 && code <= 44731) return LVT;
        if (code >= 44733 && code <= 44759) return LVT;
        if (code >= 44761 && code <= 44787) return LVT;
        if (code >= 44789 && code <= 44815) return LVT;
        if (code >= 44817 && code <= 44843) return LVT;
        if (code >= 44845 && code <= 44871) return LVT;
        if (code >= 44873 && code <= 44899) return LVT;
        if (code >= 44901 && code <= 44927) return LVT;
        if (code >= 44929 && code <= 44955) return LVT;
        if (code >= 44957 && code <= 44983) return LVT;
        if (code >= 44985 && code <= 45011) return LVT;
        if (code >= 45013 && code <= 45039) return LVT;
        if (code >= 45041 && code <= 45067) return LVT;
        if (code >= 45069 && code <= 45095) return LVT;
        if (code >= 45097 && code <= 45123) return LVT;
        if (code >= 45125 && code <= 45151) return LVT;
        if (code >= 45153 && code <= 45179) return LVT;
        if (code >= 45181 && code <= 45207) return LVT;
        if (code >= 45209 && code <= 45235) return LVT;
        if (code >= 45237 && code <= 45263) return LVT;
        if (code >= 45265 && code <= 45291) return LVT;
        if (code >= 45293 && code <= 45319) return LVT;
        if (code >= 45321 && code <= 45347) return LVT;
        if (code >= 45349 && code <= 45375) return LVT;
        if (code >= 45377 && code <= 45403) return LVT;
        if (code >= 45405 && code <= 45431) return LVT;
        if (code >= 45433 && code <= 45459) return LVT;
        if (code >= 45461 && code <= 45487) return LVT;
        if (code >= 45489 && code <= 45515) return LVT;
        if (code >= 45517 && code <= 45543) return LVT;
        if (code >= 45545 && code <= 45571) return LVT;
        if (code >= 45573 && code <= 45599) return LVT;
        if (code >= 45601 && code <= 45627) return LVT;
        if (code >= 45629 && code <= 45655) return LVT;
        if (code >= 45657 && code <= 45683) return LVT;
        if (code >= 45685 && code <= 45711) return LVT;
        if (code >= 45713 && code <= 45739) return LVT;
        if (code >= 45741 && code <= 45767) return LVT;
        if (code >= 45769 && code <= 45795) return LVT;
        if (code >= 45797 && code <= 45823) return LVT;
        if (code >= 45825 && code <= 45851) return LVT;
        if (code >= 45853 && code <= 45879) return LVT;
        if (code >= 45881 && code <= 45907) return LVT;
        if (code >= 45909 && code <= 45935) return LVT;
        if (code >= 45937 && code <= 45963) return LVT;
        if (code >= 45965 && code <= 45991) return LVT;
        if (code >= 45993 && code <= 46019) return LVT;
        if (code >= 46021 && code <= 46047) return LVT;
        if (code >= 46049 && code <= 46075) return LVT;
        if (code >= 46077 && code <= 46103) return LVT;
        if (code >= 46105 && code <= 46131) return LVT;
        if (code >= 46133 && code <= 46159) return LVT;
        if (code >= 46161 && code <= 46187) return LVT;
        if (code >= 46189 && code <= 46215) return LVT;
        if (code >= 46217 && code <= 46243) return LVT;
        if (code >= 46245 && code <= 46271) return LVT;
        if (code >= 46273 && code <= 46299) return LVT;
        if (code >= 46301 && code <= 46327) return LVT;
        if (code >= 46329 && code <= 46355) return LVT;
        if (code >= 46357 && code <= 46383) return LVT;
        if (code >= 46385 && code <= 46411) return LVT;
        if (code >= 46413 && code <= 46439) return LVT;
        if (code >= 46441 && code <= 46467) return LVT;
        if (code >= 46469 && code <= 46495) return LVT;
        if (code >= 46497 && code <= 46523) return LVT;
        if (code >= 46525 && code <= 46551) return LVT;
        if (code >= 46553 && code <= 46579) return LVT;
        if (code >= 46581 && code <= 46607) return LVT;
        if (code >= 46609 && code <= 46635) return LVT;
        if (code >= 46637 && code <= 46663) return LVT;
        if (code >= 46665 && code <= 46691) return LVT;
        if (code >= 46693 && code <= 46719) return LVT;
        if (code >= 46721 && code <= 46747) return LVT;
        if (code >= 46749 && code <= 46775) return LVT;
        if (code >= 46777 && code <= 46803) return LVT;
        if (code >= 46805 && code <= 46831) return LVT;
        if (code >= 46833 && code <= 46859) return LVT;
        if (code >= 46861 && code <= 46887) return LVT;
        if (code >= 46889 && code <= 46915) return LVT;
        if (code >= 46917 && code <= 46943) return LVT;
        if (code >= 46945 && code <= 46971) return LVT;
        if (code >= 46973 && code <= 46999) return LVT;
        if (code >= 47001 && code <= 47027) return LVT;
        if (code >= 47029 && code <= 47055) return LVT;
        if (code >= 47057 && code <= 47083) return LVT;
        if (code >= 47085 && code <= 47111) return LVT;
        if (code >= 47113 && code <= 47139) return LVT;
        if (code >= 47141 && code <= 47167) return LVT;
        if (code >= 47169 && code <= 47195) return LVT;
        if (code >= 47197 && code <= 47223) return LVT;
        if (code >= 47225 && code <= 47251) return LVT;
        if (code >= 47253 && code <= 47279) return LVT;
        if (code >= 47281 && code <= 47307) return LVT;
        if (code >= 47309 && code <= 47335) return LVT;
        if (code >= 47337 && code <= 47363) return LVT;
        if (code >= 47365 && code <= 47391) return LVT;
        if (code >= 47393 && code <= 47419) return LVT;
        if (code >= 47421 && code <= 47447) return LVT;
        if (code >= 47449 && code <= 47475) return LVT;
        if (code >= 47477 && code <= 47503) return LVT;
        if (code >= 47505 && code <= 47531) return LVT;
        if (code >= 47533 && code <= 47559) return LVT;
        if (code >= 47561 && code <= 47587) return LVT;
        if (code >= 47589 && code <= 47615) return LVT;
        if (code >= 47617 && code <= 47643) return LVT;
        if (code >= 47645 && code <= 47671) return LVT;
        if (code >= 47673 && code <= 47699) return LVT;
        if (code >= 47701 && code <= 47727) return LVT;
        if (code >= 47729 && code <= 47755) return LVT;
        if (code >= 47757 && code <= 47783) return LVT;
        if (code >= 47785 && code <= 47811) return LVT;
        if (code >= 47813 && code <= 47839) return LVT;
        if (code >= 47841 && code <= 47867) return LVT;
        if (code >= 47869 && code <= 47895) return LVT;
        if (code >= 47897 && code <= 47923) return LVT;
        if (code >= 47925 && code <= 47951) return LVT;
        if (code >= 47953 && code <= 47979) return LVT;
        if (code >= 47981 && code <= 48007) return LVT;
        if (code >= 48009 && code <= 48035) return LVT;
        if (code >= 48037 && code <= 48063) return LVT;
        if (code >= 48065 && code <= 48091) return LVT;
        if (code >= 48093 && code <= 48119) return LVT;
        if (code >= 48121 && code <= 48147) return LVT;
        if (code >= 48149 && code <= 48175) return LVT;
        if (code >= 48177 && code <= 48203) return LVT;
        if (code >= 48205 && code <= 48231) return LVT;
        if (code >= 48233 && code <= 48259) return LVT;
        if (code >= 48261 && code <= 48287) return LVT;
        if (code >= 48289 && code <= 48315) return LVT;
        if (code >= 48317 && code <= 48343) return LVT;
        if (code >= 48345 && code <= 48371) return LVT;
        if (code >= 48373 && code <= 48399) return LVT;
        if (code >= 48401 && code <= 48427) return LVT;
        if (code >= 48429 && code <= 48455) return LVT;
        if (code >= 48457 && code <= 48483) return LVT;
        if (code >= 48485 && code <= 48511) return LVT;
        if (code >= 48513 && code <= 48539) return LVT;
        if (code >= 48541 && code <= 48567) return LVT;
        if (code >= 48569 && code <= 48595) return LVT;
        if (code >= 48597 && code <= 48623) return LVT;
        if (code >= 48625 && code <= 48651) return LVT;
        if (code >= 48653 && code <= 48679) return LVT;
        if (code >= 48681 && code <= 48707) return LVT;
        if (code >= 48709 && code <= 48735) return LVT;
        if (code >= 48737 && code <= 48763) return LVT;
        if (code >= 48765 && code <= 48791) return LVT;
        if (code >= 48793 && code <= 48819) return LVT;
        if (code >= 48821 && code <= 48847) return LVT;
        if (code >= 48849 && code <= 48875) return LVT;
        if (code >= 48877 && code <= 48903) return LVT;
        if (code >= 48905 && code <= 48931) return LVT;
        if (code >= 48933 && code <= 48959) return LVT;
        if (code >= 48961 && code <= 48987) return LVT;
        if (code >= 48989 && code <= 49015) return LVT;
        if (code >= 49017 && code <= 49043) return LVT;
        if (code >= 49045 && code <= 49071) return LVT;
        if (code >= 49073 && code <= 49099) return LVT;
        if (code >= 49101 && code <= 49127) return LVT;
        if (code >= 49129 && code <= 49155) return LVT;
        if (code >= 49157 && code <= 49183) return LVT;
        if (code >= 49185 && code <= 49211) return LVT;
        if (code >= 49213 && code <= 49239) return LVT;
        if (code >= 49241 && code <= 49267) return LVT;
        if (code >= 49269 && code <= 49295) return LVT;
        if (code >= 49297 && code <= 49323) return LVT;
        if (code >= 49325 && code <= 49351) return LVT;
        if (code >= 49353 && code <= 49379) return LVT;
        if (code >= 49381 && code <= 49407) return LVT;
        if (code >= 49409 && code <= 49435) return LVT;
        if (code >= 49437 && code <= 49463) return LVT;
        if (code >= 49465 && code <= 49491) return LVT;
        if (code >= 49493 && code <= 49519) return LVT;
        if (code >= 49521 && code <= 49547) return LVT;
        if (code >= 49549 && code <= 49575) return LVT;
        if (code >= 49577 && code <= 49603) return LVT;
        if (code >= 49605 && code <= 49631) return LVT;
        if (code >= 49633 && code <= 49659) return LVT;
        if (code >= 49661 && code <= 49687) return LVT;
        if (code >= 49689 && code <= 49715) return LVT;
        if (code >= 49717 && code <= 49743) return LVT;
        if (code >= 49745 && code <= 49771) return LVT;
        if (code >= 49773 && code <= 49799) return LVT;
        if (code >= 49801 && code <= 49827) return LVT;
        if (code >= 49829 && code <= 49855) return LVT;
        if (code >= 49857 && code <= 49883) return LVT;
        if (code >= 49885 && code <= 49911) return LVT;
        if (code >= 49913 && code <= 49939) return LVT;
        if (code >= 49941 && code <= 49967) return LVT;
        if (code >= 49969 && code <= 49995) return LVT;
        if (code >= 49997 && code <= 50023) return LVT;
        if (code >= 50025 && code <= 50051) return LVT;
        if (code >= 50053 && code <= 50079) return LVT;
        if (code >= 50081 && code <= 50107) return LVT;
        if (code >= 50109 && code <= 50135) return LVT;
        if (code >= 50137 && code <= 50163) return LVT;
        if (code >= 50165 && code <= 50191) return LVT;
        if (code >= 50193 && code <= 50219) return LVT;
        if (code >= 50221 && code <= 50247) return LVT;
        if (code >= 50249 && code <= 50275) return LVT;
        if (code >= 50277 && code <= 50303) return LVT;
        if (code >= 50305 && code <= 50331) return LVT;
        if (code >= 50333 && code <= 50359) return LVT;
        if (code >= 50361 && code <= 50387) return LVT;
        if (code >= 50389 && code <= 50415) return LVT;
        if (code >= 50417 && code <= 50443) return LVT;
        if (code >= 50445 && code <= 50471) return LVT;
        if (code >= 50473 && code <= 50499) return LVT;
        if (code >= 50501 && code <= 50527) return LVT;
        if (code >= 50529 && code <= 50555) return LVT;
        if (code >= 50557 && code <= 50583) return LVT;
        if (code >= 50585 && code <= 50611) return LVT;
        if (code >= 50613 && code <= 50639) return LVT;
        if (code >= 50641 && code <= 50667) return LVT;
        if (code >= 50669 && code <= 50695) return LVT;
        if (code >= 50697 && code <= 50723) return LVT;
        if (code >= 50725 && code <= 50751) return LVT;
        if (code >= 50753 && code <= 50779) return LVT;
        if (code >= 50781 && code <= 50807) return LVT;
        if (code >= 50809 && code <= 50835) return LVT;
        if (code >= 50837 && code <= 50863) return LVT;
        if (code >= 50865 && code <= 50891) return LVT;
        if (code >= 50893 && code <= 50919) return LVT;
        if (code >= 50921 && code <= 50947) return LVT;
        if (code >= 50949 && code <= 50975) return LVT;
        if (code >= 50977 && code <= 51003) return LVT;
        if (code >= 51005 && code <= 51031) return LVT;
        if (code >= 51033 && code <= 51059) return LVT;
        if (code >= 51061 && code <= 51087) return LVT;
        if (code >= 51089 && code <= 51115) return LVT;
        if (code >= 51117 && code <= 51143) return LVT;
        if (code >= 51145 && code <= 51171) return LVT;
        if (code >= 51173 && code <= 51199) return LVT;
        if (code >= 51201 && code <= 51227) return LVT;
        if (code >= 51229 && code <= 51255) return LVT;
        if (code >= 51257 && code <= 51283) return LVT;
        if (code >= 51285 && code <= 51311) return LVT;
        if (code >= 51313 && code <= 51339) return LVT;
        if (code >= 51341 && code <= 51367) return LVT;
        if (code >= 51369 && code <= 51395) return LVT;
        if (code >= 51397 && code <= 51423) return LVT;
        if (code >= 51425 && code <= 51451) return LVT;
        if (code >= 51453 && code <= 51479) return LVT;
        if (code >= 51481 && code <= 51507) return LVT;
        if (code >= 51509 && code <= 51535) return LVT;
        if (code >= 51537 && code <= 51563) return LVT;
        if (code >= 51565 && code <= 51591) return LVT;
        if (code >= 51593 && code <= 51619) return LVT;
        if (code >= 51621 && code <= 51647) return LVT;
        if (code >= 51649 && code <= 51675) return LVT;
        if (code >= 51677 && code <= 51703) return LVT;
        if (code >= 51705 && code <= 51731) return LVT;
        if (code >= 51733 && code <= 51759) return LVT;
        if (code >= 51761 && code <= 51787) return LVT;
        if (code >= 51789 && code <= 51815) return LVT;
        if (code >= 51817 && code <= 51843) return LVT;
        if (code >= 51845 && code <= 51871) return LVT;
        if (code >= 51873 && code <= 51899) return LVT;
        if (code >= 51901 && code <= 51927) return LVT;
        if (code >= 51929 && code <= 51955) return LVT;
        if (code >= 51957 && code <= 51983) return LVT;
        if (code >= 51985 && code <= 52011) return LVT;
        if (code >= 52013 && code <= 52039) return LVT;
        if (code >= 52041 && code <= 52067) return LVT;
        if (code >= 52069 && code <= 52095) return LVT;
        if (code >= 52097 && code <= 52123) return LVT;
        if (code >= 52125 && code <= 52151) return LVT;
        if (code >= 52153 && code <= 52179) return LVT;
        if (code >= 52181 && code <= 52207) return LVT;
        if (code >= 52209 && code <= 52235) return LVT;
        if (code >= 52237 && code <= 52263) return LVT;
        if (code >= 52265 && code <= 52291) return LVT;
        if (code >= 52293 && code <= 52319) return LVT;
        if (code >= 52321 && code <= 52347) return LVT;
        if (code >= 52349 && code <= 52375) return LVT;
        if (code >= 52377 && code <= 52403) return LVT;
        if (code >= 52405 && code <= 52431) return LVT;
        if (code >= 52433 && code <= 52459) return LVT;
        if (code >= 52461 && code <= 52487) return LVT;
        if (code >= 52489 && code <= 52515) return LVT;
        if (code >= 52517 && code <= 52543) return LVT;
        if (code >= 52545 && code <= 52571) return LVT;
        if (code >= 52573 && code <= 52599) return LVT;
        if (code >= 52601 && code <= 52627) return LVT;
        if (code >= 52629 && code <= 52655) return LVT;
        if (code >= 52657 && code <= 52683) return LVT;
        if (code >= 52685 && code <= 52711) return LVT;
        if (code >= 52713 && code <= 52739) return LVT;
        if (code >= 52741 && code <= 52767) return LVT;
        if (code >= 52769 && code <= 52795) return LVT;
        if (code >= 52797 && code <= 52823) return LVT;
        if (code >= 52825 && code <= 52851) return LVT;
        if (code >= 52853 && code <= 52879) return LVT;
        if (code >= 52881 && code <= 52907) return LVT;
        if (code >= 52909 && code <= 52935) return LVT;
        if (code >= 52937 && code <= 52963) return LVT;
        if (code >= 52965 && code <= 52991) return LVT;
        if (code >= 52993 && code <= 53019) return LVT;
        if (code >= 53021 && code <= 53047) return LVT;
        if (code >= 53049 && code <= 53075) return LVT;
        if (code >= 53077 && code <= 53103) return LVT;
        if (code >= 53105 && code <= 53131) return LVT;
        if (code >= 53133 && code <= 53159) return LVT;
        if (code >= 53161 && code <= 53187) return LVT;
        if (code >= 53189 && code <= 53215) return LVT;
        if (code >= 53217 && code <= 53243) return LVT;
        if (code >= 53245 && code <= 53271) return LVT;
        if (code >= 53273 && code <= 53299) return LVT;
        if (code >= 53301 && code <= 53327) return LVT;
        if (code >= 53329 && code <= 53355) return LVT;
        if (code >= 53357 && code <= 53383) return LVT;
        if (code >= 53385 && code <= 53411) return LVT;
        if (code >= 53413 && code <= 53439) return LVT;
        if (code >= 53441 && code <= 53467) return LVT;
        if (code >= 53469 && code <= 53495) return LVT;
        if (code >= 53497 && code <= 53523) return LVT;
        if (code >= 53525 && code <= 53551) return LVT;
        if (code >= 53553 && code <= 53579) return LVT;
        if (code >= 53581 && code <= 53607) return LVT;
        if (code >= 53609 && code <= 53635) return LVT;
        if (code >= 53637 && code <= 53663) return LVT;
        if (code >= 53665 && code <= 53691) return LVT;
        if (code >= 53693 && code <= 53719) return LVT;
        if (code >= 53721 && code <= 53747) return LVT;
        if (code >= 53749 && code <= 53775) return LVT;
        if (code >= 53777 && code <= 53803) return LVT;
        if (code >= 53805 && code <= 53831) return LVT;
        if (code >= 53833 && code <= 53859) return LVT;
        if (code >= 53861 && code <= 53887) return LVT;
        if (code >= 53889 && code <= 53915) return LVT;
        if (code >= 53917 && code <= 53943) return LVT;
        if (code >= 53945 && code <= 53971) return LVT;
        if (code >= 53973 && code <= 53999) return LVT;
        if (code >= 54001 && code <= 54027) return LVT;
        if (code >= 54029 && code <= 54055) return LVT;
        if (code >= 54057 && code <= 54083) return LVT;
        if (code >= 54085 && code <= 54111) return LVT;
        if (code >= 54113 && code <= 54139) return LVT;
        if (code >= 54141 && code <= 54167) return LVT;
        if (code >= 54169 && code <= 54195) return LVT;
        if (code >= 54197 && code <= 54223) return LVT;
        if (code >= 54225 && code <= 54251) return LVT;
        if (code >= 54253 && code <= 54279) return LVT;
        if (code >= 54281 && code <= 54307) return LVT;
        if (code >= 54309 && code <= 54335) return LVT;
        if (code >= 54337 && code <= 54363) return LVT;
        if (code >= 54365 && code <= 54391) return LVT;
        if (code >= 54393 && code <= 54419) return LVT;
        if (code >= 54421 && code <= 54447) return LVT;
        if (code >= 54449 && code <= 54475) return LVT;
        if (code >= 54477 && code <= 54503) return LVT;
        if (code >= 54505 && code <= 54531) return LVT;
        if (code >= 54533 && code <= 54559) return LVT;
        if (code >= 54561 && code <= 54587) return LVT;
        if (code >= 54589 && code <= 54615) return LVT;
        if (code >= 54617 && code <= 54643) return LVT;
        if (code >= 54645 && code <= 54671) return LVT;
        if (code >= 54673 && code <= 54699) return LVT;
        if (code >= 54701 && code <= 54727) return LVT;
        if (code >= 54729 && code <= 54755) return LVT;
        if (code >= 54757 && code <= 54783) return LVT;
        if (code >= 54785 && code <= 54811) return LVT;
        if (code >= 54813 && code <= 54839) return LVT;
        if (code >= 54841 && code <= 54867) return LVT;
        if (code >= 54869 && code <= 54895) return LVT;
        if (code >= 54897 && code <= 54923) return LVT;
        if (code >= 54925 && code <= 54951) return LVT;
        if (code >= 54953 && code <= 54979) return LVT;
        if (code >= 54981 && code <= 55007) return LVT;
        if (code >= 55009 && code <= 55035) return LVT;
        if (code >= 55037 && code <= 55063) return LVT;
        if (code >= 55065 && code <= 55091) return LVT;
        if (code >= 55093 && code <= 55119) return LVT;
        if (code >= 55121 && code <= 55147) return LVT;
        if (code >= 55149 && code <= 55175) return LVT;
        if (code >= 55177 && code <= 55203) return LVT;
        if (code >= 9994 && code <= 9997) return E_Base;
        if (code >= 127939 && code <= 127940) return E_Base;
        if (code >= 127946 && code <= 127947) return E_Base;
        if (code >= 128066 && code <= 128067) return E_Base;
        if (code >= 128070 && code <= 128080) return E_Base;
        if (code >= 128112 && code <= 128120) return E_Base;
        if (code >= 128129 && code <= 128131) return E_Base;
        if (code >= 128133 && code <= 128135) return E_Base;
        if (code >= 128405 && code <= 128406) return E_Base;
        if (code >= 128581 && code <= 128583) return E_Base;
        if (code >= 128587 && code <= 128591) return E_Base;
        if (code >= 128692 && code <= 128694) return E_Base;
        if (code >= 129304 && code <= 129310) return E_Base;
        if (code >= 129331 && code <= 129337) return E_Base;
        if (code >= 129340 && code <= 129342) return E_Base;
        if (code >= 127995 && code <= 127999) return E_Modifier;
        if (code >= 128102 && code <= 128105) return E_Base_GAZ;
        var res = m.get(code);
        return res != null ? res : Other;
    }
}
enum GraphemeValuesEnum {
    L;
    Other;
    SpacingMark;
    T;
    E_Base;
    Control;
    LVT;
    E_Base_GAZ;
    Prepend;
    LV;
    ZWJ;
    V;
    LF;
    E_Modifier;
    Regional_Indicator;
    CR;
    Extend;
    Glue_After_Zwj;
}
