package unicode.tr29.internal;
//Autogenerated, do not edit
class SentenceValues {
        static var m = [
        13 => CR,
        10 => LF,
        1471 => Extend,
        1479 => Extend,
        1648 => Extend,
        1809 => Extend,
        2307 => Extend,
        2362 => Extend,
        2363 => Extend,
        2364 => Extend,
        2381 => Extend,
        2433 => Extend,
        2492 => Extend,
        2509 => Extend,
        2519 => Extend,
        2563 => Extend,
        2620 => Extend,
        2641 => Extend,
        2677 => Extend,
        2691 => Extend,
        2748 => Extend,
        2761 => Extend,
        2765 => Extend,
        2817 => Extend,
        2876 => Extend,
        2878 => Extend,
        2879 => Extend,
        2880 => Extend,
        2893 => Extend,
        2902 => Extend,
        2903 => Extend,
        2946 => Extend,
        3008 => Extend,
        3021 => Extend,
        3031 => Extend,
        3072 => Extend,
        3201 => Extend,
        3260 => Extend,
        3262 => Extend,
        3263 => Extend,
        3270 => Extend,
        3329 => Extend,
        3405 => Extend,
        3415 => Extend,
        3530 => Extend,
        3542 => Extend,
        3633 => Extend,
        3761 => Extend,
        3893 => Extend,
        3895 => Extend,
        3897 => Extend,
        3967 => Extend,
        4038 => Extend,
        4145 => Extend,
        4152 => Extend,
        4226 => Extend,
        4237 => Extend,
        4239 => Extend,
        4253 => Extend,
        6070 => Extend,
        6086 => Extend,
        6109 => Extend,
        6313 => Extend,
        6450 => Extend,
        6683 => Extend,
        6741 => Extend,
        6742 => Extend,
        6743 => Extend,
        6752 => Extend,
        6753 => Extend,
        6754 => Extend,
        6783 => Extend,
        6846 => Extend,
        6916 => Extend,
        6964 => Extend,
        6965 => Extend,
        6971 => Extend,
        6972 => Extend,
        6978 => Extend,
        7042 => Extend,
        7073 => Extend,
        7082 => Extend,
        7142 => Extend,
        7143 => Extend,
        7149 => Extend,
        7150 => Extend,
        7393 => Extend,
        7405 => Extend,
        7412 => Extend,
        8417 => Extend,
        11647 => Extend,
        42607 => Extend,
        43010 => Extend,
        43014 => Extend,
        43019 => Extend,
        43047 => Extend,
        43395 => Extend,
        43443 => Extend,
        43452 => Extend,
        43493 => Extend,
        43587 => Extend,
        43596 => Extend,
        43597 => Extend,
        43643 => Extend,
        43644 => Extend,
        43645 => Extend,
        43696 => Extend,
        43713 => Extend,
        43755 => Extend,
        43765 => Extend,
        43766 => Extend,
        44005 => Extend,
        44008 => Extend,
        44012 => Extend,
        44013 => Extend,
        64286 => Extend,
        66045 => Extend,
        66272 => Extend,
        68159 => Extend,
        69632 => Extend,
        69633 => Extend,
        69634 => Extend,
        69762 => Extend,
        69932 => Extend,
        70003 => Extend,
        70018 => Extend,
        70196 => Extend,
        70197 => Extend,
        70206 => Extend,
        70367 => Extend,
        70460 => Extend,
        70464 => Extend,
        70487 => Extend,
        70725 => Extend,
        70726 => Extend,
        70841 => Extend,
        70842 => Extend,
        70849 => Extend,
        71102 => Extend,
        71229 => Extend,
        71230 => Extend,
        71339 => Extend,
        71340 => Extend,
        71341 => Extend,
        71350 => Extend,
        71351 => Extend,
        71462 => Extend,
        72751 => Extend,
        72766 => Extend,
        72767 => Extend,
        72873 => Extend,
        72881 => Extend,
        72884 => Extend,
        121461 => Extend,
        121476 => Extend,
        133 => Sep,
        8232 => Sep,
        8233 => Sep,
        173 => Format,
        1564 => Format,
        1757 => Format,
        1807 => Format,
        2274 => Format,
        6158 => Format,
        8203 => Format,
        65279 => Format,
        69821 => Format,
        917505 => Format,
        9 => Sp,
        32 => Sp,
        160 => Sp,
        5760 => Sp,
        8239 => Sp,
        8287 => Sp,
        12288 => Sp,
        170 => Lower,
        181 => Lower,
        186 => Lower,
        257 => Lower,
        259 => Lower,
        261 => Lower,
        263 => Lower,
        265 => Lower,
        267 => Lower,
        269 => Lower,
        271 => Lower,
        273 => Lower,
        275 => Lower,
        277 => Lower,
        279 => Lower,
        281 => Lower,
        283 => Lower,
        285 => Lower,
        287 => Lower,
        289 => Lower,
        291 => Lower,
        293 => Lower,
        295 => Lower,
        297 => Lower,
        299 => Lower,
        301 => Lower,
        303 => Lower,
        305 => Lower,
        307 => Lower,
        309 => Lower,
        314 => Lower,
        316 => Lower,
        318 => Lower,
        320 => Lower,
        322 => Lower,
        324 => Lower,
        326 => Lower,
        331 => Lower,
        333 => Lower,
        335 => Lower,
        337 => Lower,
        339 => Lower,
        341 => Lower,
        343 => Lower,
        345 => Lower,
        347 => Lower,
        349 => Lower,
        351 => Lower,
        353 => Lower,
        355 => Lower,
        357 => Lower,
        359 => Lower,
        361 => Lower,
        363 => Lower,
        365 => Lower,
        367 => Lower,
        369 => Lower,
        371 => Lower,
        373 => Lower,
        375 => Lower,
        378 => Lower,
        380 => Lower,
        387 => Lower,
        389 => Lower,
        392 => Lower,
        402 => Lower,
        405 => Lower,
        414 => Lower,
        417 => Lower,
        419 => Lower,
        421 => Lower,
        424 => Lower,
        429 => Lower,
        432 => Lower,
        436 => Lower,
        438 => Lower,
        454 => Lower,
        457 => Lower,
        460 => Lower,
        462 => Lower,
        464 => Lower,
        466 => Lower,
        468 => Lower,
        470 => Lower,
        472 => Lower,
        474 => Lower,
        479 => Lower,
        481 => Lower,
        483 => Lower,
        485 => Lower,
        487 => Lower,
        489 => Lower,
        491 => Lower,
        493 => Lower,
        499 => Lower,
        501 => Lower,
        505 => Lower,
        507 => Lower,
        509 => Lower,
        511 => Lower,
        513 => Lower,
        515 => Lower,
        517 => Lower,
        519 => Lower,
        521 => Lower,
        523 => Lower,
        525 => Lower,
        527 => Lower,
        529 => Lower,
        531 => Lower,
        533 => Lower,
        535 => Lower,
        537 => Lower,
        539 => Lower,
        541 => Lower,
        543 => Lower,
        545 => Lower,
        547 => Lower,
        549 => Lower,
        551 => Lower,
        553 => Lower,
        555 => Lower,
        557 => Lower,
        559 => Lower,
        561 => Lower,
        572 => Lower,
        578 => Lower,
        583 => Lower,
        585 => Lower,
        587 => Lower,
        589 => Lower,
        881 => Lower,
        883 => Lower,
        887 => Lower,
        890 => Lower,
        912 => Lower,
        985 => Lower,
        987 => Lower,
        989 => Lower,
        991 => Lower,
        993 => Lower,
        995 => Lower,
        997 => Lower,
        999 => Lower,
        1001 => Lower,
        1003 => Lower,
        1005 => Lower,
        1013 => Lower,
        1016 => Lower,
        1121 => Lower,
        1123 => Lower,
        1125 => Lower,
        1127 => Lower,
        1129 => Lower,
        1131 => Lower,
        1133 => Lower,
        1135 => Lower,
        1137 => Lower,
        1139 => Lower,
        1141 => Lower,
        1143 => Lower,
        1145 => Lower,
        1147 => Lower,
        1149 => Lower,
        1151 => Lower,
        1153 => Lower,
        1163 => Lower,
        1165 => Lower,
        1167 => Lower,
        1169 => Lower,
        1171 => Lower,
        1173 => Lower,
        1175 => Lower,
        1177 => Lower,
        1179 => Lower,
        1181 => Lower,
        1183 => Lower,
        1185 => Lower,
        1187 => Lower,
        1189 => Lower,
        1191 => Lower,
        1193 => Lower,
        1195 => Lower,
        1197 => Lower,
        1199 => Lower,
        1201 => Lower,
        1203 => Lower,
        1205 => Lower,
        1207 => Lower,
        1209 => Lower,
        1211 => Lower,
        1213 => Lower,
        1215 => Lower,
        1218 => Lower,
        1220 => Lower,
        1222 => Lower,
        1224 => Lower,
        1226 => Lower,
        1228 => Lower,
        1233 => Lower,
        1235 => Lower,
        1237 => Lower,
        1239 => Lower,
        1241 => Lower,
        1243 => Lower,
        1245 => Lower,
        1247 => Lower,
        1249 => Lower,
        1251 => Lower,
        1253 => Lower,
        1255 => Lower,
        1257 => Lower,
        1259 => Lower,
        1261 => Lower,
        1263 => Lower,
        1265 => Lower,
        1267 => Lower,
        1269 => Lower,
        1271 => Lower,
        1273 => Lower,
        1275 => Lower,
        1277 => Lower,
        1279 => Lower,
        1281 => Lower,
        1283 => Lower,
        1285 => Lower,
        1287 => Lower,
        1289 => Lower,
        1291 => Lower,
        1293 => Lower,
        1295 => Lower,
        1297 => Lower,
        1299 => Lower,
        1301 => Lower,
        1303 => Lower,
        1305 => Lower,
        1307 => Lower,
        1309 => Lower,
        1311 => Lower,
        1313 => Lower,
        1315 => Lower,
        1317 => Lower,
        1319 => Lower,
        1321 => Lower,
        1323 => Lower,
        1325 => Lower,
        1327 => Lower,
        7544 => Lower,
        7681 => Lower,
        7683 => Lower,
        7685 => Lower,
        7687 => Lower,
        7689 => Lower,
        7691 => Lower,
        7693 => Lower,
        7695 => Lower,
        7697 => Lower,
        7699 => Lower,
        7701 => Lower,
        7703 => Lower,
        7705 => Lower,
        7707 => Lower,
        7709 => Lower,
        7711 => Lower,
        7713 => Lower,
        7715 => Lower,
        7717 => Lower,
        7719 => Lower,
        7721 => Lower,
        7723 => Lower,
        7725 => Lower,
        7727 => Lower,
        7729 => Lower,
        7731 => Lower,
        7733 => Lower,
        7735 => Lower,
        7737 => Lower,
        7739 => Lower,
        7741 => Lower,
        7743 => Lower,
        7745 => Lower,
        7747 => Lower,
        7749 => Lower,
        7751 => Lower,
        7753 => Lower,
        7755 => Lower,
        7757 => Lower,
        7759 => Lower,
        7761 => Lower,
        7763 => Lower,
        7765 => Lower,
        7767 => Lower,
        7769 => Lower,
        7771 => Lower,
        7773 => Lower,
        7775 => Lower,
        7777 => Lower,
        7779 => Lower,
        7781 => Lower,
        7783 => Lower,
        7785 => Lower,
        7787 => Lower,
        7789 => Lower,
        7791 => Lower,
        7793 => Lower,
        7795 => Lower,
        7797 => Lower,
        7799 => Lower,
        7801 => Lower,
        7803 => Lower,
        7805 => Lower,
        7807 => Lower,
        7809 => Lower,
        7811 => Lower,
        7813 => Lower,
        7815 => Lower,
        7817 => Lower,
        7819 => Lower,
        7821 => Lower,
        7823 => Lower,
        7825 => Lower,
        7827 => Lower,
        7839 => Lower,
        7841 => Lower,
        7843 => Lower,
        7845 => Lower,
        7847 => Lower,
        7849 => Lower,
        7851 => Lower,
        7853 => Lower,
        7855 => Lower,
        7857 => Lower,
        7859 => Lower,
        7861 => Lower,
        7863 => Lower,
        7865 => Lower,
        7867 => Lower,
        7869 => Lower,
        7871 => Lower,
        7873 => Lower,
        7875 => Lower,
        7877 => Lower,
        7879 => Lower,
        7881 => Lower,
        7883 => Lower,
        7885 => Lower,
        7887 => Lower,
        7889 => Lower,
        7891 => Lower,
        7893 => Lower,
        7895 => Lower,
        7897 => Lower,
        7899 => Lower,
        7901 => Lower,
        7903 => Lower,
        7905 => Lower,
        7907 => Lower,
        7909 => Lower,
        7911 => Lower,
        7913 => Lower,
        7915 => Lower,
        7917 => Lower,
        7919 => Lower,
        7921 => Lower,
        7923 => Lower,
        7925 => Lower,
        7927 => Lower,
        7929 => Lower,
        7931 => Lower,
        7933 => Lower,
        8126 => Lower,
        8305 => Lower,
        8319 => Lower,
        8458 => Lower,
        8467 => Lower,
        8495 => Lower,
        8500 => Lower,
        8505 => Lower,
        8526 => Lower,
        8580 => Lower,
        11361 => Lower,
        11368 => Lower,
        11370 => Lower,
        11372 => Lower,
        11377 => Lower,
        11393 => Lower,
        11395 => Lower,
        11397 => Lower,
        11399 => Lower,
        11401 => Lower,
        11403 => Lower,
        11405 => Lower,
        11407 => Lower,
        11409 => Lower,
        11411 => Lower,
        11413 => Lower,
        11415 => Lower,
        11417 => Lower,
        11419 => Lower,
        11421 => Lower,
        11423 => Lower,
        11425 => Lower,
        11427 => Lower,
        11429 => Lower,
        11431 => Lower,
        11433 => Lower,
        11435 => Lower,
        11437 => Lower,
        11439 => Lower,
        11441 => Lower,
        11443 => Lower,
        11445 => Lower,
        11447 => Lower,
        11449 => Lower,
        11451 => Lower,
        11453 => Lower,
        11455 => Lower,
        11457 => Lower,
        11459 => Lower,
        11461 => Lower,
        11463 => Lower,
        11465 => Lower,
        11467 => Lower,
        11469 => Lower,
        11471 => Lower,
        11473 => Lower,
        11475 => Lower,
        11477 => Lower,
        11479 => Lower,
        11481 => Lower,
        11483 => Lower,
        11485 => Lower,
        11487 => Lower,
        11489 => Lower,
        11500 => Lower,
        11502 => Lower,
        11507 => Lower,
        11559 => Lower,
        11565 => Lower,
        42561 => Lower,
        42563 => Lower,
        42565 => Lower,
        42567 => Lower,
        42569 => Lower,
        42571 => Lower,
        42573 => Lower,
        42575 => Lower,
        42577 => Lower,
        42579 => Lower,
        42581 => Lower,
        42583 => Lower,
        42585 => Lower,
        42587 => Lower,
        42589 => Lower,
        42591 => Lower,
        42593 => Lower,
        42595 => Lower,
        42597 => Lower,
        42599 => Lower,
        42601 => Lower,
        42603 => Lower,
        42605 => Lower,
        42625 => Lower,
        42627 => Lower,
        42629 => Lower,
        42631 => Lower,
        42633 => Lower,
        42635 => Lower,
        42637 => Lower,
        42639 => Lower,
        42641 => Lower,
        42643 => Lower,
        42645 => Lower,
        42647 => Lower,
        42649 => Lower,
        42651 => Lower,
        42787 => Lower,
        42789 => Lower,
        42791 => Lower,
        42793 => Lower,
        42795 => Lower,
        42797 => Lower,
        42803 => Lower,
        42805 => Lower,
        42807 => Lower,
        42809 => Lower,
        42811 => Lower,
        42813 => Lower,
        42815 => Lower,
        42817 => Lower,
        42819 => Lower,
        42821 => Lower,
        42823 => Lower,
        42825 => Lower,
        42827 => Lower,
        42829 => Lower,
        42831 => Lower,
        42833 => Lower,
        42835 => Lower,
        42837 => Lower,
        42839 => Lower,
        42841 => Lower,
        42843 => Lower,
        42845 => Lower,
        42847 => Lower,
        42849 => Lower,
        42851 => Lower,
        42853 => Lower,
        42855 => Lower,
        42857 => Lower,
        42859 => Lower,
        42861 => Lower,
        42863 => Lower,
        42864 => Lower,
        42874 => Lower,
        42876 => Lower,
        42879 => Lower,
        42881 => Lower,
        42883 => Lower,
        42885 => Lower,
        42887 => Lower,
        42892 => Lower,
        42894 => Lower,
        42897 => Lower,
        42903 => Lower,
        42905 => Lower,
        42907 => Lower,
        42909 => Lower,
        42911 => Lower,
        42913 => Lower,
        42915 => Lower,
        42917 => Lower,
        42919 => Lower,
        42921 => Lower,
        42933 => Lower,
        42935 => Lower,
        43002 => Lower,
        119995 => Lower,
        120779 => Lower,
        256 => Upper,
        258 => Upper,
        260 => Upper,
        262 => Upper,
        264 => Upper,
        266 => Upper,
        268 => Upper,
        270 => Upper,
        272 => Upper,
        274 => Upper,
        276 => Upper,
        278 => Upper,
        280 => Upper,
        282 => Upper,
        284 => Upper,
        286 => Upper,
        288 => Upper,
        290 => Upper,
        292 => Upper,
        294 => Upper,
        296 => Upper,
        298 => Upper,
        300 => Upper,
        302 => Upper,
        304 => Upper,
        306 => Upper,
        308 => Upper,
        310 => Upper,
        313 => Upper,
        315 => Upper,
        317 => Upper,
        319 => Upper,
        321 => Upper,
        323 => Upper,
        325 => Upper,
        327 => Upper,
        330 => Upper,
        332 => Upper,
        334 => Upper,
        336 => Upper,
        338 => Upper,
        340 => Upper,
        342 => Upper,
        344 => Upper,
        346 => Upper,
        348 => Upper,
        350 => Upper,
        352 => Upper,
        354 => Upper,
        356 => Upper,
        358 => Upper,
        360 => Upper,
        362 => Upper,
        364 => Upper,
        366 => Upper,
        368 => Upper,
        370 => Upper,
        372 => Upper,
        374 => Upper,
        379 => Upper,
        381 => Upper,
        388 => Upper,
        418 => Upper,
        420 => Upper,
        425 => Upper,
        428 => Upper,
        437 => Upper,
        444 => Upper,
        461 => Upper,
        463 => Upper,
        465 => Upper,
        467 => Upper,
        469 => Upper,
        471 => Upper,
        473 => Upper,
        475 => Upper,
        478 => Upper,
        480 => Upper,
        482 => Upper,
        484 => Upper,
        486 => Upper,
        488 => Upper,
        490 => Upper,
        492 => Upper,
        494 => Upper,
        500 => Upper,
        506 => Upper,
        508 => Upper,
        510 => Upper,
        512 => Upper,
        514 => Upper,
        516 => Upper,
        518 => Upper,
        520 => Upper,
        522 => Upper,
        524 => Upper,
        526 => Upper,
        528 => Upper,
        530 => Upper,
        532 => Upper,
        534 => Upper,
        536 => Upper,
        538 => Upper,
        540 => Upper,
        542 => Upper,
        544 => Upper,
        546 => Upper,
        548 => Upper,
        550 => Upper,
        552 => Upper,
        554 => Upper,
        556 => Upper,
        558 => Upper,
        560 => Upper,
        562 => Upper,
        577 => Upper,
        584 => Upper,
        586 => Upper,
        588 => Upper,
        590 => Upper,
        880 => Upper,
        882 => Upper,
        886 => Upper,
        895 => Upper,
        902 => Upper,
        908 => Upper,
        975 => Upper,
        984 => Upper,
        986 => Upper,
        988 => Upper,
        990 => Upper,
        992 => Upper,
        994 => Upper,
        996 => Upper,
        998 => Upper,
        1000 => Upper,
        1002 => Upper,
        1004 => Upper,
        1006 => Upper,
        1012 => Upper,
        1015 => Upper,
        1120 => Upper,
        1122 => Upper,
        1124 => Upper,
        1126 => Upper,
        1128 => Upper,
        1130 => Upper,
        1132 => Upper,
        1134 => Upper,
        1136 => Upper,
        1138 => Upper,
        1140 => Upper,
        1142 => Upper,
        1144 => Upper,
        1146 => Upper,
        1148 => Upper,
        1150 => Upper,
        1152 => Upper,
        1162 => Upper,
        1164 => Upper,
        1166 => Upper,
        1168 => Upper,
        1170 => Upper,
        1172 => Upper,
        1174 => Upper,
        1176 => Upper,
        1178 => Upper,
        1180 => Upper,
        1182 => Upper,
        1184 => Upper,
        1186 => Upper,
        1188 => Upper,
        1190 => Upper,
        1192 => Upper,
        1194 => Upper,
        1196 => Upper,
        1198 => Upper,
        1200 => Upper,
        1202 => Upper,
        1204 => Upper,
        1206 => Upper,
        1208 => Upper,
        1210 => Upper,
        1212 => Upper,
        1214 => Upper,
        1219 => Upper,
        1221 => Upper,
        1223 => Upper,
        1225 => Upper,
        1227 => Upper,
        1229 => Upper,
        1232 => Upper,
        1234 => Upper,
        1236 => Upper,
        1238 => Upper,
        1240 => Upper,
        1242 => Upper,
        1244 => Upper,
        1246 => Upper,
        1248 => Upper,
        1250 => Upper,
        1252 => Upper,
        1254 => Upper,
        1256 => Upper,
        1258 => Upper,
        1260 => Upper,
        1262 => Upper,
        1264 => Upper,
        1266 => Upper,
        1268 => Upper,
        1270 => Upper,
        1272 => Upper,
        1274 => Upper,
        1276 => Upper,
        1278 => Upper,
        1280 => Upper,
        1282 => Upper,
        1284 => Upper,
        1286 => Upper,
        1288 => Upper,
        1290 => Upper,
        1292 => Upper,
        1294 => Upper,
        1296 => Upper,
        1298 => Upper,
        1300 => Upper,
        1302 => Upper,
        1304 => Upper,
        1306 => Upper,
        1308 => Upper,
        1310 => Upper,
        1312 => Upper,
        1314 => Upper,
        1316 => Upper,
        1318 => Upper,
        1320 => Upper,
        1322 => Upper,
        1324 => Upper,
        1326 => Upper,
        4295 => Upper,
        4301 => Upper,
        7680 => Upper,
        7682 => Upper,
        7684 => Upper,
        7686 => Upper,
        7688 => Upper,
        7690 => Upper,
        7692 => Upper,
        7694 => Upper,
        7696 => Upper,
        7698 => Upper,
        7700 => Upper,
        7702 => Upper,
        7704 => Upper,
        7706 => Upper,
        7708 => Upper,
        7710 => Upper,
        7712 => Upper,
        7714 => Upper,
        7716 => Upper,
        7718 => Upper,
        7720 => Upper,
        7722 => Upper,
        7724 => Upper,
        7726 => Upper,
        7728 => Upper,
        7730 => Upper,
        7732 => Upper,
        7734 => Upper,
        7736 => Upper,
        7738 => Upper,
        7740 => Upper,
        7742 => Upper,
        7744 => Upper,
        7746 => Upper,
        7748 => Upper,
        7750 => Upper,
        7752 => Upper,
        7754 => Upper,
        7756 => Upper,
        7758 => Upper,
        7760 => Upper,
        7762 => Upper,
        7764 => Upper,
        7766 => Upper,
        7768 => Upper,
        7770 => Upper,
        7772 => Upper,
        7774 => Upper,
        7776 => Upper,
        7778 => Upper,
        7780 => Upper,
        7782 => Upper,
        7784 => Upper,
        7786 => Upper,
        7788 => Upper,
        7790 => Upper,
        7792 => Upper,
        7794 => Upper,
        7796 => Upper,
        7798 => Upper,
        7800 => Upper,
        7802 => Upper,
        7804 => Upper,
        7806 => Upper,
        7808 => Upper,
        7810 => Upper,
        7812 => Upper,
        7814 => Upper,
        7816 => Upper,
        7818 => Upper,
        7820 => Upper,
        7822 => Upper,
        7824 => Upper,
        7826 => Upper,
        7828 => Upper,
        7838 => Upper,
        7840 => Upper,
        7842 => Upper,
        7844 => Upper,
        7846 => Upper,
        7848 => Upper,
        7850 => Upper,
        7852 => Upper,
        7854 => Upper,
        7856 => Upper,
        7858 => Upper,
        7860 => Upper,
        7862 => Upper,
        7864 => Upper,
        7866 => Upper,
        7868 => Upper,
        7870 => Upper,
        7872 => Upper,
        7874 => Upper,
        7876 => Upper,
        7878 => Upper,
        7880 => Upper,
        7882 => Upper,
        7884 => Upper,
        7886 => Upper,
        7888 => Upper,
        7890 => Upper,
        7892 => Upper,
        7894 => Upper,
        7896 => Upper,
        7898 => Upper,
        7900 => Upper,
        7902 => Upper,
        7904 => Upper,
        7906 => Upper,
        7908 => Upper,
        7910 => Upper,
        7912 => Upper,
        7914 => Upper,
        7916 => Upper,
        7918 => Upper,
        7920 => Upper,
        7922 => Upper,
        7924 => Upper,
        7926 => Upper,
        7928 => Upper,
        7930 => Upper,
        7932 => Upper,
        7934 => Upper,
        8025 => Upper,
        8027 => Upper,
        8029 => Upper,
        8031 => Upper,
        8450 => Upper,
        8455 => Upper,
        8469 => Upper,
        8484 => Upper,
        8486 => Upper,
        8488 => Upper,
        8517 => Upper,
        8579 => Upper,
        11360 => Upper,
        11367 => Upper,
        11369 => Upper,
        11371 => Upper,
        11378 => Upper,
        11381 => Upper,
        11394 => Upper,
        11396 => Upper,
        11398 => Upper,
        11400 => Upper,
        11402 => Upper,
        11404 => Upper,
        11406 => Upper,
        11408 => Upper,
        11410 => Upper,
        11412 => Upper,
        11414 => Upper,
        11416 => Upper,
        11418 => Upper,
        11420 => Upper,
        11422 => Upper,
        11424 => Upper,
        11426 => Upper,
        11428 => Upper,
        11430 => Upper,
        11432 => Upper,
        11434 => Upper,
        11436 => Upper,
        11438 => Upper,
        11440 => Upper,
        11442 => Upper,
        11444 => Upper,
        11446 => Upper,
        11448 => Upper,
        11450 => Upper,
        11452 => Upper,
        11454 => Upper,
        11456 => Upper,
        11458 => Upper,
        11460 => Upper,
        11462 => Upper,
        11464 => Upper,
        11466 => Upper,
        11468 => Upper,
        11470 => Upper,
        11472 => Upper,
        11474 => Upper,
        11476 => Upper,
        11478 => Upper,
        11480 => Upper,
        11482 => Upper,
        11484 => Upper,
        11486 => Upper,
        11488 => Upper,
        11490 => Upper,
        11499 => Upper,
        11501 => Upper,
        11506 => Upper,
        42560 => Upper,
        42562 => Upper,
        42564 => Upper,
        42566 => Upper,
        42568 => Upper,
        42570 => Upper,
        42572 => Upper,
        42574 => Upper,
        42576 => Upper,
        42578 => Upper,
        42580 => Upper,
        42582 => Upper,
        42584 => Upper,
        42586 => Upper,
        42588 => Upper,
        42590 => Upper,
        42592 => Upper,
        42594 => Upper,
        42596 => Upper,
        42598 => Upper,
        42600 => Upper,
        42602 => Upper,
        42604 => Upper,
        42624 => Upper,
        42626 => Upper,
        42628 => Upper,
        42630 => Upper,
        42632 => Upper,
        42634 => Upper,
        42636 => Upper,
        42638 => Upper,
        42640 => Upper,
        42642 => Upper,
        42644 => Upper,
        42646 => Upper,
        42648 => Upper,
        42650 => Upper,
        42786 => Upper,
        42788 => Upper,
        42790 => Upper,
        42792 => Upper,
        42794 => Upper,
        42796 => Upper,
        42798 => Upper,
        42802 => Upper,
        42804 => Upper,
        42806 => Upper,
        42808 => Upper,
        42810 => Upper,
        42812 => Upper,
        42814 => Upper,
        42816 => Upper,
        42818 => Upper,
        42820 => Upper,
        42822 => Upper,
        42824 => Upper,
        42826 => Upper,
        42828 => Upper,
        42830 => Upper,
        42832 => Upper,
        42834 => Upper,
        42836 => Upper,
        42838 => Upper,
        42840 => Upper,
        42842 => Upper,
        42844 => Upper,
        42846 => Upper,
        42848 => Upper,
        42850 => Upper,
        42852 => Upper,
        42854 => Upper,
        42856 => Upper,
        42858 => Upper,
        42860 => Upper,
        42862 => Upper,
        42873 => Upper,
        42875 => Upper,
        42880 => Upper,
        42882 => Upper,
        42884 => Upper,
        42886 => Upper,
        42891 => Upper,
        42893 => Upper,
        42896 => Upper,
        42898 => Upper,
        42902 => Upper,
        42904 => Upper,
        42906 => Upper,
        42908 => Upper,
        42910 => Upper,
        42912 => Upper,
        42914 => Upper,
        42916 => Upper,
        42918 => Upper,
        42920 => Upper,
        42934 => Upper,
        119964 => Upper,
        119970 => Upper,
        120134 => Upper,
        120778 => Upper,
        443 => OLetter,
        660 => OLetter,
        748 => OLetter,
        750 => OLetter,
        884 => OLetter,
        1369 => OLetter,
        1523 => OLetter,
        1600 => OLetter,
        1749 => OLetter,
        1791 => OLetter,
        1808 => OLetter,
        1969 => OLetter,
        2042 => OLetter,
        2074 => OLetter,
        2084 => OLetter,
        2088 => OLetter,
        2365 => OLetter,
        2384 => OLetter,
        2417 => OLetter,
        2482 => OLetter,
        2493 => OLetter,
        2510 => OLetter,
        2654 => OLetter,
        2749 => OLetter,
        2768 => OLetter,
        2809 => OLetter,
        2877 => OLetter,
        2929 => OLetter,
        2947 => OLetter,
        2972 => OLetter,
        3024 => OLetter,
        3133 => OLetter,
        3200 => OLetter,
        3261 => OLetter,
        3294 => OLetter,
        3389 => OLetter,
        3406 => OLetter,
        3517 => OLetter,
        3654 => OLetter,
        3716 => OLetter,
        3722 => OLetter,
        3725 => OLetter,
        3749 => OLetter,
        3751 => OLetter,
        3773 => OLetter,
        3782 => OLetter,
        3840 => OLetter,
        4159 => OLetter,
        4193 => OLetter,
        4238 => OLetter,
        4348 => OLetter,
        4696 => OLetter,
        4800 => OLetter,
        6103 => OLetter,
        6108 => OLetter,
        6211 => OLetter,
        6314 => OLetter,
        6823 => OLetter,
        11631 => OLetter,
        11823 => OLetter,
        12293 => OLetter,
        12294 => OLetter,
        12295 => OLetter,
        12347 => OLetter,
        12348 => OLetter,
        12447 => OLetter,
        12543 => OLetter,
        40981 => OLetter,
        42508 => OLetter,
        42606 => OLetter,
        42623 => OLetter,
        42888 => OLetter,
        42895 => OLetter,
        42999 => OLetter,
        43259 => OLetter,
        43261 => OLetter,
        43471 => OLetter,
        43494 => OLetter,
        43632 => OLetter,
        43642 => OLetter,
        43697 => OLetter,
        43712 => OLetter,
        43714 => OLetter,
        43741 => OLetter,
        43762 => OLetter,
        64285 => OLetter,
        64318 => OLetter,
        65392 => OLetter,
        66369 => OLetter,
        66378 => OLetter,
        67592 => OLetter,
        67644 => OLetter,
        68096 => OLetter,
        70006 => OLetter,
        70106 => OLetter,
        70108 => OLetter,
        70280 => OLetter,
        70461 => OLetter,
        70480 => OLetter,
        70855 => OLetter,
        71236 => OLetter,
        71935 => OLetter,
        72768 => OLetter,
        94032 => OLetter,
        94176 => OLetter,
        126500 => OLetter,
        126503 => OLetter,
        126521 => OLetter,
        126523 => OLetter,
        126530 => OLetter,
        126535 => OLetter,
        126537 => OLetter,
        126539 => OLetter,
        126548 => OLetter,
        126551 => OLetter,
        126553 => OLetter,
        126555 => OLetter,
        126557 => OLetter,
        126559 => OLetter,
        126564 => OLetter,
        126590 => OLetter,
        46 => ATerm,
        8228 => ATerm,
        65106 => ATerm,
        65294 => ATerm,
        33 => STerm,
        63 => STerm,
        1417 => STerm,
        1567 => STerm,
        1748 => STerm,
        2041 => STerm,
        4962 => STerm,
        5742 => STerm,
        6147 => STerm,
        6153 => STerm,
        11822 => STerm,
        11836 => STerm,
        12290 => STerm,
        42239 => STerm,
        42739 => STerm,
        42743 => STerm,
        43311 => STerm,
        44011 => STerm,
        65281 => STerm,
        65311 => STerm,
        65377 => STerm,
        70093 => STerm,
        70313 => STerm,
        92917 => STerm,
        92996 => STerm,
        113823 => STerm,
        121480 => STerm,
        34 => Close,
        39 => Close,
        40 => Close,
        41 => Close,
        91 => Close,
        93 => Close,
        123 => Close,
        125 => Close,
        171 => Close,
        187 => Close,
        3898 => Close,
        3899 => Close,
        3900 => Close,
        3901 => Close,
        5787 => Close,
        5788 => Close,
        8216 => Close,
        8217 => Close,
        8218 => Close,
        8221 => Close,
        8222 => Close,
        8223 => Close,
        8249 => Close,
        8250 => Close,
        8261 => Close,
        8262 => Close,
        8317 => Close,
        8318 => Close,
        8333 => Close,
        8334 => Close,
        8968 => Close,
        8969 => Close,
        8970 => Close,
        8971 => Close,
        9001 => Close,
        9002 => Close,
        10088 => Close,
        10089 => Close,
        10090 => Close,
        10091 => Close,
        10092 => Close,
        10093 => Close,
        10094 => Close,
        10095 => Close,
        10096 => Close,
        10097 => Close,
        10098 => Close,
        10099 => Close,
        10100 => Close,
        10101 => Close,
        10181 => Close,
        10182 => Close,
        10214 => Close,
        10215 => Close,
        10216 => Close,
        10217 => Close,
        10218 => Close,
        10219 => Close,
        10220 => Close,
        10221 => Close,
        10222 => Close,
        10223 => Close,
        10627 => Close,
        10628 => Close,
        10629 => Close,
        10630 => Close,
        10631 => Close,
        10632 => Close,
        10633 => Close,
        10634 => Close,
        10635 => Close,
        10636 => Close,
        10637 => Close,
        10638 => Close,
        10639 => Close,
        10640 => Close,
        10641 => Close,
        10642 => Close,
        10643 => Close,
        10644 => Close,
        10645 => Close,
        10646 => Close,
        10647 => Close,
        10648 => Close,
        10712 => Close,
        10713 => Close,
        10714 => Close,
        10715 => Close,
        10748 => Close,
        10749 => Close,
        11778 => Close,
        11779 => Close,
        11780 => Close,
        11781 => Close,
        11785 => Close,
        11786 => Close,
        11787 => Close,
        11788 => Close,
        11789 => Close,
        11804 => Close,
        11805 => Close,
        11808 => Close,
        11809 => Close,
        11810 => Close,
        11811 => Close,
        11812 => Close,
        11813 => Close,
        11814 => Close,
        11815 => Close,
        11816 => Close,
        11817 => Close,
        11842 => Close,
        12296 => Close,
        12297 => Close,
        12298 => Close,
        12299 => Close,
        12300 => Close,
        12301 => Close,
        12302 => Close,
        12303 => Close,
        12304 => Close,
        12305 => Close,
        12308 => Close,
        12309 => Close,
        12310 => Close,
        12311 => Close,
        12312 => Close,
        12313 => Close,
        12314 => Close,
        12315 => Close,
        12317 => Close,
        64830 => Close,
        64831 => Close,
        65047 => Close,
        65048 => Close,
        65077 => Close,
        65078 => Close,
        65079 => Close,
        65080 => Close,
        65081 => Close,
        65082 => Close,
        65083 => Close,
        65084 => Close,
        65085 => Close,
        65086 => Close,
        65087 => Close,
        65088 => Close,
        65089 => Close,
        65090 => Close,
        65091 => Close,
        65092 => Close,
        65095 => Close,
        65096 => Close,
        65113 => Close,
        65114 => Close,
        65115 => Close,
        65116 => Close,
        65117 => Close,
        65118 => Close,
        65288 => Close,
        65289 => Close,
        65339 => Close,
        65341 => Close,
        65371 => Close,
        65373 => Close,
        65375 => Close,
        65376 => Close,
        65378 => Close,
        65379 => Close,
        44 => SContinue,
        45 => SContinue,
        58 => SContinue,
        1373 => SContinue,
        2040 => SContinue,
        6146 => SContinue,
        6152 => SContinue,
        12289 => SContinue,
        65043 => SContinue,
        65109 => SContinue,
        65112 => SContinue,
        65123 => SContinue,
        65292 => SContinue,
        65293 => SContinue,
        65306 => SContinue,
        65380 => SContinue,
        ];
    public static function get(code:Int):SentenceValuesEnum {
        if (code >= 768 && code <= 879) return Extend;
        if (code >= 1155 && code <= 1159) return Extend;
        if (code >= 1160 && code <= 1161) return Extend;
        if (code >= 1425 && code <= 1469) return Extend;
        if (code >= 1473 && code <= 1474) return Extend;
        if (code >= 1476 && code <= 1477) return Extend;
        if (code >= 1552 && code <= 1562) return Extend;
        if (code >= 1611 && code <= 1631) return Extend;
        if (code >= 1750 && code <= 1756) return Extend;
        if (code >= 1759 && code <= 1764) return Extend;
        if (code >= 1767 && code <= 1768) return Extend;
        if (code >= 1770 && code <= 1773) return Extend;
        if (code >= 1840 && code <= 1866) return Extend;
        if (code >= 1958 && code <= 1968) return Extend;
        if (code >= 2027 && code <= 2035) return Extend;
        if (code >= 2070 && code <= 2073) return Extend;
        if (code >= 2075 && code <= 2083) return Extend;
        if (code >= 2085 && code <= 2087) return Extend;
        if (code >= 2089 && code <= 2093) return Extend;
        if (code >= 2137 && code <= 2139) return Extend;
        if (code >= 2260 && code <= 2273) return Extend;
        if (code >= 2275 && code <= 2306) return Extend;
        if (code >= 2366 && code <= 2368) return Extend;
        if (code >= 2369 && code <= 2376) return Extend;
        if (code >= 2377 && code <= 2380) return Extend;
        if (code >= 2382 && code <= 2383) return Extend;
        if (code >= 2385 && code <= 2391) return Extend;
        if (code >= 2402 && code <= 2403) return Extend;
        if (code >= 2434 && code <= 2435) return Extend;
        if (code >= 2494 && code <= 2496) return Extend;
        if (code >= 2497 && code <= 2500) return Extend;
        if (code >= 2503 && code <= 2504) return Extend;
        if (code >= 2507 && code <= 2508) return Extend;
        if (code >= 2530 && code <= 2531) return Extend;
        if (code >= 2561 && code <= 2562) return Extend;
        if (code >= 2622 && code <= 2624) return Extend;
        if (code >= 2625 && code <= 2626) return Extend;
        if (code >= 2631 && code <= 2632) return Extend;
        if (code >= 2635 && code <= 2637) return Extend;
        if (code >= 2672 && code <= 2673) return Extend;
        if (code >= 2689 && code <= 2690) return Extend;
        if (code >= 2750 && code <= 2752) return Extend;
        if (code >= 2753 && code <= 2757) return Extend;
        if (code >= 2759 && code <= 2760) return Extend;
        if (code >= 2763 && code <= 2764) return Extend;
        if (code >= 2786 && code <= 2787) return Extend;
        if (code >= 2818 && code <= 2819) return Extend;
        if (code >= 2881 && code <= 2884) return Extend;
        if (code >= 2887 && code <= 2888) return Extend;
        if (code >= 2891 && code <= 2892) return Extend;
        if (code >= 2914 && code <= 2915) return Extend;
        if (code >= 3006 && code <= 3007) return Extend;
        if (code >= 3009 && code <= 3010) return Extend;
        if (code >= 3014 && code <= 3016) return Extend;
        if (code >= 3018 && code <= 3020) return Extend;
        if (code >= 3073 && code <= 3075) return Extend;
        if (code >= 3134 && code <= 3136) return Extend;
        if (code >= 3137 && code <= 3140) return Extend;
        if (code >= 3142 && code <= 3144) return Extend;
        if (code >= 3146 && code <= 3149) return Extend;
        if (code >= 3157 && code <= 3158) return Extend;
        if (code >= 3170 && code <= 3171) return Extend;
        if (code >= 3202 && code <= 3203) return Extend;
        if (code >= 3264 && code <= 3268) return Extend;
        if (code >= 3271 && code <= 3272) return Extend;
        if (code >= 3274 && code <= 3275) return Extend;
        if (code >= 3276 && code <= 3277) return Extend;
        if (code >= 3285 && code <= 3286) return Extend;
        if (code >= 3298 && code <= 3299) return Extend;
        if (code >= 3330 && code <= 3331) return Extend;
        if (code >= 3390 && code <= 3392) return Extend;
        if (code >= 3393 && code <= 3396) return Extend;
        if (code >= 3398 && code <= 3400) return Extend;
        if (code >= 3402 && code <= 3404) return Extend;
        if (code >= 3426 && code <= 3427) return Extend;
        if (code >= 3458 && code <= 3459) return Extend;
        if (code >= 3535 && code <= 3537) return Extend;
        if (code >= 3538 && code <= 3540) return Extend;
        if (code >= 3544 && code <= 3551) return Extend;
        if (code >= 3570 && code <= 3571) return Extend;
        if (code >= 3636 && code <= 3642) return Extend;
        if (code >= 3655 && code <= 3662) return Extend;
        if (code >= 3764 && code <= 3769) return Extend;
        if (code >= 3771 && code <= 3772) return Extend;
        if (code >= 3784 && code <= 3789) return Extend;
        if (code >= 3864 && code <= 3865) return Extend;
        if (code >= 3902 && code <= 3903) return Extend;
        if (code >= 3953 && code <= 3966) return Extend;
        if (code >= 3968 && code <= 3972) return Extend;
        if (code >= 3974 && code <= 3975) return Extend;
        if (code >= 3981 && code <= 3991) return Extend;
        if (code >= 3993 && code <= 4028) return Extend;
        if (code >= 4139 && code <= 4140) return Extend;
        if (code >= 4141 && code <= 4144) return Extend;
        if (code >= 4146 && code <= 4151) return Extend;
        if (code >= 4153 && code <= 4154) return Extend;
        if (code >= 4155 && code <= 4156) return Extend;
        if (code >= 4157 && code <= 4158) return Extend;
        if (code >= 4182 && code <= 4183) return Extend;
        if (code >= 4184 && code <= 4185) return Extend;
        if (code >= 4190 && code <= 4192) return Extend;
        if (code >= 4194 && code <= 4196) return Extend;
        if (code >= 4199 && code <= 4205) return Extend;
        if (code >= 4209 && code <= 4212) return Extend;
        if (code >= 4227 && code <= 4228) return Extend;
        if (code >= 4229 && code <= 4230) return Extend;
        if (code >= 4231 && code <= 4236) return Extend;
        if (code >= 4250 && code <= 4252) return Extend;
        if (code >= 4957 && code <= 4959) return Extend;
        if (code >= 5906 && code <= 5908) return Extend;
        if (code >= 5938 && code <= 5940) return Extend;
        if (code >= 5970 && code <= 5971) return Extend;
        if (code >= 6002 && code <= 6003) return Extend;
        if (code >= 6068 && code <= 6069) return Extend;
        if (code >= 6071 && code <= 6077) return Extend;
        if (code >= 6078 && code <= 6085) return Extend;
        if (code >= 6087 && code <= 6088) return Extend;
        if (code >= 6089 && code <= 6099) return Extend;
        if (code >= 6155 && code <= 6157) return Extend;
        if (code >= 6277 && code <= 6278) return Extend;
        if (code >= 6432 && code <= 6434) return Extend;
        if (code >= 6435 && code <= 6438) return Extend;
        if (code >= 6439 && code <= 6440) return Extend;
        if (code >= 6441 && code <= 6443) return Extend;
        if (code >= 6448 && code <= 6449) return Extend;
        if (code >= 6451 && code <= 6456) return Extend;
        if (code >= 6457 && code <= 6459) return Extend;
        if (code >= 6679 && code <= 6680) return Extend;
        if (code >= 6681 && code <= 6682) return Extend;
        if (code >= 6744 && code <= 6750) return Extend;
        if (code >= 6755 && code <= 6756) return Extend;
        if (code >= 6757 && code <= 6764) return Extend;
        if (code >= 6765 && code <= 6770) return Extend;
        if (code >= 6771 && code <= 6780) return Extend;
        if (code >= 6832 && code <= 6845) return Extend;
        if (code >= 6912 && code <= 6915) return Extend;
        if (code >= 6966 && code <= 6970) return Extend;
        if (code >= 6973 && code <= 6977) return Extend;
        if (code >= 6979 && code <= 6980) return Extend;
        if (code >= 7019 && code <= 7027) return Extend;
        if (code >= 7040 && code <= 7041) return Extend;
        if (code >= 7074 && code <= 7077) return Extend;
        if (code >= 7078 && code <= 7079) return Extend;
        if (code >= 7080 && code <= 7081) return Extend;
        if (code >= 7083 && code <= 7085) return Extend;
        if (code >= 7144 && code <= 7145) return Extend;
        if (code >= 7146 && code <= 7148) return Extend;
        if (code >= 7151 && code <= 7153) return Extend;
        if (code >= 7154 && code <= 7155) return Extend;
        if (code >= 7204 && code <= 7211) return Extend;
        if (code >= 7212 && code <= 7219) return Extend;
        if (code >= 7220 && code <= 7221) return Extend;
        if (code >= 7222 && code <= 7223) return Extend;
        if (code >= 7376 && code <= 7378) return Extend;
        if (code >= 7380 && code <= 7392) return Extend;
        if (code >= 7394 && code <= 7400) return Extend;
        if (code >= 7410 && code <= 7411) return Extend;
        if (code >= 7416 && code <= 7417) return Extend;
        if (code >= 7616 && code <= 7669) return Extend;
        if (code >= 7675 && code <= 7679) return Extend;
        if (code >= 8204 && code <= 8205) return Extend;
        if (code >= 8400 && code <= 8412) return Extend;
        if (code >= 8413 && code <= 8416) return Extend;
        if (code >= 8418 && code <= 8420) return Extend;
        if (code >= 8421 && code <= 8432) return Extend;
        if (code >= 11503 && code <= 11505) return Extend;
        if (code >= 11744 && code <= 11775) return Extend;
        if (code >= 12330 && code <= 12333) return Extend;
        if (code >= 12334 && code <= 12335) return Extend;
        if (code >= 12441 && code <= 12442) return Extend;
        if (code >= 42608 && code <= 42610) return Extend;
        if (code >= 42612 && code <= 42621) return Extend;
        if (code >= 42654 && code <= 42655) return Extend;
        if (code >= 42736 && code <= 42737) return Extend;
        if (code >= 43043 && code <= 43044) return Extend;
        if (code >= 43045 && code <= 43046) return Extend;
        if (code >= 43136 && code <= 43137) return Extend;
        if (code >= 43188 && code <= 43203) return Extend;
        if (code >= 43204 && code <= 43205) return Extend;
        if (code >= 43232 && code <= 43249) return Extend;
        if (code >= 43302 && code <= 43309) return Extend;
        if (code >= 43335 && code <= 43345) return Extend;
        if (code >= 43346 && code <= 43347) return Extend;
        if (code >= 43392 && code <= 43394) return Extend;
        if (code >= 43444 && code <= 43445) return Extend;
        if (code >= 43446 && code <= 43449) return Extend;
        if (code >= 43450 && code <= 43451) return Extend;
        if (code >= 43453 && code <= 43456) return Extend;
        if (code >= 43561 && code <= 43566) return Extend;
        if (code >= 43567 && code <= 43568) return Extend;
        if (code >= 43569 && code <= 43570) return Extend;
        if (code >= 43571 && code <= 43572) return Extend;
        if (code >= 43573 && code <= 43574) return Extend;
        if (code >= 43698 && code <= 43700) return Extend;
        if (code >= 43703 && code <= 43704) return Extend;
        if (code >= 43710 && code <= 43711) return Extend;
        if (code >= 43756 && code <= 43757) return Extend;
        if (code >= 43758 && code <= 43759) return Extend;
        if (code >= 44003 && code <= 44004) return Extend;
        if (code >= 44006 && code <= 44007) return Extend;
        if (code >= 44009 && code <= 44010) return Extend;
        if (code >= 65024 && code <= 65039) return Extend;
        if (code >= 65056 && code <= 65071) return Extend;
        if (code >= 65438 && code <= 65439) return Extend;
        if (code >= 66422 && code <= 66426) return Extend;
        if (code >= 68097 && code <= 68099) return Extend;
        if (code >= 68101 && code <= 68102) return Extend;
        if (code >= 68108 && code <= 68111) return Extend;
        if (code >= 68152 && code <= 68154) return Extend;
        if (code >= 68325 && code <= 68326) return Extend;
        if (code >= 69688 && code <= 69702) return Extend;
        if (code >= 69759 && code <= 69761) return Extend;
        if (code >= 69808 && code <= 69810) return Extend;
        if (code >= 69811 && code <= 69814) return Extend;
        if (code >= 69815 && code <= 69816) return Extend;
        if (code >= 69817 && code <= 69818) return Extend;
        if (code >= 69888 && code <= 69890) return Extend;
        if (code >= 69927 && code <= 69931) return Extend;
        if (code >= 69933 && code <= 69940) return Extend;
        if (code >= 70016 && code <= 70017) return Extend;
        if (code >= 70067 && code <= 70069) return Extend;
        if (code >= 70070 && code <= 70078) return Extend;
        if (code >= 70079 && code <= 70080) return Extend;
        if (code >= 70090 && code <= 70092) return Extend;
        if (code >= 70188 && code <= 70190) return Extend;
        if (code >= 70191 && code <= 70193) return Extend;
        if (code >= 70194 && code <= 70195) return Extend;
        if (code >= 70198 && code <= 70199) return Extend;
        if (code >= 70368 && code <= 70370) return Extend;
        if (code >= 70371 && code <= 70378) return Extend;
        if (code >= 70400 && code <= 70401) return Extend;
        if (code >= 70402 && code <= 70403) return Extend;
        if (code >= 70462 && code <= 70463) return Extend;
        if (code >= 70465 && code <= 70468) return Extend;
        if (code >= 70471 && code <= 70472) return Extend;
        if (code >= 70475 && code <= 70477) return Extend;
        if (code >= 70498 && code <= 70499) return Extend;
        if (code >= 70502 && code <= 70508) return Extend;
        if (code >= 70512 && code <= 70516) return Extend;
        if (code >= 70709 && code <= 70711) return Extend;
        if (code >= 70712 && code <= 70719) return Extend;
        if (code >= 70720 && code <= 70721) return Extend;
        if (code >= 70722 && code <= 70724) return Extend;
        if (code >= 70832 && code <= 70834) return Extend;
        if (code >= 70835 && code <= 70840) return Extend;
        if (code >= 70843 && code <= 70846) return Extend;
        if (code >= 70847 && code <= 70848) return Extend;
        if (code >= 70850 && code <= 70851) return Extend;
        if (code >= 71087 && code <= 71089) return Extend;
        if (code >= 71090 && code <= 71093) return Extend;
        if (code >= 71096 && code <= 71099) return Extend;
        if (code >= 71100 && code <= 71101) return Extend;
        if (code >= 71103 && code <= 71104) return Extend;
        if (code >= 71132 && code <= 71133) return Extend;
        if (code >= 71216 && code <= 71218) return Extend;
        if (code >= 71219 && code <= 71226) return Extend;
        if (code >= 71227 && code <= 71228) return Extend;
        if (code >= 71231 && code <= 71232) return Extend;
        if (code >= 71342 && code <= 71343) return Extend;
        if (code >= 71344 && code <= 71349) return Extend;
        if (code >= 71453 && code <= 71455) return Extend;
        if (code >= 71456 && code <= 71457) return Extend;
        if (code >= 71458 && code <= 71461) return Extend;
        if (code >= 71463 && code <= 71467) return Extend;
        if (code >= 72752 && code <= 72758) return Extend;
        if (code >= 72760 && code <= 72765) return Extend;
        if (code >= 72850 && code <= 72871) return Extend;
        if (code >= 72874 && code <= 72880) return Extend;
        if (code >= 72882 && code <= 72883) return Extend;
        if (code >= 72885 && code <= 72886) return Extend;
        if (code >= 92912 && code <= 92916) return Extend;
        if (code >= 92976 && code <= 92982) return Extend;
        if (code >= 94033 && code <= 94078) return Extend;
        if (code >= 94095 && code <= 94098) return Extend;
        if (code >= 113821 && code <= 113822) return Extend;
        if (code >= 119141 && code <= 119142) return Extend;
        if (code >= 119143 && code <= 119145) return Extend;
        if (code >= 119149 && code <= 119154) return Extend;
        if (code >= 119163 && code <= 119170) return Extend;
        if (code >= 119173 && code <= 119179) return Extend;
        if (code >= 119210 && code <= 119213) return Extend;
        if (code >= 119362 && code <= 119364) return Extend;
        if (code >= 121344 && code <= 121398) return Extend;
        if (code >= 121403 && code <= 121452) return Extend;
        if (code >= 121499 && code <= 121503) return Extend;
        if (code >= 121505 && code <= 121519) return Extend;
        if (code >= 122880 && code <= 122886) return Extend;
        if (code >= 122888 && code <= 122904) return Extend;
        if (code >= 122907 && code <= 122913) return Extend;
        if (code >= 122915 && code <= 122916) return Extend;
        if (code >= 122918 && code <= 122922) return Extend;
        if (code >= 125136 && code <= 125142) return Extend;
        if (code >= 125252 && code <= 125258) return Extend;
        if (code >= 917536 && code <= 917631) return Extend;
        if (code >= 917760 && code <= 917999) return Extend;
        if (code >= 1536 && code <= 1541) return Format;
        if (code >= 8206 && code <= 8207) return Format;
        if (code >= 8234 && code <= 8238) return Format;
        if (code >= 8288 && code <= 8292) return Format;
        if (code >= 8294 && code <= 8303) return Format;
        if (code >= 65529 && code <= 65531) return Format;
        if (code >= 113824 && code <= 113827) return Format;
        if (code >= 119155 && code <= 119162) return Format;
        if (code >= 11 && code <= 12) return Sp;
        if (code >= 8192 && code <= 8202) return Sp;
        if (code >= 97 && code <= 122) return Lower;
        if (code >= 223 && code <= 246) return Lower;
        if (code >= 248 && code <= 255) return Lower;
        if (code >= 311 && code <= 312) return Lower;
        if (code >= 328 && code <= 329) return Lower;
        if (code >= 382 && code <= 384) return Lower;
        if (code >= 396 && code <= 397) return Lower;
        if (code >= 409 && code <= 411) return Lower;
        if (code >= 426 && code <= 427) return Lower;
        if (code >= 441 && code <= 442) return Lower;
        if (code >= 445 && code <= 447) return Lower;
        if (code >= 476 && code <= 477) return Lower;
        if (code >= 495 && code <= 496) return Lower;
        if (code >= 563 && code <= 569) return Lower;
        if (code >= 575 && code <= 576) return Lower;
        if (code >= 591 && code <= 659) return Lower;
        if (code >= 661 && code <= 687) return Lower;
        if (code >= 688 && code <= 696) return Lower;
        if (code >= 704 && code <= 705) return Lower;
        if (code >= 736 && code <= 740) return Lower;
        if (code >= 891 && code <= 893) return Lower;
        if (code >= 940 && code <= 974) return Lower;
        if (code >= 976 && code <= 977) return Lower;
        if (code >= 981 && code <= 983) return Lower;
        if (code >= 1007 && code <= 1011) return Lower;
        if (code >= 1019 && code <= 1020) return Lower;
        if (code >= 1072 && code <= 1119) return Lower;
        if (code >= 1230 && code <= 1231) return Lower;
        if (code >= 1377 && code <= 1415) return Lower;
        if (code >= 5112 && code <= 5117) return Lower;
        if (code >= 7296 && code <= 7304) return Lower;
        if (code >= 7424 && code <= 7467) return Lower;
        if (code >= 7468 && code <= 7530) return Lower;
        if (code >= 7531 && code <= 7543) return Lower;
        if (code >= 7545 && code <= 7578) return Lower;
        if (code >= 7579 && code <= 7615) return Lower;
        if (code >= 7829 && code <= 7837) return Lower;
        if (code >= 7935 && code <= 7943) return Lower;
        if (code >= 7952 && code <= 7957) return Lower;
        if (code >= 7968 && code <= 7975) return Lower;
        if (code >= 7984 && code <= 7991) return Lower;
        if (code >= 8000 && code <= 8005) return Lower;
        if (code >= 8016 && code <= 8023) return Lower;
        if (code >= 8032 && code <= 8039) return Lower;
        if (code >= 8048 && code <= 8061) return Lower;
        if (code >= 8064 && code <= 8071) return Lower;
        if (code >= 8080 && code <= 8087) return Lower;
        if (code >= 8096 && code <= 8103) return Lower;
        if (code >= 8112 && code <= 8116) return Lower;
        if (code >= 8118 && code <= 8119) return Lower;
        if (code >= 8130 && code <= 8132) return Lower;
        if (code >= 8134 && code <= 8135) return Lower;
        if (code >= 8144 && code <= 8147) return Lower;
        if (code >= 8150 && code <= 8151) return Lower;
        if (code >= 8160 && code <= 8167) return Lower;
        if (code >= 8178 && code <= 8180) return Lower;
        if (code >= 8182 && code <= 8183) return Lower;
        if (code >= 8336 && code <= 8348) return Lower;
        if (code >= 8462 && code <= 8463) return Lower;
        if (code >= 8508 && code <= 8509) return Lower;
        if (code >= 8518 && code <= 8521) return Lower;
        if (code >= 8560 && code <= 8575) return Lower;
        if (code >= 9424 && code <= 9449) return Lower;
        if (code >= 11312 && code <= 11358) return Lower;
        if (code >= 11365 && code <= 11366) return Lower;
        if (code >= 11379 && code <= 11380) return Lower;
        if (code >= 11382 && code <= 11387) return Lower;
        if (code >= 11388 && code <= 11389) return Lower;
        if (code >= 11491 && code <= 11492) return Lower;
        if (code >= 11520 && code <= 11557) return Lower;
        if (code >= 42652 && code <= 42653) return Lower;
        if (code >= 42799 && code <= 42801) return Lower;
        if (code >= 42865 && code <= 42872) return Lower;
        if (code >= 42899 && code <= 42901) return Lower;
        if (code >= 43000 && code <= 43001) return Lower;
        if (code >= 43824 && code <= 43866) return Lower;
        if (code >= 43868 && code <= 43871) return Lower;
        if (code >= 43872 && code <= 43877) return Lower;
        if (code >= 43888 && code <= 43967) return Lower;
        if (code >= 64256 && code <= 64262) return Lower;
        if (code >= 64275 && code <= 64279) return Lower;
        if (code >= 65345 && code <= 65370) return Lower;
        if (code >= 66600 && code <= 66639) return Lower;
        if (code >= 66776 && code <= 66811) return Lower;
        if (code >= 68800 && code <= 68850) return Lower;
        if (code >= 71872 && code <= 71903) return Lower;
        if (code >= 119834 && code <= 119859) return Lower;
        if (code >= 119886 && code <= 119892) return Lower;
        if (code >= 119894 && code <= 119911) return Lower;
        if (code >= 119938 && code <= 119963) return Lower;
        if (code >= 119990 && code <= 119993) return Lower;
        if (code >= 119997 && code <= 120003) return Lower;
        if (code >= 120005 && code <= 120015) return Lower;
        if (code >= 120042 && code <= 120067) return Lower;
        if (code >= 120094 && code <= 120119) return Lower;
        if (code >= 120146 && code <= 120171) return Lower;
        if (code >= 120198 && code <= 120223) return Lower;
        if (code >= 120250 && code <= 120275) return Lower;
        if (code >= 120302 && code <= 120327) return Lower;
        if (code >= 120354 && code <= 120379) return Lower;
        if (code >= 120406 && code <= 120431) return Lower;
        if (code >= 120458 && code <= 120485) return Lower;
        if (code >= 120514 && code <= 120538) return Lower;
        if (code >= 120540 && code <= 120545) return Lower;
        if (code >= 120572 && code <= 120596) return Lower;
        if (code >= 120598 && code <= 120603) return Lower;
        if (code >= 120630 && code <= 120654) return Lower;
        if (code >= 120656 && code <= 120661) return Lower;
        if (code >= 120688 && code <= 120712) return Lower;
        if (code >= 120714 && code <= 120719) return Lower;
        if (code >= 120746 && code <= 120770) return Lower;
        if (code >= 120772 && code <= 120777) return Lower;
        if (code >= 125218 && code <= 125251) return Lower;
        if (code >= 65 && code <= 90) return Upper;
        if (code >= 192 && code <= 214) return Upper;
        if (code >= 216 && code <= 222) return Upper;
        if (code >= 376 && code <= 377) return Upper;
        if (code >= 385 && code <= 386) return Upper;
        if (code >= 390 && code <= 391) return Upper;
        if (code >= 393 && code <= 395) return Upper;
        if (code >= 398 && code <= 401) return Upper;
        if (code >= 403 && code <= 404) return Upper;
        if (code >= 406 && code <= 408) return Upper;
        if (code >= 412 && code <= 413) return Upper;
        if (code >= 415 && code <= 416) return Upper;
        if (code >= 422 && code <= 423) return Upper;
        if (code >= 430 && code <= 431) return Upper;
        if (code >= 433 && code <= 435) return Upper;
        if (code >= 439 && code <= 440) return Upper;
        if (code >= 452 && code <= 453) return Upper;
        if (code >= 455 && code <= 456) return Upper;
        if (code >= 458 && code <= 459) return Upper;
        if (code >= 497 && code <= 498) return Upper;
        if (code >= 502 && code <= 504) return Upper;
        if (code >= 570 && code <= 571) return Upper;
        if (code >= 573 && code <= 574) return Upper;
        if (code >= 579 && code <= 582) return Upper;
        if (code >= 904 && code <= 906) return Upper;
        if (code >= 910 && code <= 911) return Upper;
        if (code >= 913 && code <= 929) return Upper;
        if (code >= 931 && code <= 939) return Upper;
        if (code >= 978 && code <= 980) return Upper;
        if (code >= 1017 && code <= 1018) return Upper;
        if (code >= 1021 && code <= 1071) return Upper;
        if (code >= 1216 && code <= 1217) return Upper;
        if (code >= 1329 && code <= 1366) return Upper;
        if (code >= 4256 && code <= 4293) return Upper;
        if (code >= 5024 && code <= 5109) return Upper;
        if (code >= 7944 && code <= 7951) return Upper;
        if (code >= 7960 && code <= 7965) return Upper;
        if (code >= 7976 && code <= 7983) return Upper;
        if (code >= 7992 && code <= 7999) return Upper;
        if (code >= 8008 && code <= 8013) return Upper;
        if (code >= 8040 && code <= 8047) return Upper;
        if (code >= 8072 && code <= 8079) return Upper;
        if (code >= 8088 && code <= 8095) return Upper;
        if (code >= 8104 && code <= 8111) return Upper;
        if (code >= 8120 && code <= 8124) return Upper;
        if (code >= 8136 && code <= 8140) return Upper;
        if (code >= 8152 && code <= 8155) return Upper;
        if (code >= 8168 && code <= 8172) return Upper;
        if (code >= 8184 && code <= 8188) return Upper;
        if (code >= 8459 && code <= 8461) return Upper;
        if (code >= 8464 && code <= 8466) return Upper;
        if (code >= 8473 && code <= 8477) return Upper;
        if (code >= 8490 && code <= 8493) return Upper;
        if (code >= 8496 && code <= 8499) return Upper;
        if (code >= 8510 && code <= 8511) return Upper;
        if (code >= 8544 && code <= 8559) return Upper;
        if (code >= 9398 && code <= 9423) return Upper;
        if (code >= 11264 && code <= 11310) return Upper;
        if (code >= 11362 && code <= 11364) return Upper;
        if (code >= 11373 && code <= 11376) return Upper;
        if (code >= 11390 && code <= 11392) return Upper;
        if (code >= 42877 && code <= 42878) return Upper;
        if (code >= 42922 && code <= 42926) return Upper;
        if (code >= 42928 && code <= 42932) return Upper;
        if (code >= 65313 && code <= 65338) return Upper;
        if (code >= 66560 && code <= 66599) return Upper;
        if (code >= 66736 && code <= 66771) return Upper;
        if (code >= 68736 && code <= 68786) return Upper;
        if (code >= 71840 && code <= 71871) return Upper;
        if (code >= 119808 && code <= 119833) return Upper;
        if (code >= 119860 && code <= 119885) return Upper;
        if (code >= 119912 && code <= 119937) return Upper;
        if (code >= 119966 && code <= 119967) return Upper;
        if (code >= 119973 && code <= 119974) return Upper;
        if (code >= 119977 && code <= 119980) return Upper;
        if (code >= 119982 && code <= 119989) return Upper;
        if (code >= 120016 && code <= 120041) return Upper;
        if (code >= 120068 && code <= 120069) return Upper;
        if (code >= 120071 && code <= 120074) return Upper;
        if (code >= 120077 && code <= 120084) return Upper;
        if (code >= 120086 && code <= 120092) return Upper;
        if (code >= 120120 && code <= 120121) return Upper;
        if (code >= 120123 && code <= 120126) return Upper;
        if (code >= 120128 && code <= 120132) return Upper;
        if (code >= 120138 && code <= 120144) return Upper;
        if (code >= 120172 && code <= 120197) return Upper;
        if (code >= 120224 && code <= 120249) return Upper;
        if (code >= 120276 && code <= 120301) return Upper;
        if (code >= 120328 && code <= 120353) return Upper;
        if (code >= 120380 && code <= 120405) return Upper;
        if (code >= 120432 && code <= 120457) return Upper;
        if (code >= 120488 && code <= 120512) return Upper;
        if (code >= 120546 && code <= 120570) return Upper;
        if (code >= 120604 && code <= 120628) return Upper;
        if (code >= 120662 && code <= 120686) return Upper;
        if (code >= 120720 && code <= 120744) return Upper;
        if (code >= 125184 && code <= 125217) return Upper;
        if (code >= 127280 && code <= 127305) return Upper;
        if (code >= 127312 && code <= 127337) return Upper;
        if (code >= 127344 && code <= 127369) return Upper;
        if (code >= 448 && code <= 451) return OLetter;
        if (code >= 697 && code <= 703) return OLetter;
        if (code >= 710 && code <= 721) return OLetter;
        if (code >= 1488 && code <= 1514) return OLetter;
        if (code >= 1520 && code <= 1522) return OLetter;
        if (code >= 1568 && code <= 1599) return OLetter;
        if (code >= 1601 && code <= 1610) return OLetter;
        if (code >= 1646 && code <= 1647) return OLetter;
        if (code >= 1649 && code <= 1747) return OLetter;
        if (code >= 1765 && code <= 1766) return OLetter;
        if (code >= 1774 && code <= 1775) return OLetter;
        if (code >= 1786 && code <= 1788) return OLetter;
        if (code >= 1810 && code <= 1839) return OLetter;
        if (code >= 1869 && code <= 1957) return OLetter;
        if (code >= 1994 && code <= 2026) return OLetter;
        if (code >= 2036 && code <= 2037) return OLetter;
        if (code >= 2048 && code <= 2069) return OLetter;
        if (code >= 2112 && code <= 2136) return OLetter;
        if (code >= 2208 && code <= 2228) return OLetter;
        if (code >= 2230 && code <= 2237) return OLetter;
        if (code >= 2308 && code <= 2361) return OLetter;
        if (code >= 2392 && code <= 2401) return OLetter;
        if (code >= 2418 && code <= 2432) return OLetter;
        if (code >= 2437 && code <= 2444) return OLetter;
        if (code >= 2447 && code <= 2448) return OLetter;
        if (code >= 2451 && code <= 2472) return OLetter;
        if (code >= 2474 && code <= 2480) return OLetter;
        if (code >= 2486 && code <= 2489) return OLetter;
        if (code >= 2524 && code <= 2525) return OLetter;
        if (code >= 2527 && code <= 2529) return OLetter;
        if (code >= 2544 && code <= 2545) return OLetter;
        if (code >= 2565 && code <= 2570) return OLetter;
        if (code >= 2575 && code <= 2576) return OLetter;
        if (code >= 2579 && code <= 2600) return OLetter;
        if (code >= 2602 && code <= 2608) return OLetter;
        if (code >= 2610 && code <= 2611) return OLetter;
        if (code >= 2613 && code <= 2614) return OLetter;
        if (code >= 2616 && code <= 2617) return OLetter;
        if (code >= 2649 && code <= 2652) return OLetter;
        if (code >= 2674 && code <= 2676) return OLetter;
        if (code >= 2693 && code <= 2701) return OLetter;
        if (code >= 2703 && code <= 2705) return OLetter;
        if (code >= 2707 && code <= 2728) return OLetter;
        if (code >= 2730 && code <= 2736) return OLetter;
        if (code >= 2738 && code <= 2739) return OLetter;
        if (code >= 2741 && code <= 2745) return OLetter;
        if (code >= 2784 && code <= 2785) return OLetter;
        if (code >= 2821 && code <= 2828) return OLetter;
        if (code >= 2831 && code <= 2832) return OLetter;
        if (code >= 2835 && code <= 2856) return OLetter;
        if (code >= 2858 && code <= 2864) return OLetter;
        if (code >= 2866 && code <= 2867) return OLetter;
        if (code >= 2869 && code <= 2873) return OLetter;
        if (code >= 2908 && code <= 2909) return OLetter;
        if (code >= 2911 && code <= 2913) return OLetter;
        if (code >= 2949 && code <= 2954) return OLetter;
        if (code >= 2958 && code <= 2960) return OLetter;
        if (code >= 2962 && code <= 2965) return OLetter;
        if (code >= 2969 && code <= 2970) return OLetter;
        if (code >= 2974 && code <= 2975) return OLetter;
        if (code >= 2979 && code <= 2980) return OLetter;
        if (code >= 2984 && code <= 2986) return OLetter;
        if (code >= 2990 && code <= 3001) return OLetter;
        if (code >= 3077 && code <= 3084) return OLetter;
        if (code >= 3086 && code <= 3088) return OLetter;
        if (code >= 3090 && code <= 3112) return OLetter;
        if (code >= 3114 && code <= 3129) return OLetter;
        if (code >= 3160 && code <= 3162) return OLetter;
        if (code >= 3168 && code <= 3169) return OLetter;
        if (code >= 3205 && code <= 3212) return OLetter;
        if (code >= 3214 && code <= 3216) return OLetter;
        if (code >= 3218 && code <= 3240) return OLetter;
        if (code >= 3242 && code <= 3251) return OLetter;
        if (code >= 3253 && code <= 3257) return OLetter;
        if (code >= 3296 && code <= 3297) return OLetter;
        if (code >= 3313 && code <= 3314) return OLetter;
        if (code >= 3333 && code <= 3340) return OLetter;
        if (code >= 3342 && code <= 3344) return OLetter;
        if (code >= 3346 && code <= 3386) return OLetter;
        if (code >= 3412 && code <= 3414) return OLetter;
        if (code >= 3423 && code <= 3425) return OLetter;
        if (code >= 3450 && code <= 3455) return OLetter;
        if (code >= 3461 && code <= 3478) return OLetter;
        if (code >= 3482 && code <= 3505) return OLetter;
        if (code >= 3507 && code <= 3515) return OLetter;
        if (code >= 3520 && code <= 3526) return OLetter;
        if (code >= 3585 && code <= 3632) return OLetter;
        if (code >= 3634 && code <= 3635) return OLetter;
        if (code >= 3648 && code <= 3653) return OLetter;
        if (code >= 3713 && code <= 3714) return OLetter;
        if (code >= 3719 && code <= 3720) return OLetter;
        if (code >= 3732 && code <= 3735) return OLetter;
        if (code >= 3737 && code <= 3743) return OLetter;
        if (code >= 3745 && code <= 3747) return OLetter;
        if (code >= 3754 && code <= 3755) return OLetter;
        if (code >= 3757 && code <= 3760) return OLetter;
        if (code >= 3762 && code <= 3763) return OLetter;
        if (code >= 3776 && code <= 3780) return OLetter;
        if (code >= 3804 && code <= 3807) return OLetter;
        if (code >= 3904 && code <= 3911) return OLetter;
        if (code >= 3913 && code <= 3948) return OLetter;
        if (code >= 3976 && code <= 3980) return OLetter;
        if (code >= 4096 && code <= 4138) return OLetter;
        if (code >= 4176 && code <= 4181) return OLetter;
        if (code >= 4186 && code <= 4189) return OLetter;
        if (code >= 4197 && code <= 4198) return OLetter;
        if (code >= 4206 && code <= 4208) return OLetter;
        if (code >= 4213 && code <= 4225) return OLetter;
        if (code >= 4304 && code <= 4346) return OLetter;
        if (code >= 4349 && code <= 4680) return OLetter;
        if (code >= 4682 && code <= 4685) return OLetter;
        if (code >= 4688 && code <= 4694) return OLetter;
        if (code >= 4698 && code <= 4701) return OLetter;
        if (code >= 4704 && code <= 4744) return OLetter;
        if (code >= 4746 && code <= 4749) return OLetter;
        if (code >= 4752 && code <= 4784) return OLetter;
        if (code >= 4786 && code <= 4789) return OLetter;
        if (code >= 4792 && code <= 4798) return OLetter;
        if (code >= 4802 && code <= 4805) return OLetter;
        if (code >= 4808 && code <= 4822) return OLetter;
        if (code >= 4824 && code <= 4880) return OLetter;
        if (code >= 4882 && code <= 4885) return OLetter;
        if (code >= 4888 && code <= 4954) return OLetter;
        if (code >= 4992 && code <= 5007) return OLetter;
        if (code >= 5121 && code <= 5740) return OLetter;
        if (code >= 5743 && code <= 5759) return OLetter;
        if (code >= 5761 && code <= 5786) return OLetter;
        if (code >= 5792 && code <= 5866) return OLetter;
        if (code >= 5870 && code <= 5872) return OLetter;
        if (code >= 5873 && code <= 5880) return OLetter;
        if (code >= 5888 && code <= 5900) return OLetter;
        if (code >= 5902 && code <= 5905) return OLetter;
        if (code >= 5920 && code <= 5937) return OLetter;
        if (code >= 5952 && code <= 5969) return OLetter;
        if (code >= 5984 && code <= 5996) return OLetter;
        if (code >= 5998 && code <= 6000) return OLetter;
        if (code >= 6016 && code <= 6067) return OLetter;
        if (code >= 6176 && code <= 6210) return OLetter;
        if (code >= 6212 && code <= 6263) return OLetter;
        if (code >= 6272 && code <= 6276) return OLetter;
        if (code >= 6279 && code <= 6312) return OLetter;
        if (code >= 6320 && code <= 6389) return OLetter;
        if (code >= 6400 && code <= 6430) return OLetter;
        if (code >= 6480 && code <= 6509) return OLetter;
        if (code >= 6512 && code <= 6516) return OLetter;
        if (code >= 6528 && code <= 6571) return OLetter;
        if (code >= 6576 && code <= 6601) return OLetter;
        if (code >= 6656 && code <= 6678) return OLetter;
        if (code >= 6688 && code <= 6740) return OLetter;
        if (code >= 6917 && code <= 6963) return OLetter;
        if (code >= 6981 && code <= 6987) return OLetter;
        if (code >= 7043 && code <= 7072) return OLetter;
        if (code >= 7086 && code <= 7087) return OLetter;
        if (code >= 7098 && code <= 7141) return OLetter;
        if (code >= 7168 && code <= 7203) return OLetter;
        if (code >= 7245 && code <= 7247) return OLetter;
        if (code >= 7258 && code <= 7287) return OLetter;
        if (code >= 7288 && code <= 7293) return OLetter;
        if (code >= 7401 && code <= 7404) return OLetter;
        if (code >= 7406 && code <= 7409) return OLetter;
        if (code >= 7413 && code <= 7414) return OLetter;
        if (code >= 8501 && code <= 8504) return OLetter;
        if (code >= 8576 && code <= 8578) return OLetter;
        if (code >= 8581 && code <= 8584) return OLetter;
        if (code >= 11568 && code <= 11623) return OLetter;
        if (code >= 11648 && code <= 11670) return OLetter;
        if (code >= 11680 && code <= 11686) return OLetter;
        if (code >= 11688 && code <= 11694) return OLetter;
        if (code >= 11696 && code <= 11702) return OLetter;
        if (code >= 11704 && code <= 11710) return OLetter;
        if (code >= 11712 && code <= 11718) return OLetter;
        if (code >= 11720 && code <= 11726) return OLetter;
        if (code >= 11728 && code <= 11734) return OLetter;
        if (code >= 11736 && code <= 11742) return OLetter;
        if (code >= 12321 && code <= 12329) return OLetter;
        if (code >= 12337 && code <= 12341) return OLetter;
        if (code >= 12344 && code <= 12346) return OLetter;
        if (code >= 12353 && code <= 12438) return OLetter;
        if (code >= 12445 && code <= 12446) return OLetter;
        if (code >= 12449 && code <= 12538) return OLetter;
        if (code >= 12540 && code <= 12542) return OLetter;
        if (code >= 12549 && code <= 12589) return OLetter;
        if (code >= 12593 && code <= 12686) return OLetter;
        if (code >= 12704 && code <= 12730) return OLetter;
        if (code >= 12784 && code <= 12799) return OLetter;
        if (code >= 13312 && code <= 19893) return OLetter;
        if (code >= 19968 && code <= 40917) return OLetter;
        if (code >= 40960 && code <= 40980) return OLetter;
        if (code >= 40982 && code <= 42124) return OLetter;
        if (code >= 42192 && code <= 42231) return OLetter;
        if (code >= 42232 && code <= 42237) return OLetter;
        if (code >= 42240 && code <= 42507) return OLetter;
        if (code >= 42512 && code <= 42527) return OLetter;
        if (code >= 42538 && code <= 42539) return OLetter;
        if (code >= 42656 && code <= 42725) return OLetter;
        if (code >= 42726 && code <= 42735) return OLetter;
        if (code >= 42775 && code <= 42783) return OLetter;
        if (code >= 43003 && code <= 43009) return OLetter;
        if (code >= 43011 && code <= 43013) return OLetter;
        if (code >= 43015 && code <= 43018) return OLetter;
        if (code >= 43020 && code <= 43042) return OLetter;
        if (code >= 43072 && code <= 43123) return OLetter;
        if (code >= 43138 && code <= 43187) return OLetter;
        if (code >= 43250 && code <= 43255) return OLetter;
        if (code >= 43274 && code <= 43301) return OLetter;
        if (code >= 43312 && code <= 43334) return OLetter;
        if (code >= 43360 && code <= 43388) return OLetter;
        if (code >= 43396 && code <= 43442) return OLetter;
        if (code >= 43488 && code <= 43492) return OLetter;
        if (code >= 43495 && code <= 43503) return OLetter;
        if (code >= 43514 && code <= 43518) return OLetter;
        if (code >= 43520 && code <= 43560) return OLetter;
        if (code >= 43584 && code <= 43586) return OLetter;
        if (code >= 43588 && code <= 43595) return OLetter;
        if (code >= 43616 && code <= 43631) return OLetter;
        if (code >= 43633 && code <= 43638) return OLetter;
        if (code >= 43646 && code <= 43695) return OLetter;
        if (code >= 43701 && code <= 43702) return OLetter;
        if (code >= 43705 && code <= 43709) return OLetter;
        if (code >= 43739 && code <= 43740) return OLetter;
        if (code >= 43744 && code <= 43754) return OLetter;
        if (code >= 43763 && code <= 43764) return OLetter;
        if (code >= 43777 && code <= 43782) return OLetter;
        if (code >= 43785 && code <= 43790) return OLetter;
        if (code >= 43793 && code <= 43798) return OLetter;
        if (code >= 43808 && code <= 43814) return OLetter;
        if (code >= 43816 && code <= 43822) return OLetter;
        if (code >= 43968 && code <= 44002) return OLetter;
        if (code >= 44032 && code <= 55203) return OLetter;
        if (code >= 55216 && code <= 55238) return OLetter;
        if (code >= 55243 && code <= 55291) return OLetter;
        if (code >= 63744 && code <= 64109) return OLetter;
        if (code >= 64112 && code <= 64217) return OLetter;
        if (code >= 64287 && code <= 64296) return OLetter;
        if (code >= 64298 && code <= 64310) return OLetter;
        if (code >= 64312 && code <= 64316) return OLetter;
        if (code >= 64320 && code <= 64321) return OLetter;
        if (code >= 64323 && code <= 64324) return OLetter;
        if (code >= 64326 && code <= 64433) return OLetter;
        if (code >= 64467 && code <= 64829) return OLetter;
        if (code >= 64848 && code <= 64911) return OLetter;
        if (code >= 64914 && code <= 64967) return OLetter;
        if (code >= 65008 && code <= 65019) return OLetter;
        if (code >= 65136 && code <= 65140) return OLetter;
        if (code >= 65142 && code <= 65276) return OLetter;
        if (code >= 65382 && code <= 65391) return OLetter;
        if (code >= 65393 && code <= 65437) return OLetter;
        if (code >= 65440 && code <= 65470) return OLetter;
        if (code >= 65474 && code <= 65479) return OLetter;
        if (code >= 65482 && code <= 65487) return OLetter;
        if (code >= 65490 && code <= 65495) return OLetter;
        if (code >= 65498 && code <= 65500) return OLetter;
        if (code >= 65536 && code <= 65547) return OLetter;
        if (code >= 65549 && code <= 65574) return OLetter;
        if (code >= 65576 && code <= 65594) return OLetter;
        if (code >= 65596 && code <= 65597) return OLetter;
        if (code >= 65599 && code <= 65613) return OLetter;
        if (code >= 65616 && code <= 65629) return OLetter;
        if (code >= 65664 && code <= 65786) return OLetter;
        if (code >= 65856 && code <= 65908) return OLetter;
        if (code >= 66176 && code <= 66204) return OLetter;
        if (code >= 66208 && code <= 66256) return OLetter;
        if (code >= 66304 && code <= 66335) return OLetter;
        if (code >= 66352 && code <= 66368) return OLetter;
        if (code >= 66370 && code <= 66377) return OLetter;
        if (code >= 66384 && code <= 66421) return OLetter;
        if (code >= 66432 && code <= 66461) return OLetter;
        if (code >= 66464 && code <= 66499) return OLetter;
        if (code >= 66504 && code <= 66511) return OLetter;
        if (code >= 66513 && code <= 66517) return OLetter;
        if (code >= 66640 && code <= 66717) return OLetter;
        if (code >= 66816 && code <= 66855) return OLetter;
        if (code >= 66864 && code <= 66915) return OLetter;
        if (code >= 67072 && code <= 67382) return OLetter;
        if (code >= 67392 && code <= 67413) return OLetter;
        if (code >= 67424 && code <= 67431) return OLetter;
        if (code >= 67584 && code <= 67589) return OLetter;
        if (code >= 67594 && code <= 67637) return OLetter;
        if (code >= 67639 && code <= 67640) return OLetter;
        if (code >= 67647 && code <= 67669) return OLetter;
        if (code >= 67680 && code <= 67702) return OLetter;
        if (code >= 67712 && code <= 67742) return OLetter;
        if (code >= 67808 && code <= 67826) return OLetter;
        if (code >= 67828 && code <= 67829) return OLetter;
        if (code >= 67840 && code <= 67861) return OLetter;
        if (code >= 67872 && code <= 67897) return OLetter;
        if (code >= 67968 && code <= 68023) return OLetter;
        if (code >= 68030 && code <= 68031) return OLetter;
        if (code >= 68112 && code <= 68115) return OLetter;
        if (code >= 68117 && code <= 68119) return OLetter;
        if (code >= 68121 && code <= 68147) return OLetter;
        if (code >= 68192 && code <= 68220) return OLetter;
        if (code >= 68224 && code <= 68252) return OLetter;
        if (code >= 68288 && code <= 68295) return OLetter;
        if (code >= 68297 && code <= 68324) return OLetter;
        if (code >= 68352 && code <= 68405) return OLetter;
        if (code >= 68416 && code <= 68437) return OLetter;
        if (code >= 68448 && code <= 68466) return OLetter;
        if (code >= 68480 && code <= 68497) return OLetter;
        if (code >= 68608 && code <= 68680) return OLetter;
        if (code >= 69635 && code <= 69687) return OLetter;
        if (code >= 69763 && code <= 69807) return OLetter;
        if (code >= 69840 && code <= 69864) return OLetter;
        if (code >= 69891 && code <= 69926) return OLetter;
        if (code >= 69968 && code <= 70002) return OLetter;
        if (code >= 70019 && code <= 70066) return OLetter;
        if (code >= 70081 && code <= 70084) return OLetter;
        if (code >= 70144 && code <= 70161) return OLetter;
        if (code >= 70163 && code <= 70187) return OLetter;
        if (code >= 70272 && code <= 70278) return OLetter;
        if (code >= 70282 && code <= 70285) return OLetter;
        if (code >= 70287 && code <= 70301) return OLetter;
        if (code >= 70303 && code <= 70312) return OLetter;
        if (code >= 70320 && code <= 70366) return OLetter;
        if (code >= 70405 && code <= 70412) return OLetter;
        if (code >= 70415 && code <= 70416) return OLetter;
        if (code >= 70419 && code <= 70440) return OLetter;
        if (code >= 70442 && code <= 70448) return OLetter;
        if (code >= 70450 && code <= 70451) return OLetter;
        if (code >= 70453 && code <= 70457) return OLetter;
        if (code >= 70493 && code <= 70497) return OLetter;
        if (code >= 70656 && code <= 70708) return OLetter;
        if (code >= 70727 && code <= 70730) return OLetter;
        if (code >= 70784 && code <= 70831) return OLetter;
        if (code >= 70852 && code <= 70853) return OLetter;
        if (code >= 71040 && code <= 71086) return OLetter;
        if (code >= 71128 && code <= 71131) return OLetter;
        if (code >= 71168 && code <= 71215) return OLetter;
        if (code >= 71296 && code <= 71338) return OLetter;
        if (code >= 71424 && code <= 71449) return OLetter;
        if (code >= 72384 && code <= 72440) return OLetter;
        if (code >= 72704 && code <= 72712) return OLetter;
        if (code >= 72714 && code <= 72750) return OLetter;
        if (code >= 72818 && code <= 72847) return OLetter;
        if (code >= 73728 && code <= 74649) return OLetter;
        if (code >= 74752 && code <= 74862) return OLetter;
        if (code >= 74880 && code <= 75075) return OLetter;
        if (code >= 77824 && code <= 78894) return OLetter;
        if (code >= 82944 && code <= 83526) return OLetter;
        if (code >= 92160 && code <= 92728) return OLetter;
        if (code >= 92736 && code <= 92766) return OLetter;
        if (code >= 92880 && code <= 92909) return OLetter;
        if (code >= 92928 && code <= 92975) return OLetter;
        if (code >= 92992 && code <= 92995) return OLetter;
        if (code >= 93027 && code <= 93047) return OLetter;
        if (code >= 93053 && code <= 93071) return OLetter;
        if (code >= 93952 && code <= 94020) return OLetter;
        if (code >= 94099 && code <= 94111) return OLetter;
        if (code >= 94208 && code <= 100332) return OLetter;
        if (code >= 100352 && code <= 101106) return OLetter;
        if (code >= 110592 && code <= 110593) return OLetter;
        if (code >= 113664 && code <= 113770) return OLetter;
        if (code >= 113776 && code <= 113788) return OLetter;
        if (code >= 113792 && code <= 113800) return OLetter;
        if (code >= 113808 && code <= 113817) return OLetter;
        if (code >= 124928 && code <= 125124) return OLetter;
        if (code >= 126464 && code <= 126467) return OLetter;
        if (code >= 126469 && code <= 126495) return OLetter;
        if (code >= 126497 && code <= 126498) return OLetter;
        if (code >= 126505 && code <= 126514) return OLetter;
        if (code >= 126516 && code <= 126519) return OLetter;
        if (code >= 126541 && code <= 126543) return OLetter;
        if (code >= 126545 && code <= 126546) return OLetter;
        if (code >= 126561 && code <= 126562) return OLetter;
        if (code >= 126567 && code <= 126570) return OLetter;
        if (code >= 126572 && code <= 126578) return OLetter;
        if (code >= 126580 && code <= 126583) return OLetter;
        if (code >= 126585 && code <= 126588) return OLetter;
        if (code >= 126592 && code <= 126601) return OLetter;
        if (code >= 126603 && code <= 126619) return OLetter;
        if (code >= 126625 && code <= 126627) return OLetter;
        if (code >= 126629 && code <= 126633) return OLetter;
        if (code >= 126635 && code <= 126651) return OLetter;
        if (code >= 131072 && code <= 173782) return OLetter;
        if (code >= 173824 && code <= 177972) return OLetter;
        if (code >= 177984 && code <= 178205) return OLetter;
        if (code >= 178208 && code <= 183969) return OLetter;
        if (code >= 194560 && code <= 195101) return OLetter;
        if (code >= 48 && code <= 57) return Numeric;
        if (code >= 1632 && code <= 1641) return Numeric;
        if (code >= 1643 && code <= 1644) return Numeric;
        if (code >= 1776 && code <= 1785) return Numeric;
        if (code >= 1984 && code <= 1993) return Numeric;
        if (code >= 2406 && code <= 2415) return Numeric;
        if (code >= 2534 && code <= 2543) return Numeric;
        if (code >= 2662 && code <= 2671) return Numeric;
        if (code >= 2790 && code <= 2799) return Numeric;
        if (code >= 2918 && code <= 2927) return Numeric;
        if (code >= 3046 && code <= 3055) return Numeric;
        if (code >= 3174 && code <= 3183) return Numeric;
        if (code >= 3302 && code <= 3311) return Numeric;
        if (code >= 3430 && code <= 3439) return Numeric;
        if (code >= 3558 && code <= 3567) return Numeric;
        if (code >= 3664 && code <= 3673) return Numeric;
        if (code >= 3792 && code <= 3801) return Numeric;
        if (code >= 3872 && code <= 3881) return Numeric;
        if (code >= 4160 && code <= 4169) return Numeric;
        if (code >= 4240 && code <= 4249) return Numeric;
        if (code >= 6112 && code <= 6121) return Numeric;
        if (code >= 6160 && code <= 6169) return Numeric;
        if (code >= 6470 && code <= 6479) return Numeric;
        if (code >= 6608 && code <= 6617) return Numeric;
        if (code >= 6784 && code <= 6793) return Numeric;
        if (code >= 6800 && code <= 6809) return Numeric;
        if (code >= 6992 && code <= 7001) return Numeric;
        if (code >= 7088 && code <= 7097) return Numeric;
        if (code >= 7232 && code <= 7241) return Numeric;
        if (code >= 7248 && code <= 7257) return Numeric;
        if (code >= 42528 && code <= 42537) return Numeric;
        if (code >= 43216 && code <= 43225) return Numeric;
        if (code >= 43264 && code <= 43273) return Numeric;
        if (code >= 43472 && code <= 43481) return Numeric;
        if (code >= 43504 && code <= 43513) return Numeric;
        if (code >= 43600 && code <= 43609) return Numeric;
        if (code >= 44016 && code <= 44025) return Numeric;
        if (code >= 66720 && code <= 66729) return Numeric;
        if (code >= 69734 && code <= 69743) return Numeric;
        if (code >= 69872 && code <= 69881) return Numeric;
        if (code >= 69942 && code <= 69951) return Numeric;
        if (code >= 70096 && code <= 70105) return Numeric;
        if (code >= 70384 && code <= 70393) return Numeric;
        if (code >= 70736 && code <= 70745) return Numeric;
        if (code >= 70864 && code <= 70873) return Numeric;
        if (code >= 71248 && code <= 71257) return Numeric;
        if (code >= 71360 && code <= 71369) return Numeric;
        if (code >= 71472 && code <= 71481) return Numeric;
        if (code >= 71904 && code <= 71913) return Numeric;
        if (code >= 72784 && code <= 72793) return Numeric;
        if (code >= 92768 && code <= 92777) return Numeric;
        if (code >= 93008 && code <= 93017) return Numeric;
        if (code >= 120782 && code <= 120831) return Numeric;
        if (code >= 125264 && code <= 125273) return Numeric;
        if (code >= 1792 && code <= 1794) return STerm;
        if (code >= 2404 && code <= 2405) return STerm;
        if (code >= 4170 && code <= 4171) return STerm;
        if (code >= 4967 && code <= 4968) return STerm;
        if (code >= 5941 && code <= 5942) return STerm;
        if (code >= 6468 && code <= 6469) return STerm;
        if (code >= 6824 && code <= 6827) return STerm;
        if (code >= 7002 && code <= 7003) return STerm;
        if (code >= 7006 && code <= 7007) return STerm;
        if (code >= 7227 && code <= 7228) return STerm;
        if (code >= 7294 && code <= 7295) return STerm;
        if (code >= 8252 && code <= 8253) return STerm;
        if (code >= 8263 && code <= 8265) return STerm;
        if (code >= 42510 && code <= 42511) return STerm;
        if (code >= 43126 && code <= 43127) return STerm;
        if (code >= 43214 && code <= 43215) return STerm;
        if (code >= 43464 && code <= 43465) return STerm;
        if (code >= 43613 && code <= 43615) return STerm;
        if (code >= 43760 && code <= 43761) return STerm;
        if (code >= 65110 && code <= 65111) return STerm;
        if (code >= 68182 && code <= 68183) return STerm;
        if (code >= 69703 && code <= 69704) return STerm;
        if (code >= 69822 && code <= 69825) return STerm;
        if (code >= 69953 && code <= 69955) return STerm;
        if (code >= 70085 && code <= 70086) return STerm;
        if (code >= 70110 && code <= 70111) return STerm;
        if (code >= 70200 && code <= 70201) return STerm;
        if (code >= 70203 && code <= 70204) return STerm;
        if (code >= 70731 && code <= 70732) return STerm;
        if (code >= 71106 && code <= 71107) return STerm;
        if (code >= 71113 && code <= 71127) return STerm;
        if (code >= 71233 && code <= 71234) return STerm;
        if (code >= 71484 && code <= 71486) return STerm;
        if (code >= 72769 && code <= 72770) return STerm;
        if (code >= 92782 && code <= 92783) return STerm;
        if (code >= 92983 && code <= 92984) return STerm;
        if (code >= 8219 && code <= 8220) return Close;
        if (code >= 10075 && code <= 10080) return Close;
        if (code >= 11776 && code <= 11777) return Close;
        if (code >= 11782 && code <= 11784) return Close;
        if (code >= 12318 && code <= 12319) return Close;
        if (code >= 128630 && code <= 128632) return Close;
        if (code >= 1548 && code <= 1549) return SContinue;
        if (code >= 8211 && code <= 8212) return SContinue;
        if (code >= 65040 && code <= 65041) return SContinue;
        if (code >= 65073 && code <= 65074) return SContinue;
        if (code >= 65104 && code <= 65105) return SContinue;
        return m.exists(code) ? m.get(code) : Other;
    }
}
enum SentenceValuesEnum {
    Format;
    ATerm;
    STerm;
    Other;
    Sp;
    Lower;
    LF;
    Close;
    CR;
    Sep;
    Numeric;
    Extend;
    Upper;
    OLetter;
    SContinue;
}
