package unicode.tr29.internal;
//Autogenerated, do not edit
class WordValues {
        static var m = [
        34 => Double_Quote,
        39 => Single_Quote,
        64285 => Hebrew_Letter,
        64318 => Hebrew_Letter,
        13 => CR,
        10 => LF,
        133 => Newline,
        8232 => Newline,
        8233 => Newline,
        1471 => Extend,
        1479 => Extend,
        1648 => Extend,
        1809 => Extend,
        2307 => Extend,
        2362 => Extend,
        2363 => Extend,
        2364 => Extend,
        2381 => Extend,
        2433 => Extend,
        2492 => Extend,
        2509 => Extend,
        2519 => Extend,
        2563 => Extend,
        2620 => Extend,
        2641 => Extend,
        2677 => Extend,
        2691 => Extend,
        2748 => Extend,
        2761 => Extend,
        2765 => Extend,
        2817 => Extend,
        2876 => Extend,
        2878 => Extend,
        2879 => Extend,
        2880 => Extend,
        2893 => Extend,
        2902 => Extend,
        2903 => Extend,
        2946 => Extend,
        3008 => Extend,
        3021 => Extend,
        3031 => Extend,
        3072 => Extend,
        3201 => Extend,
        3260 => Extend,
        3262 => Extend,
        3263 => Extend,
        3270 => Extend,
        3329 => Extend,
        3405 => Extend,
        3415 => Extend,
        3530 => Extend,
        3542 => Extend,
        3633 => Extend,
        3761 => Extend,
        3893 => Extend,
        3895 => Extend,
        3897 => Extend,
        3967 => Extend,
        4038 => Extend,
        4145 => Extend,
        4152 => Extend,
        4226 => Extend,
        4237 => Extend,
        4239 => Extend,
        4253 => Extend,
        6070 => Extend,
        6086 => Extend,
        6109 => Extend,
        6313 => Extend,
        6450 => Extend,
        6683 => Extend,
        6741 => Extend,
        6742 => Extend,
        6743 => Extend,
        6752 => Extend,
        6753 => Extend,
        6754 => Extend,
        6783 => Extend,
        6846 => Extend,
        6916 => Extend,
        6964 => Extend,
        6965 => Extend,
        6971 => Extend,
        6972 => Extend,
        6978 => Extend,
        7042 => Extend,
        7073 => Extend,
        7082 => Extend,
        7142 => Extend,
        7143 => Extend,
        7149 => Extend,
        7150 => Extend,
        7393 => Extend,
        7405 => Extend,
        7412 => Extend,
        8204 => Extend,
        8417 => Extend,
        11647 => Extend,
        42607 => Extend,
        43010 => Extend,
        43014 => Extend,
        43019 => Extend,
        43047 => Extend,
        43395 => Extend,
        43443 => Extend,
        43452 => Extend,
        43493 => Extend,
        43587 => Extend,
        43596 => Extend,
        43597 => Extend,
        43643 => Extend,
        43644 => Extend,
        43645 => Extend,
        43696 => Extend,
        43713 => Extend,
        43755 => Extend,
        43765 => Extend,
        43766 => Extend,
        44005 => Extend,
        44008 => Extend,
        44012 => Extend,
        44013 => Extend,
        64286 => Extend,
        66045 => Extend,
        66272 => Extend,
        68159 => Extend,
        69632 => Extend,
        69633 => Extend,
        69634 => Extend,
        69762 => Extend,
        69932 => Extend,
        70003 => Extend,
        70018 => Extend,
        70196 => Extend,
        70197 => Extend,
        70206 => Extend,
        70367 => Extend,
        70460 => Extend,
        70464 => Extend,
        70487 => Extend,
        70725 => Extend,
        70726 => Extend,
        70841 => Extend,
        70842 => Extend,
        70849 => Extend,
        71102 => Extend,
        71229 => Extend,
        71230 => Extend,
        71339 => Extend,
        71340 => Extend,
        71341 => Extend,
        71350 => Extend,
        71351 => Extend,
        71462 => Extend,
        72751 => Extend,
        72766 => Extend,
        72767 => Extend,
        72873 => Extend,
        72881 => Extend,
        72884 => Extend,
        121461 => Extend,
        121476 => Extend,
        173 => Format,
        1564 => Format,
        1757 => Format,
        1807 => Format,
        2274 => Format,
        6158 => Format,
        65279 => Format,
        69821 => Format,
        917505 => Format,
        12448 => Katakana,
        12543 => Katakana,
        65392 => Katakana,
        110592 => Katakana,
        170 => ALetter,
        181 => ALetter,
        186 => ALetter,
        443 => ALetter,
        660 => ALetter,
        748 => ALetter,
        750 => ALetter,
        884 => ALetter,
        890 => ALetter,
        895 => ALetter,
        902 => ALetter,
        908 => ALetter,
        1369 => ALetter,
        1523 => ALetter,
        1600 => ALetter,
        1749 => ALetter,
        1791 => ALetter,
        1808 => ALetter,
        1969 => ALetter,
        2042 => ALetter,
        2074 => ALetter,
        2084 => ALetter,
        2088 => ALetter,
        2365 => ALetter,
        2384 => ALetter,
        2417 => ALetter,
        2482 => ALetter,
        2493 => ALetter,
        2510 => ALetter,
        2654 => ALetter,
        2749 => ALetter,
        2768 => ALetter,
        2809 => ALetter,
        2877 => ALetter,
        2929 => ALetter,
        2947 => ALetter,
        2972 => ALetter,
        3024 => ALetter,
        3133 => ALetter,
        3200 => ALetter,
        3261 => ALetter,
        3294 => ALetter,
        3389 => ALetter,
        3406 => ALetter,
        3517 => ALetter,
        3840 => ALetter,
        4295 => ALetter,
        4301 => ALetter,
        4348 => ALetter,
        4696 => ALetter,
        4800 => ALetter,
        6211 => ALetter,
        6314 => ALetter,
        7544 => ALetter,
        8025 => ALetter,
        8027 => ALetter,
        8029 => ALetter,
        8126 => ALetter,
        8305 => ALetter,
        8319 => ALetter,
        8450 => ALetter,
        8455 => ALetter,
        8469 => ALetter,
        8484 => ALetter,
        8486 => ALetter,
        8488 => ALetter,
        8505 => ALetter,
        8526 => ALetter,
        11559 => ALetter,
        11565 => ALetter,
        11631 => ALetter,
        11823 => ALetter,
        12293 => ALetter,
        12347 => ALetter,
        12348 => ALetter,
        40981 => ALetter,
        42508 => ALetter,
        42606 => ALetter,
        42623 => ALetter,
        42864 => ALetter,
        42888 => ALetter,
        42895 => ALetter,
        42999 => ALetter,
        43002 => ALetter,
        43259 => ALetter,
        43261 => ALetter,
        43471 => ALetter,
        43762 => ALetter,
        66369 => ALetter,
        66378 => ALetter,
        67592 => ALetter,
        67644 => ALetter,
        68096 => ALetter,
        70006 => ALetter,
        70106 => ALetter,
        70108 => ALetter,
        70280 => ALetter,
        70461 => ALetter,
        70480 => ALetter,
        70855 => ALetter,
        71236 => ALetter,
        71935 => ALetter,
        72768 => ALetter,
        94032 => ALetter,
        94176 => ALetter,
        119970 => ALetter,
        119995 => ALetter,
        120134 => ALetter,
        126500 => ALetter,
        126503 => ALetter,
        126521 => ALetter,
        126523 => ALetter,
        126530 => ALetter,
        126535 => ALetter,
        126537 => ALetter,
        126539 => ALetter,
        126548 => ALetter,
        126551 => ALetter,
        126553 => ALetter,
        126555 => ALetter,
        126557 => ALetter,
        126559 => ALetter,
        126564 => ALetter,
        126590 => ALetter,
        58 => MidLetter,
        183 => MidLetter,
        727 => MidLetter,
        903 => MidLetter,
        1524 => MidLetter,
        8231 => MidLetter,
        65043 => MidLetter,
        65109 => MidLetter,
        65306 => MidLetter,
        44 => MidNum,
        59 => MidNum,
        894 => MidNum,
        1417 => MidNum,
        1644 => MidNum,
        2040 => MidNum,
        8260 => MidNum,
        65040 => MidNum,
        65044 => MidNum,
        65104 => MidNum,
        65108 => MidNum,
        65292 => MidNum,
        65307 => MidNum,
        46 => MidNumLet,
        8216 => MidNumLet,
        8217 => MidNumLet,
        8228 => MidNumLet,
        65106 => MidNumLet,
        65287 => MidNumLet,
        65294 => MidNumLet,
        1643 => Numeric,
        95 => ExtendNumLet,
        8239 => ExtendNumLet,
        8276 => ExtendNumLet,
        65343 => ExtendNumLet,
        9757 => E_Base,
        9977 => E_Base,
        127877 => E_Base,
        128110 => E_Base,
        128124 => E_Base,
        128170 => E_Base,
        128373 => E_Base,
        128378 => E_Base,
        128400 => E_Base,
        128675 => E_Base,
        128704 => E_Base,
        129318 => E_Base,
        129328 => E_Base,
        8205 => ZWJ,
        10084 => Glue_After_Zwj,
        128139 => Glue_After_Zwj,
        128488 => Glue_After_Zwj,
        ];
    public static function get(code:Int):WordValuesEnum {
        if (code >= 1488 && code <= 1514) return Hebrew_Letter;
        if (code >= 1520 && code <= 1522) return Hebrew_Letter;
        if (code >= 64287 && code <= 64296) return Hebrew_Letter;
        if (code >= 64298 && code <= 64310) return Hebrew_Letter;
        if (code >= 64312 && code <= 64316) return Hebrew_Letter;
        if (code >= 64320 && code <= 64321) return Hebrew_Letter;
        if (code >= 64323 && code <= 64324) return Hebrew_Letter;
        if (code >= 64326 && code <= 64335) return Hebrew_Letter;
        if (code >= 11 && code <= 12) return Newline;
        if (code >= 768 && code <= 879) return Extend;
        if (code >= 1155 && code <= 1159) return Extend;
        if (code >= 1160 && code <= 1161) return Extend;
        if (code >= 1425 && code <= 1469) return Extend;
        if (code >= 1473 && code <= 1474) return Extend;
        if (code >= 1476 && code <= 1477) return Extend;
        if (code >= 1552 && code <= 1562) return Extend;
        if (code >= 1611 && code <= 1631) return Extend;
        if (code >= 1750 && code <= 1756) return Extend;
        if (code >= 1759 && code <= 1764) return Extend;
        if (code >= 1767 && code <= 1768) return Extend;
        if (code >= 1770 && code <= 1773) return Extend;
        if (code >= 1840 && code <= 1866) return Extend;
        if (code >= 1958 && code <= 1968) return Extend;
        if (code >= 2027 && code <= 2035) return Extend;
        if (code >= 2070 && code <= 2073) return Extend;
        if (code >= 2075 && code <= 2083) return Extend;
        if (code >= 2085 && code <= 2087) return Extend;
        if (code >= 2089 && code <= 2093) return Extend;
        if (code >= 2137 && code <= 2139) return Extend;
        if (code >= 2260 && code <= 2273) return Extend;
        if (code >= 2275 && code <= 2306) return Extend;
        if (code >= 2366 && code <= 2368) return Extend;
        if (code >= 2369 && code <= 2376) return Extend;
        if (code >= 2377 && code <= 2380) return Extend;
        if (code >= 2382 && code <= 2383) return Extend;
        if (code >= 2385 && code <= 2391) return Extend;
        if (code >= 2402 && code <= 2403) return Extend;
        if (code >= 2434 && code <= 2435) return Extend;
        if (code >= 2494 && code <= 2496) return Extend;
        if (code >= 2497 && code <= 2500) return Extend;
        if (code >= 2503 && code <= 2504) return Extend;
        if (code >= 2507 && code <= 2508) return Extend;
        if (code >= 2530 && code <= 2531) return Extend;
        if (code >= 2561 && code <= 2562) return Extend;
        if (code >= 2622 && code <= 2624) return Extend;
        if (code >= 2625 && code <= 2626) return Extend;
        if (code >= 2631 && code <= 2632) return Extend;
        if (code >= 2635 && code <= 2637) return Extend;
        if (code >= 2672 && code <= 2673) return Extend;
        if (code >= 2689 && code <= 2690) return Extend;
        if (code >= 2750 && code <= 2752) return Extend;
        if (code >= 2753 && code <= 2757) return Extend;
        if (code >= 2759 && code <= 2760) return Extend;
        if (code >= 2763 && code <= 2764) return Extend;
        if (code >= 2786 && code <= 2787) return Extend;
        if (code >= 2818 && code <= 2819) return Extend;
        if (code >= 2881 && code <= 2884) return Extend;
        if (code >= 2887 && code <= 2888) return Extend;
        if (code >= 2891 && code <= 2892) return Extend;
        if (code >= 2914 && code <= 2915) return Extend;
        if (code >= 3006 && code <= 3007) return Extend;
        if (code >= 3009 && code <= 3010) return Extend;
        if (code >= 3014 && code <= 3016) return Extend;
        if (code >= 3018 && code <= 3020) return Extend;
        if (code >= 3073 && code <= 3075) return Extend;
        if (code >= 3134 && code <= 3136) return Extend;
        if (code >= 3137 && code <= 3140) return Extend;
        if (code >= 3142 && code <= 3144) return Extend;
        if (code >= 3146 && code <= 3149) return Extend;
        if (code >= 3157 && code <= 3158) return Extend;
        if (code >= 3170 && code <= 3171) return Extend;
        if (code >= 3202 && code <= 3203) return Extend;
        if (code >= 3264 && code <= 3268) return Extend;
        if (code >= 3271 && code <= 3272) return Extend;
        if (code >= 3274 && code <= 3275) return Extend;
        if (code >= 3276 && code <= 3277) return Extend;
        if (code >= 3285 && code <= 3286) return Extend;
        if (code >= 3298 && code <= 3299) return Extend;
        if (code >= 3330 && code <= 3331) return Extend;
        if (code >= 3390 && code <= 3392) return Extend;
        if (code >= 3393 && code <= 3396) return Extend;
        if (code >= 3398 && code <= 3400) return Extend;
        if (code >= 3402 && code <= 3404) return Extend;
        if (code >= 3426 && code <= 3427) return Extend;
        if (code >= 3458 && code <= 3459) return Extend;
        if (code >= 3535 && code <= 3537) return Extend;
        if (code >= 3538 && code <= 3540) return Extend;
        if (code >= 3544 && code <= 3551) return Extend;
        if (code >= 3570 && code <= 3571) return Extend;
        if (code >= 3636 && code <= 3642) return Extend;
        if (code >= 3655 && code <= 3662) return Extend;
        if (code >= 3764 && code <= 3769) return Extend;
        if (code >= 3771 && code <= 3772) return Extend;
        if (code >= 3784 && code <= 3789) return Extend;
        if (code >= 3864 && code <= 3865) return Extend;
        if (code >= 3902 && code <= 3903) return Extend;
        if (code >= 3953 && code <= 3966) return Extend;
        if (code >= 3968 && code <= 3972) return Extend;
        if (code >= 3974 && code <= 3975) return Extend;
        if (code >= 3981 && code <= 3991) return Extend;
        if (code >= 3993 && code <= 4028) return Extend;
        if (code >= 4139 && code <= 4140) return Extend;
        if (code >= 4141 && code <= 4144) return Extend;
        if (code >= 4146 && code <= 4151) return Extend;
        if (code >= 4153 && code <= 4154) return Extend;
        if (code >= 4155 && code <= 4156) return Extend;
        if (code >= 4157 && code <= 4158) return Extend;
        if (code >= 4182 && code <= 4183) return Extend;
        if (code >= 4184 && code <= 4185) return Extend;
        if (code >= 4190 && code <= 4192) return Extend;
        if (code >= 4194 && code <= 4196) return Extend;
        if (code >= 4199 && code <= 4205) return Extend;
        if (code >= 4209 && code <= 4212) return Extend;
        if (code >= 4227 && code <= 4228) return Extend;
        if (code >= 4229 && code <= 4230) return Extend;
        if (code >= 4231 && code <= 4236) return Extend;
        if (code >= 4250 && code <= 4252) return Extend;
        if (code >= 4957 && code <= 4959) return Extend;
        if (code >= 5906 && code <= 5908) return Extend;
        if (code >= 5938 && code <= 5940) return Extend;
        if (code >= 5970 && code <= 5971) return Extend;
        if (code >= 6002 && code <= 6003) return Extend;
        if (code >= 6068 && code <= 6069) return Extend;
        if (code >= 6071 && code <= 6077) return Extend;
        if (code >= 6078 && code <= 6085) return Extend;
        if (code >= 6087 && code <= 6088) return Extend;
        if (code >= 6089 && code <= 6099) return Extend;
        if (code >= 6155 && code <= 6157) return Extend;
        if (code >= 6277 && code <= 6278) return Extend;
        if (code >= 6432 && code <= 6434) return Extend;
        if (code >= 6435 && code <= 6438) return Extend;
        if (code >= 6439 && code <= 6440) return Extend;
        if (code >= 6441 && code <= 6443) return Extend;
        if (code >= 6448 && code <= 6449) return Extend;
        if (code >= 6451 && code <= 6456) return Extend;
        if (code >= 6457 && code <= 6459) return Extend;
        if (code >= 6679 && code <= 6680) return Extend;
        if (code >= 6681 && code <= 6682) return Extend;
        if (code >= 6744 && code <= 6750) return Extend;
        if (code >= 6755 && code <= 6756) return Extend;
        if (code >= 6757 && code <= 6764) return Extend;
        if (code >= 6765 && code <= 6770) return Extend;
        if (code >= 6771 && code <= 6780) return Extend;
        if (code >= 6832 && code <= 6845) return Extend;
        if (code >= 6912 && code <= 6915) return Extend;
        if (code >= 6966 && code <= 6970) return Extend;
        if (code >= 6973 && code <= 6977) return Extend;
        if (code >= 6979 && code <= 6980) return Extend;
        if (code >= 7019 && code <= 7027) return Extend;
        if (code >= 7040 && code <= 7041) return Extend;
        if (code >= 7074 && code <= 7077) return Extend;
        if (code >= 7078 && code <= 7079) return Extend;
        if (code >= 7080 && code <= 7081) return Extend;
        if (code >= 7083 && code <= 7085) return Extend;
        if (code >= 7144 && code <= 7145) return Extend;
        if (code >= 7146 && code <= 7148) return Extend;
        if (code >= 7151 && code <= 7153) return Extend;
        if (code >= 7154 && code <= 7155) return Extend;
        if (code >= 7204 && code <= 7211) return Extend;
        if (code >= 7212 && code <= 7219) return Extend;
        if (code >= 7220 && code <= 7221) return Extend;
        if (code >= 7222 && code <= 7223) return Extend;
        if (code >= 7376 && code <= 7378) return Extend;
        if (code >= 7380 && code <= 7392) return Extend;
        if (code >= 7394 && code <= 7400) return Extend;
        if (code >= 7410 && code <= 7411) return Extend;
        if (code >= 7416 && code <= 7417) return Extend;
        if (code >= 7616 && code <= 7669) return Extend;
        if (code >= 7675 && code <= 7679) return Extend;
        if (code >= 8400 && code <= 8412) return Extend;
        if (code >= 8413 && code <= 8416) return Extend;
        if (code >= 8418 && code <= 8420) return Extend;
        if (code >= 8421 && code <= 8432) return Extend;
        if (code >= 11503 && code <= 11505) return Extend;
        if (code >= 11744 && code <= 11775) return Extend;
        if (code >= 12330 && code <= 12333) return Extend;
        if (code >= 12334 && code <= 12335) return Extend;
        if (code >= 12441 && code <= 12442) return Extend;
        if (code >= 42608 && code <= 42610) return Extend;
        if (code >= 42612 && code <= 42621) return Extend;
        if (code >= 42654 && code <= 42655) return Extend;
        if (code >= 42736 && code <= 42737) return Extend;
        if (code >= 43043 && code <= 43044) return Extend;
        if (code >= 43045 && code <= 43046) return Extend;
        if (code >= 43136 && code <= 43137) return Extend;
        if (code >= 43188 && code <= 43203) return Extend;
        if (code >= 43204 && code <= 43205) return Extend;
        if (code >= 43232 && code <= 43249) return Extend;
        if (code >= 43302 && code <= 43309) return Extend;
        if (code >= 43335 && code <= 43345) return Extend;
        if (code >= 43346 && code <= 43347) return Extend;
        if (code >= 43392 && code <= 43394) return Extend;
        if (code >= 43444 && code <= 43445) return Extend;
        if (code >= 43446 && code <= 43449) return Extend;
        if (code >= 43450 && code <= 43451) return Extend;
        if (code >= 43453 && code <= 43456) return Extend;
        if (code >= 43561 && code <= 43566) return Extend;
        if (code >= 43567 && code <= 43568) return Extend;
        if (code >= 43569 && code <= 43570) return Extend;
        if (code >= 43571 && code <= 43572) return Extend;
        if (code >= 43573 && code <= 43574) return Extend;
        if (code >= 43698 && code <= 43700) return Extend;
        if (code >= 43703 && code <= 43704) return Extend;
        if (code >= 43710 && code <= 43711) return Extend;
        if (code >= 43756 && code <= 43757) return Extend;
        if (code >= 43758 && code <= 43759) return Extend;
        if (code >= 44003 && code <= 44004) return Extend;
        if (code >= 44006 && code <= 44007) return Extend;
        if (code >= 44009 && code <= 44010) return Extend;
        if (code >= 65024 && code <= 65039) return Extend;
        if (code >= 65056 && code <= 65071) return Extend;
        if (code >= 65438 && code <= 65439) return Extend;
        if (code >= 66422 && code <= 66426) return Extend;
        if (code >= 68097 && code <= 68099) return Extend;
        if (code >= 68101 && code <= 68102) return Extend;
        if (code >= 68108 && code <= 68111) return Extend;
        if (code >= 68152 && code <= 68154) return Extend;
        if (code >= 68325 && code <= 68326) return Extend;
        if (code >= 69688 && code <= 69702) return Extend;
        if (code >= 69759 && code <= 69761) return Extend;
        if (code >= 69808 && code <= 69810) return Extend;
        if (code >= 69811 && code <= 69814) return Extend;
        if (code >= 69815 && code <= 69816) return Extend;
        if (code >= 69817 && code <= 69818) return Extend;
        if (code >= 69888 && code <= 69890) return Extend;
        if (code >= 69927 && code <= 69931) return Extend;
        if (code >= 69933 && code <= 69940) return Extend;
        if (code >= 70016 && code <= 70017) return Extend;
        if (code >= 70067 && code <= 70069) return Extend;
        if (code >= 70070 && code <= 70078) return Extend;
        if (code >= 70079 && code <= 70080) return Extend;
        if (code >= 70090 && code <= 70092) return Extend;
        if (code >= 70188 && code <= 70190) return Extend;
        if (code >= 70191 && code <= 70193) return Extend;
        if (code >= 70194 && code <= 70195) return Extend;
        if (code >= 70198 && code <= 70199) return Extend;
        if (code >= 70368 && code <= 70370) return Extend;
        if (code >= 70371 && code <= 70378) return Extend;
        if (code >= 70400 && code <= 70401) return Extend;
        if (code >= 70402 && code <= 70403) return Extend;
        if (code >= 70462 && code <= 70463) return Extend;
        if (code >= 70465 && code <= 70468) return Extend;
        if (code >= 70471 && code <= 70472) return Extend;
        if (code >= 70475 && code <= 70477) return Extend;
        if (code >= 70498 && code <= 70499) return Extend;
        if (code >= 70502 && code <= 70508) return Extend;
        if (code >= 70512 && code <= 70516) return Extend;
        if (code >= 70709 && code <= 70711) return Extend;
        if (code >= 70712 && code <= 70719) return Extend;
        if (code >= 70720 && code <= 70721) return Extend;
        if (code >= 70722 && code <= 70724) return Extend;
        if (code >= 70832 && code <= 70834) return Extend;
        if (code >= 70835 && code <= 70840) return Extend;
        if (code >= 70843 && code <= 70846) return Extend;
        if (code >= 70847 && code <= 70848) return Extend;
        if (code >= 70850 && code <= 70851) return Extend;
        if (code >= 71087 && code <= 71089) return Extend;
        if (code >= 71090 && code <= 71093) return Extend;
        if (code >= 71096 && code <= 71099) return Extend;
        if (code >= 71100 && code <= 71101) return Extend;
        if (code >= 71103 && code <= 71104) return Extend;
        if (code >= 71132 && code <= 71133) return Extend;
        if (code >= 71216 && code <= 71218) return Extend;
        if (code >= 71219 && code <= 71226) return Extend;
        if (code >= 71227 && code <= 71228) return Extend;
        if (code >= 71231 && code <= 71232) return Extend;
        if (code >= 71342 && code <= 71343) return Extend;
        if (code >= 71344 && code <= 71349) return Extend;
        if (code >= 71453 && code <= 71455) return Extend;
        if (code >= 71456 && code <= 71457) return Extend;
        if (code >= 71458 && code <= 71461) return Extend;
        if (code >= 71463 && code <= 71467) return Extend;
        if (code >= 72752 && code <= 72758) return Extend;
        if (code >= 72760 && code <= 72765) return Extend;
        if (code >= 72850 && code <= 72871) return Extend;
        if (code >= 72874 && code <= 72880) return Extend;
        if (code >= 72882 && code <= 72883) return Extend;
        if (code >= 72885 && code <= 72886) return Extend;
        if (code >= 92912 && code <= 92916) return Extend;
        if (code >= 92976 && code <= 92982) return Extend;
        if (code >= 94033 && code <= 94078) return Extend;
        if (code >= 94095 && code <= 94098) return Extend;
        if (code >= 113821 && code <= 113822) return Extend;
        if (code >= 119141 && code <= 119142) return Extend;
        if (code >= 119143 && code <= 119145) return Extend;
        if (code >= 119149 && code <= 119154) return Extend;
        if (code >= 119163 && code <= 119170) return Extend;
        if (code >= 119173 && code <= 119179) return Extend;
        if (code >= 119210 && code <= 119213) return Extend;
        if (code >= 119362 && code <= 119364) return Extend;
        if (code >= 121344 && code <= 121398) return Extend;
        if (code >= 121403 && code <= 121452) return Extend;
        if (code >= 121499 && code <= 121503) return Extend;
        if (code >= 121505 && code <= 121519) return Extend;
        if (code >= 122880 && code <= 122886) return Extend;
        if (code >= 122888 && code <= 122904) return Extend;
        if (code >= 122907 && code <= 122913) return Extend;
        if (code >= 122915 && code <= 122916) return Extend;
        if (code >= 122918 && code <= 122922) return Extend;
        if (code >= 125136 && code <= 125142) return Extend;
        if (code >= 125252 && code <= 125258) return Extend;
        if (code >= 917536 && code <= 917631) return Extend;
        if (code >= 917760 && code <= 917999) return Extend;
        if (code >= 127462 && code <= 127487) return Regional_Indicator;
        if (code >= 1536 && code <= 1541) return Format;
        if (code >= 8206 && code <= 8207) return Format;
        if (code >= 8234 && code <= 8238) return Format;
        if (code >= 8288 && code <= 8292) return Format;
        if (code >= 8294 && code <= 8303) return Format;
        if (code >= 65529 && code <= 65531) return Format;
        if (code >= 113824 && code <= 113827) return Format;
        if (code >= 119155 && code <= 119162) return Format;
        if (code >= 12337 && code <= 12341) return Katakana;
        if (code >= 12443 && code <= 12444) return Katakana;
        if (code >= 12449 && code <= 12538) return Katakana;
        if (code >= 12540 && code <= 12542) return Katakana;
        if (code >= 12784 && code <= 12799) return Katakana;
        if (code >= 13008 && code <= 13054) return Katakana;
        if (code >= 13056 && code <= 13143) return Katakana;
        if (code >= 65382 && code <= 65391) return Katakana;
        if (code >= 65393 && code <= 65437) return Katakana;
        if (code >= 65 && code <= 90) return ALetter;
        if (code >= 97 && code <= 122) return ALetter;
        if (code >= 192 && code <= 214) return ALetter;
        if (code >= 216 && code <= 246) return ALetter;
        if (code >= 248 && code <= 442) return ALetter;
        if (code >= 444 && code <= 447) return ALetter;
        if (code >= 448 && code <= 451) return ALetter;
        if (code >= 452 && code <= 659) return ALetter;
        if (code >= 661 && code <= 687) return ALetter;
        if (code >= 688 && code <= 705) return ALetter;
        if (code >= 710 && code <= 721) return ALetter;
        if (code >= 736 && code <= 740) return ALetter;
        if (code >= 880 && code <= 883) return ALetter;
        if (code >= 886 && code <= 887) return ALetter;
        if (code >= 891 && code <= 893) return ALetter;
        if (code >= 904 && code <= 906) return ALetter;
        if (code >= 910 && code <= 929) return ALetter;
        if (code >= 931 && code <= 1013) return ALetter;
        if (code >= 1015 && code <= 1153) return ALetter;
        if (code >= 1162 && code <= 1327) return ALetter;
        if (code >= 1329 && code <= 1366) return ALetter;
        if (code >= 1377 && code <= 1415) return ALetter;
        if (code >= 1568 && code <= 1599) return ALetter;
        if (code >= 1601 && code <= 1610) return ALetter;
        if (code >= 1646 && code <= 1647) return ALetter;
        if (code >= 1649 && code <= 1747) return ALetter;
        if (code >= 1765 && code <= 1766) return ALetter;
        if (code >= 1774 && code <= 1775) return ALetter;
        if (code >= 1786 && code <= 1788) return ALetter;
        if (code >= 1810 && code <= 1839) return ALetter;
        if (code >= 1869 && code <= 1957) return ALetter;
        if (code >= 1994 && code <= 2026) return ALetter;
        if (code >= 2036 && code <= 2037) return ALetter;
        if (code >= 2048 && code <= 2069) return ALetter;
        if (code >= 2112 && code <= 2136) return ALetter;
        if (code >= 2208 && code <= 2228) return ALetter;
        if (code >= 2230 && code <= 2237) return ALetter;
        if (code >= 2308 && code <= 2361) return ALetter;
        if (code >= 2392 && code <= 2401) return ALetter;
        if (code >= 2418 && code <= 2432) return ALetter;
        if (code >= 2437 && code <= 2444) return ALetter;
        if (code >= 2447 && code <= 2448) return ALetter;
        if (code >= 2451 && code <= 2472) return ALetter;
        if (code >= 2474 && code <= 2480) return ALetter;
        if (code >= 2486 && code <= 2489) return ALetter;
        if (code >= 2524 && code <= 2525) return ALetter;
        if (code >= 2527 && code <= 2529) return ALetter;
        if (code >= 2544 && code <= 2545) return ALetter;
        if (code >= 2565 && code <= 2570) return ALetter;
        if (code >= 2575 && code <= 2576) return ALetter;
        if (code >= 2579 && code <= 2600) return ALetter;
        if (code >= 2602 && code <= 2608) return ALetter;
        if (code >= 2610 && code <= 2611) return ALetter;
        if (code >= 2613 && code <= 2614) return ALetter;
        if (code >= 2616 && code <= 2617) return ALetter;
        if (code >= 2649 && code <= 2652) return ALetter;
        if (code >= 2674 && code <= 2676) return ALetter;
        if (code >= 2693 && code <= 2701) return ALetter;
        if (code >= 2703 && code <= 2705) return ALetter;
        if (code >= 2707 && code <= 2728) return ALetter;
        if (code >= 2730 && code <= 2736) return ALetter;
        if (code >= 2738 && code <= 2739) return ALetter;
        if (code >= 2741 && code <= 2745) return ALetter;
        if (code >= 2784 && code <= 2785) return ALetter;
        if (code >= 2821 && code <= 2828) return ALetter;
        if (code >= 2831 && code <= 2832) return ALetter;
        if (code >= 2835 && code <= 2856) return ALetter;
        if (code >= 2858 && code <= 2864) return ALetter;
        if (code >= 2866 && code <= 2867) return ALetter;
        if (code >= 2869 && code <= 2873) return ALetter;
        if (code >= 2908 && code <= 2909) return ALetter;
        if (code >= 2911 && code <= 2913) return ALetter;
        if (code >= 2949 && code <= 2954) return ALetter;
        if (code >= 2958 && code <= 2960) return ALetter;
        if (code >= 2962 && code <= 2965) return ALetter;
        if (code >= 2969 && code <= 2970) return ALetter;
        if (code >= 2974 && code <= 2975) return ALetter;
        if (code >= 2979 && code <= 2980) return ALetter;
        if (code >= 2984 && code <= 2986) return ALetter;
        if (code >= 2990 && code <= 3001) return ALetter;
        if (code >= 3077 && code <= 3084) return ALetter;
        if (code >= 3086 && code <= 3088) return ALetter;
        if (code >= 3090 && code <= 3112) return ALetter;
        if (code >= 3114 && code <= 3129) return ALetter;
        if (code >= 3160 && code <= 3162) return ALetter;
        if (code >= 3168 && code <= 3169) return ALetter;
        if (code >= 3205 && code <= 3212) return ALetter;
        if (code >= 3214 && code <= 3216) return ALetter;
        if (code >= 3218 && code <= 3240) return ALetter;
        if (code >= 3242 && code <= 3251) return ALetter;
        if (code >= 3253 && code <= 3257) return ALetter;
        if (code >= 3296 && code <= 3297) return ALetter;
        if (code >= 3313 && code <= 3314) return ALetter;
        if (code >= 3333 && code <= 3340) return ALetter;
        if (code >= 3342 && code <= 3344) return ALetter;
        if (code >= 3346 && code <= 3386) return ALetter;
        if (code >= 3412 && code <= 3414) return ALetter;
        if (code >= 3423 && code <= 3425) return ALetter;
        if (code >= 3450 && code <= 3455) return ALetter;
        if (code >= 3461 && code <= 3478) return ALetter;
        if (code >= 3482 && code <= 3505) return ALetter;
        if (code >= 3507 && code <= 3515) return ALetter;
        if (code >= 3520 && code <= 3526) return ALetter;
        if (code >= 3904 && code <= 3911) return ALetter;
        if (code >= 3913 && code <= 3948) return ALetter;
        if (code >= 3976 && code <= 3980) return ALetter;
        if (code >= 4256 && code <= 4293) return ALetter;
        if (code >= 4304 && code <= 4346) return ALetter;
        if (code >= 4349 && code <= 4680) return ALetter;
        if (code >= 4682 && code <= 4685) return ALetter;
        if (code >= 4688 && code <= 4694) return ALetter;
        if (code >= 4698 && code <= 4701) return ALetter;
        if (code >= 4704 && code <= 4744) return ALetter;
        if (code >= 4746 && code <= 4749) return ALetter;
        if (code >= 4752 && code <= 4784) return ALetter;
        if (code >= 4786 && code <= 4789) return ALetter;
        if (code >= 4792 && code <= 4798) return ALetter;
        if (code >= 4802 && code <= 4805) return ALetter;
        if (code >= 4808 && code <= 4822) return ALetter;
        if (code >= 4824 && code <= 4880) return ALetter;
        if (code >= 4882 && code <= 4885) return ALetter;
        if (code >= 4888 && code <= 4954) return ALetter;
        if (code >= 4992 && code <= 5007) return ALetter;
        if (code >= 5024 && code <= 5109) return ALetter;
        if (code >= 5112 && code <= 5117) return ALetter;
        if (code >= 5121 && code <= 5740) return ALetter;
        if (code >= 5743 && code <= 5759) return ALetter;
        if (code >= 5761 && code <= 5786) return ALetter;
        if (code >= 5792 && code <= 5866) return ALetter;
        if (code >= 5870 && code <= 5872) return ALetter;
        if (code >= 5873 && code <= 5880) return ALetter;
        if (code >= 5888 && code <= 5900) return ALetter;
        if (code >= 5902 && code <= 5905) return ALetter;
        if (code >= 5920 && code <= 5937) return ALetter;
        if (code >= 5952 && code <= 5969) return ALetter;
        if (code >= 5984 && code <= 5996) return ALetter;
        if (code >= 5998 && code <= 6000) return ALetter;
        if (code >= 6176 && code <= 6210) return ALetter;
        if (code >= 6212 && code <= 6263) return ALetter;
        if (code >= 6272 && code <= 6276) return ALetter;
        if (code >= 6279 && code <= 6312) return ALetter;
        if (code >= 6320 && code <= 6389) return ALetter;
        if (code >= 6400 && code <= 6430) return ALetter;
        if (code >= 6656 && code <= 6678) return ALetter;
        if (code >= 6917 && code <= 6963) return ALetter;
        if (code >= 6981 && code <= 6987) return ALetter;
        if (code >= 7043 && code <= 7072) return ALetter;
        if (code >= 7086 && code <= 7087) return ALetter;
        if (code >= 7098 && code <= 7141) return ALetter;
        if (code >= 7168 && code <= 7203) return ALetter;
        if (code >= 7245 && code <= 7247) return ALetter;
        if (code >= 7258 && code <= 7287) return ALetter;
        if (code >= 7288 && code <= 7293) return ALetter;
        if (code >= 7296 && code <= 7304) return ALetter;
        if (code >= 7401 && code <= 7404) return ALetter;
        if (code >= 7406 && code <= 7409) return ALetter;
        if (code >= 7413 && code <= 7414) return ALetter;
        if (code >= 7424 && code <= 7467) return ALetter;
        if (code >= 7468 && code <= 7530) return ALetter;
        if (code >= 7531 && code <= 7543) return ALetter;
        if (code >= 7545 && code <= 7578) return ALetter;
        if (code >= 7579 && code <= 7615) return ALetter;
        if (code >= 7680 && code <= 7957) return ALetter;
        if (code >= 7960 && code <= 7965) return ALetter;
        if (code >= 7968 && code <= 8005) return ALetter;
        if (code >= 8008 && code <= 8013) return ALetter;
        if (code >= 8016 && code <= 8023) return ALetter;
        if (code >= 8031 && code <= 8061) return ALetter;
        if (code >= 8064 && code <= 8116) return ALetter;
        if (code >= 8118 && code <= 8124) return ALetter;
        if (code >= 8130 && code <= 8132) return ALetter;
        if (code >= 8134 && code <= 8140) return ALetter;
        if (code >= 8144 && code <= 8147) return ALetter;
        if (code >= 8150 && code <= 8155) return ALetter;
        if (code >= 8160 && code <= 8172) return ALetter;
        if (code >= 8178 && code <= 8180) return ALetter;
        if (code >= 8182 && code <= 8188) return ALetter;
        if (code >= 8336 && code <= 8348) return ALetter;
        if (code >= 8458 && code <= 8467) return ALetter;
        if (code >= 8473 && code <= 8477) return ALetter;
        if (code >= 8490 && code <= 8493) return ALetter;
        if (code >= 8495 && code <= 8500) return ALetter;
        if (code >= 8501 && code <= 8504) return ALetter;
        if (code >= 8508 && code <= 8511) return ALetter;
        if (code >= 8517 && code <= 8521) return ALetter;
        if (code >= 8544 && code <= 8578) return ALetter;
        if (code >= 8579 && code <= 8580) return ALetter;
        if (code >= 8581 && code <= 8584) return ALetter;
        if (code >= 9398 && code <= 9449) return ALetter;
        if (code >= 11264 && code <= 11310) return ALetter;
        if (code >= 11312 && code <= 11358) return ALetter;
        if (code >= 11360 && code <= 11387) return ALetter;
        if (code >= 11388 && code <= 11389) return ALetter;
        if (code >= 11390 && code <= 11492) return ALetter;
        if (code >= 11499 && code <= 11502) return ALetter;
        if (code >= 11506 && code <= 11507) return ALetter;
        if (code >= 11520 && code <= 11557) return ALetter;
        if (code >= 11568 && code <= 11623) return ALetter;
        if (code >= 11648 && code <= 11670) return ALetter;
        if (code >= 11680 && code <= 11686) return ALetter;
        if (code >= 11688 && code <= 11694) return ALetter;
        if (code >= 11696 && code <= 11702) return ALetter;
        if (code >= 11704 && code <= 11710) return ALetter;
        if (code >= 11712 && code <= 11718) return ALetter;
        if (code >= 11720 && code <= 11726) return ALetter;
        if (code >= 11728 && code <= 11734) return ALetter;
        if (code >= 11736 && code <= 11742) return ALetter;
        if (code >= 12549 && code <= 12589) return ALetter;
        if (code >= 12593 && code <= 12686) return ALetter;
        if (code >= 12704 && code <= 12730) return ALetter;
        if (code >= 40960 && code <= 40980) return ALetter;
        if (code >= 40982 && code <= 42124) return ALetter;
        if (code >= 42192 && code <= 42231) return ALetter;
        if (code >= 42232 && code <= 42237) return ALetter;
        if (code >= 42240 && code <= 42507) return ALetter;
        if (code >= 42512 && code <= 42527) return ALetter;
        if (code >= 42538 && code <= 42539) return ALetter;
        if (code >= 42560 && code <= 42605) return ALetter;
        if (code >= 42624 && code <= 42651) return ALetter;
        if (code >= 42652 && code <= 42653) return ALetter;
        if (code >= 42656 && code <= 42725) return ALetter;
        if (code >= 42726 && code <= 42735) return ALetter;
        if (code >= 42775 && code <= 42783) return ALetter;
        if (code >= 42786 && code <= 42863) return ALetter;
        if (code >= 42865 && code <= 42887) return ALetter;
        if (code >= 42891 && code <= 42894) return ALetter;
        if (code >= 42896 && code <= 42926) return ALetter;
        if (code >= 42928 && code <= 42935) return ALetter;
        if (code >= 43000 && code <= 43001) return ALetter;
        if (code >= 43003 && code <= 43009) return ALetter;
        if (code >= 43011 && code <= 43013) return ALetter;
        if (code >= 43015 && code <= 43018) return ALetter;
        if (code >= 43020 && code <= 43042) return ALetter;
        if (code >= 43072 && code <= 43123) return ALetter;
        if (code >= 43138 && code <= 43187) return ALetter;
        if (code >= 43250 && code <= 43255) return ALetter;
        if (code >= 43274 && code <= 43301) return ALetter;
        if (code >= 43312 && code <= 43334) return ALetter;
        if (code >= 43360 && code <= 43388) return ALetter;
        if (code >= 43396 && code <= 43442) return ALetter;
        if (code >= 43520 && code <= 43560) return ALetter;
        if (code >= 43584 && code <= 43586) return ALetter;
        if (code >= 43588 && code <= 43595) return ALetter;
        if (code >= 43744 && code <= 43754) return ALetter;
        if (code >= 43763 && code <= 43764) return ALetter;
        if (code >= 43777 && code <= 43782) return ALetter;
        if (code >= 43785 && code <= 43790) return ALetter;
        if (code >= 43793 && code <= 43798) return ALetter;
        if (code >= 43808 && code <= 43814) return ALetter;
        if (code >= 43816 && code <= 43822) return ALetter;
        if (code >= 43824 && code <= 43866) return ALetter;
        if (code >= 43868 && code <= 43871) return ALetter;
        if (code >= 43872 && code <= 43877) return ALetter;
        if (code >= 43888 && code <= 43967) return ALetter;
        if (code >= 43968 && code <= 44002) return ALetter;
        if (code >= 44032 && code <= 55203) return ALetter;
        if (code >= 55216 && code <= 55238) return ALetter;
        if (code >= 55243 && code <= 55291) return ALetter;
        if (code >= 64256 && code <= 64262) return ALetter;
        if (code >= 64275 && code <= 64279) return ALetter;
        if (code >= 64336 && code <= 64433) return ALetter;
        if (code >= 64467 && code <= 64829) return ALetter;
        if (code >= 64848 && code <= 64911) return ALetter;
        if (code >= 64914 && code <= 64967) return ALetter;
        if (code >= 65008 && code <= 65019) return ALetter;
        if (code >= 65136 && code <= 65140) return ALetter;
        if (code >= 65142 && code <= 65276) return ALetter;
        if (code >= 65313 && code <= 65338) return ALetter;
        if (code >= 65345 && code <= 65370) return ALetter;
        if (code >= 65440 && code <= 65470) return ALetter;
        if (code >= 65474 && code <= 65479) return ALetter;
        if (code >= 65482 && code <= 65487) return ALetter;
        if (code >= 65490 && code <= 65495) return ALetter;
        if (code >= 65498 && code <= 65500) return ALetter;
        if (code >= 65536 && code <= 65547) return ALetter;
        if (code >= 65549 && code <= 65574) return ALetter;
        if (code >= 65576 && code <= 65594) return ALetter;
        if (code >= 65596 && code <= 65597) return ALetter;
        if (code >= 65599 && code <= 65613) return ALetter;
        if (code >= 65616 && code <= 65629) return ALetter;
        if (code >= 65664 && code <= 65786) return ALetter;
        if (code >= 65856 && code <= 65908) return ALetter;
        if (code >= 66176 && code <= 66204) return ALetter;
        if (code >= 66208 && code <= 66256) return ALetter;
        if (code >= 66304 && code <= 66335) return ALetter;
        if (code >= 66352 && code <= 66368) return ALetter;
        if (code >= 66370 && code <= 66377) return ALetter;
        if (code >= 66384 && code <= 66421) return ALetter;
        if (code >= 66432 && code <= 66461) return ALetter;
        if (code >= 66464 && code <= 66499) return ALetter;
        if (code >= 66504 && code <= 66511) return ALetter;
        if (code >= 66513 && code <= 66517) return ALetter;
        if (code >= 66560 && code <= 66639) return ALetter;
        if (code >= 66640 && code <= 66717) return ALetter;
        if (code >= 66736 && code <= 66771) return ALetter;
        if (code >= 66776 && code <= 66811) return ALetter;
        if (code >= 66816 && code <= 66855) return ALetter;
        if (code >= 66864 && code <= 66915) return ALetter;
        if (code >= 67072 && code <= 67382) return ALetter;
        if (code >= 67392 && code <= 67413) return ALetter;
        if (code >= 67424 && code <= 67431) return ALetter;
        if (code >= 67584 && code <= 67589) return ALetter;
        if (code >= 67594 && code <= 67637) return ALetter;
        if (code >= 67639 && code <= 67640) return ALetter;
        if (code >= 67647 && code <= 67669) return ALetter;
        if (code >= 67680 && code <= 67702) return ALetter;
        if (code >= 67712 && code <= 67742) return ALetter;
        if (code >= 67808 && code <= 67826) return ALetter;
        if (code >= 67828 && code <= 67829) return ALetter;
        if (code >= 67840 && code <= 67861) return ALetter;
        if (code >= 67872 && code <= 67897) return ALetter;
        if (code >= 67968 && code <= 68023) return ALetter;
        if (code >= 68030 && code <= 68031) return ALetter;
        if (code >= 68112 && code <= 68115) return ALetter;
        if (code >= 68117 && code <= 68119) return ALetter;
        if (code >= 68121 && code <= 68147) return ALetter;
        if (code >= 68192 && code <= 68220) return ALetter;
        if (code >= 68224 && code <= 68252) return ALetter;
        if (code >= 68288 && code <= 68295) return ALetter;
        if (code >= 68297 && code <= 68324) return ALetter;
        if (code >= 68352 && code <= 68405) return ALetter;
        if (code >= 68416 && code <= 68437) return ALetter;
        if (code >= 68448 && code <= 68466) return ALetter;
        if (code >= 68480 && code <= 68497) return ALetter;
        if (code >= 68608 && code <= 68680) return ALetter;
        if (code >= 68736 && code <= 68786) return ALetter;
        if (code >= 68800 && code <= 68850) return ALetter;
        if (code >= 69635 && code <= 69687) return ALetter;
        if (code >= 69763 && code <= 69807) return ALetter;
        if (code >= 69840 && code <= 69864) return ALetter;
        if (code >= 69891 && code <= 69926) return ALetter;
        if (code >= 69968 && code <= 70002) return ALetter;
        if (code >= 70019 && code <= 70066) return ALetter;
        if (code >= 70081 && code <= 70084) return ALetter;
        if (code >= 70144 && code <= 70161) return ALetter;
        if (code >= 70163 && code <= 70187) return ALetter;
        if (code >= 70272 && code <= 70278) return ALetter;
        if (code >= 70282 && code <= 70285) return ALetter;
        if (code >= 70287 && code <= 70301) return ALetter;
        if (code >= 70303 && code <= 70312) return ALetter;
        if (code >= 70320 && code <= 70366) return ALetter;
        if (code >= 70405 && code <= 70412) return ALetter;
        if (code >= 70415 && code <= 70416) return ALetter;
        if (code >= 70419 && code <= 70440) return ALetter;
        if (code >= 70442 && code <= 70448) return ALetter;
        if (code >= 70450 && code <= 70451) return ALetter;
        if (code >= 70453 && code <= 70457) return ALetter;
        if (code >= 70493 && code <= 70497) return ALetter;
        if (code >= 70656 && code <= 70708) return ALetter;
        if (code >= 70727 && code <= 70730) return ALetter;
        if (code >= 70784 && code <= 70831) return ALetter;
        if (code >= 70852 && code <= 70853) return ALetter;
        if (code >= 71040 && code <= 71086) return ALetter;
        if (code >= 71128 && code <= 71131) return ALetter;
        if (code >= 71168 && code <= 71215) return ALetter;
        if (code >= 71296 && code <= 71338) return ALetter;
        if (code >= 71840 && code <= 71903) return ALetter;
        if (code >= 72384 && code <= 72440) return ALetter;
        if (code >= 72704 && code <= 72712) return ALetter;
        if (code >= 72714 && code <= 72750) return ALetter;
        if (code >= 72818 && code <= 72847) return ALetter;
        if (code >= 73728 && code <= 74649) return ALetter;
        if (code >= 74752 && code <= 74862) return ALetter;
        if (code >= 74880 && code <= 75075) return ALetter;
        if (code >= 77824 && code <= 78894) return ALetter;
        if (code >= 82944 && code <= 83526) return ALetter;
        if (code >= 92160 && code <= 92728) return ALetter;
        if (code >= 92736 && code <= 92766) return ALetter;
        if (code >= 92880 && code <= 92909) return ALetter;
        if (code >= 92928 && code <= 92975) return ALetter;
        if (code >= 92992 && code <= 92995) return ALetter;
        if (code >= 93027 && code <= 93047) return ALetter;
        if (code >= 93053 && code <= 93071) return ALetter;
        if (code >= 93952 && code <= 94020) return ALetter;
        if (code >= 94099 && code <= 94111) return ALetter;
        if (code >= 113664 && code <= 113770) return ALetter;
        if (code >= 113776 && code <= 113788) return ALetter;
        if (code >= 113792 && code <= 113800) return ALetter;
        if (code >= 113808 && code <= 113817) return ALetter;
        if (code >= 119808 && code <= 119892) return ALetter;
        if (code >= 119894 && code <= 119964) return ALetter;
        if (code >= 119966 && code <= 119967) return ALetter;
        if (code >= 119973 && code <= 119974) return ALetter;
        if (code >= 119977 && code <= 119980) return ALetter;
        if (code >= 119982 && code <= 119993) return ALetter;
        if (code >= 119997 && code <= 120003) return ALetter;
        if (code >= 120005 && code <= 120069) return ALetter;
        if (code >= 120071 && code <= 120074) return ALetter;
        if (code >= 120077 && code <= 120084) return ALetter;
        if (code >= 120086 && code <= 120092) return ALetter;
        if (code >= 120094 && code <= 120121) return ALetter;
        if (code >= 120123 && code <= 120126) return ALetter;
        if (code >= 120128 && code <= 120132) return ALetter;
        if (code >= 120138 && code <= 120144) return ALetter;
        if (code >= 120146 && code <= 120485) return ALetter;
        if (code >= 120488 && code <= 120512) return ALetter;
        if (code >= 120514 && code <= 120538) return ALetter;
        if (code >= 120540 && code <= 120570) return ALetter;
        if (code >= 120572 && code <= 120596) return ALetter;
        if (code >= 120598 && code <= 120628) return ALetter;
        if (code >= 120630 && code <= 120654) return ALetter;
        if (code >= 120656 && code <= 120686) return ALetter;
        if (code >= 120688 && code <= 120712) return ALetter;
        if (code >= 120714 && code <= 120744) return ALetter;
        if (code >= 120746 && code <= 120770) return ALetter;
        if (code >= 120772 && code <= 120779) return ALetter;
        if (code >= 124928 && code <= 125124) return ALetter;
        if (code >= 125184 && code <= 125251) return ALetter;
        if (code >= 126464 && code <= 126467) return ALetter;
        if (code >= 126469 && code <= 126495) return ALetter;
        if (code >= 126497 && code <= 126498) return ALetter;
        if (code >= 126505 && code <= 126514) return ALetter;
        if (code >= 126516 && code <= 126519) return ALetter;
        if (code >= 126541 && code <= 126543) return ALetter;
        if (code >= 126545 && code <= 126546) return ALetter;
        if (code >= 126561 && code <= 126562) return ALetter;
        if (code >= 126567 && code <= 126570) return ALetter;
        if (code >= 126572 && code <= 126578) return ALetter;
        if (code >= 126580 && code <= 126583) return ALetter;
        if (code >= 126585 && code <= 126588) return ALetter;
        if (code >= 126592 && code <= 126601) return ALetter;
        if (code >= 126603 && code <= 126619) return ALetter;
        if (code >= 126625 && code <= 126627) return ALetter;
        if (code >= 126629 && code <= 126633) return ALetter;
        if (code >= 126635 && code <= 126651) return ALetter;
        if (code >= 127280 && code <= 127305) return ALetter;
        if (code >= 127312 && code <= 127337) return ALetter;
        if (code >= 127344 && code <= 127369) return ALetter;
        if (code >= 1548 && code <= 1549) return MidNum;
        if (code >= 48 && code <= 57) return Numeric;
        if (code >= 1632 && code <= 1641) return Numeric;
        if (code >= 1776 && code <= 1785) return Numeric;
        if (code >= 1984 && code <= 1993) return Numeric;
        if (code >= 2406 && code <= 2415) return Numeric;
        if (code >= 2534 && code <= 2543) return Numeric;
        if (code >= 2662 && code <= 2671) return Numeric;
        if (code >= 2790 && code <= 2799) return Numeric;
        if (code >= 2918 && code <= 2927) return Numeric;
        if (code >= 3046 && code <= 3055) return Numeric;
        if (code >= 3174 && code <= 3183) return Numeric;
        if (code >= 3302 && code <= 3311) return Numeric;
        if (code >= 3430 && code <= 3439) return Numeric;
        if (code >= 3558 && code <= 3567) return Numeric;
        if (code >= 3664 && code <= 3673) return Numeric;
        if (code >= 3792 && code <= 3801) return Numeric;
        if (code >= 3872 && code <= 3881) return Numeric;
        if (code >= 4160 && code <= 4169) return Numeric;
        if (code >= 4240 && code <= 4249) return Numeric;
        if (code >= 6112 && code <= 6121) return Numeric;
        if (code >= 6160 && code <= 6169) return Numeric;
        if (code >= 6470 && code <= 6479) return Numeric;
        if (code >= 6608 && code <= 6617) return Numeric;
        if (code >= 6784 && code <= 6793) return Numeric;
        if (code >= 6800 && code <= 6809) return Numeric;
        if (code >= 6992 && code <= 7001) return Numeric;
        if (code >= 7088 && code <= 7097) return Numeric;
        if (code >= 7232 && code <= 7241) return Numeric;
        if (code >= 7248 && code <= 7257) return Numeric;
        if (code >= 42528 && code <= 42537) return Numeric;
        if (code >= 43216 && code <= 43225) return Numeric;
        if (code >= 43264 && code <= 43273) return Numeric;
        if (code >= 43472 && code <= 43481) return Numeric;
        if (code >= 43504 && code <= 43513) return Numeric;
        if (code >= 43600 && code <= 43609) return Numeric;
        if (code >= 44016 && code <= 44025) return Numeric;
        if (code >= 66720 && code <= 66729) return Numeric;
        if (code >= 69734 && code <= 69743) return Numeric;
        if (code >= 69872 && code <= 69881) return Numeric;
        if (code >= 69942 && code <= 69951) return Numeric;
        if (code >= 70096 && code <= 70105) return Numeric;
        if (code >= 70384 && code <= 70393) return Numeric;
        if (code >= 70736 && code <= 70745) return Numeric;
        if (code >= 70864 && code <= 70873) return Numeric;
        if (code >= 71248 && code <= 71257) return Numeric;
        if (code >= 71360 && code <= 71369) return Numeric;
        if (code >= 71472 && code <= 71481) return Numeric;
        if (code >= 71904 && code <= 71913) return Numeric;
        if (code >= 72784 && code <= 72793) return Numeric;
        if (code >= 92768 && code <= 92777) return Numeric;
        if (code >= 93008 && code <= 93017) return Numeric;
        if (code >= 120782 && code <= 120831) return Numeric;
        if (code >= 125264 && code <= 125273) return Numeric;
        if (code >= 8255 && code <= 8256) return ExtendNumLet;
        if (code >= 65075 && code <= 65076) return ExtendNumLet;
        if (code >= 65101 && code <= 65103) return ExtendNumLet;
        if (code >= 9994 && code <= 9997) return E_Base;
        if (code >= 127939 && code <= 127940) return E_Base;
        if (code >= 127946 && code <= 127947) return E_Base;
        if (code >= 128066 && code <= 128067) return E_Base;
        if (code >= 128070 && code <= 128080) return E_Base;
        if (code >= 128112 && code <= 128120) return E_Base;
        if (code >= 128129 && code <= 128131) return E_Base;
        if (code >= 128133 && code <= 128135) return E_Base;
        if (code >= 128405 && code <= 128406) return E_Base;
        if (code >= 128581 && code <= 128583) return E_Base;
        if (code >= 128587 && code <= 128591) return E_Base;
        if (code >= 128692 && code <= 128694) return E_Base;
        if (code >= 129304 && code <= 129310) return E_Base;
        if (code >= 129331 && code <= 129337) return E_Base;
        if (code >= 129340 && code <= 129342) return E_Base;
        if (code >= 127995 && code <= 127999) return E_Modifier;
        if (code >= 128102 && code <= 128105) return E_Base_GAZ;
        var res = m.get(code);
        return res != null ? res : Other;
    }
}
enum WordValuesEnum {
    Newline;
    Format;
    MidNum;
    Other;
    E_Base;
    E_Base_GAZ;
    MidNumLet;
    ZWJ;
    Double_Quote;
    LF;
    Hebrew_Letter;
    MidLetter;
    E_Modifier;
    Regional_Indicator;
    Katakana;
    ExtendNumLet;
    CR;
    Numeric;
    Extend;
    ALetter;
    Single_Quote;
    Glue_After_Zwj;
}
